### ISSUE TITLE
Missing Remarketing examples

### ISSUE THREAD

**Issue by ilprima** [googleads/google-ads-java#105]
Hi, i would like to create listusers (audience) for my campaigns via API but in the remarketing folder are missing the examples to do that. 
Here the examples available for AdWords API:

AddAudience.java	
AddConversionTrackers.java	
AddCrmBasedUserList.java	
AddRuleBasedUserLists.java	
UploadConversionAdjustment.java	
UploadOfflineCallConversions.java	
UploadOfflineConversions.java	
UploadOfflineData.java

Is there a plan for the releasing of those examples also for the Google Ads API? 
In particular i would like to create listusers bases on url rules for the remarketing. Thank you

**Comment by nwbirnie** [comment]
Hey, thanks for surfacing this. It's on our backlog, and I've added your interest to having these examples ported.

For advice on implementing remarketing lists, please reach out on the [forum](https://groups.google.com/forum/#!forum/adwords-api).
