### ISSUE TITLE
COA Display Url - Optional in UI and Required in api request

### ISSUE THREAD

**Issue by saravolpo** [googleads/google-ads-java#109]
Call Only Ad setting in UI - display url field is optional
![image](https://user-images.githubusercontent.com/11612550/57837431-76fefe80-77cb-11e9-8a43-aaac7656f8db.png)

and if empty in request - we get an error from engine: **A required field was not specified or is an empty string., at mutate_operations[0].ad_group_ad_operation.create.ad.display_url**

**Comment by nwbirnie** [comment]
Hey, this is an issue with the backend API, rather than the Java client library. Could you post this on the [forum](https://groups.google.com/forum/#!forum/adwords-api) please?
