### ISSUE TITLE
ExtensionFeedItem missing device field

### ISSUE THREAD

**Issue by asdf123454321** [googleads/google-ads-java#114]
ExtensionFeedItem does not have the device field specified here:

https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.resources#extensionfeeditem

**Comment by nwbirnie** [comment]
The upcoming release for v1.3 (later today) will resolve this issue, apologies this was missed on the previous release. I know what happen on the backend and will work on a fix to avoid similar discrepancies in future.

Thanks for reporting.
