### ISSUE TITLE
Inconsistency between Ads documentation for billingSetup and ResourceNames.paymentsAccount() method

### ISSUE THREAD

**Issue by robgranger** [googleads/google-ads-java#138]
I'm trying to use the ResourceNames.paymentsAccounts() method to generate the payments accounts resource name for a billing setup create request.  

The method requires the customer id, payments profile id, and payments account id.  However, the billing setup create request documentation states that if the payments account id is sent, the payments account info (which contains the payments profile id) should NOT be sent.  The documentation also state that the billingSetups payments_account resource name is customers/{customer_id}/paymentsAccounts/{payments_account_id} and NOT customers/{customer_id}/paymentsAccounts/{payments_profile_id}~{payments_account_id}. 
 The required parameters for the ResourceNames.paymentsAccounts() method seem to conflict with the documentation.  

Which one is correct?

**Comment by nwbirnie** [comment]
In this case the documentation is correct, and the ResourceNames.payemntsAccount() implementation is wrong. I'll file a PR shortly to address this.

**Comment by robgranger** [comment]
Thanks for the very prompt response.
