### ISSUE TITLE
调用google 新api 程序卡死不动

### ISSUE THREAD

**Issue by lvganggang** [googleads/google-ads-java#146]
![image](https://user-images.githubusercontent.com/44962944/59997490-d2a48d80-968f-11e9-93a4-62aef641a7b9.png)

调用google 新api 程序卡死不动

**Comment by jradcliff** [comment]
Hi,

Sorry I can only answer in English. Could you please provide more details about your question or issue?

Thanks,
Josh, Google Ads API Team

**Comment by jradcliff** [comment]
Hi,

I'm closing this out because I haven't heard back in a few months. Please reopen and provide more details if you're still encountering issues.

Thanks,
Josh, Google Ads API Team
