### ISSUE TITLE
Maven dependency not found

### ISSUE THREAD

**Issue by gurstav** [googleads/google-ads-java#153]
Hi,

It seems that the Maven dependency for the latest release (3.1.0) is not in the central repository so the dependency is broken when trying to include it. I understand that it was not a long time ago since the latest release, but will it be uploaded to Maven soon?

http://repo1.maven.org/maven2/com/google/api-ads/google-ads/

Thanks.

**Comment by nwbirnie** [comment]
I think the release failed on the Javadoc phase @devchas can you confirm?

I was able to build the javadoc locally by setting the following in the root pom.xml:

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.0.1</version>
        <configuration>
          <maxmemory>2g</maxmemory>
```
![jvisualvm memory usage](https://user-images.githubusercontent.com/410275/60431989-05530680-9bf9-11e9-9d4c-67a93925feea.png)

Looks like we were pushing about 1g with 1 API version, and the memory scales linearly with the number of API versions. So we likely need 4g to support 5 concurrent versions. 

Best option is likely to rollback the release, update the memory to 5g and release again.

**Comment by devchas** [comment]
@nwbirnie yes, I can confirm that's the case

**Comment by devchas** [comment]
@gurstav the Maven dependency for the latest release is versioned 4.0.0 and is now in the central repository, so the dependency should work now.
