### ISSUE TITLE
MutateExtensionFeedItem failing with Location Extension

### ISSUE THREAD

**Issue by j-walker23** [googleads/google-ads-java#161]
Hello,

I saw in #106 that LocationExtension support was dropping in v1.3.
I am trying to use `targeted_campaign`, below is the error i am getting.
I can't find anything, anywhere on what that means.

<img width="670" alt="Screen Shot 2019-07-16 at 11 59 50 AM" src="https://user-images.githubusercontent.com/2018885/61317996-4a626580-a7c1-11e9-953f-bffec6a48fd4.png">

**Comment by jradcliff** [comment]
Hi,

Since this question is about the API and not specific to this particular client library for Java, please post your question to our [forum](https://groups.google.com/forum/#!forum/adwords-api) and someone from our team will be happy to help.

Thanks,
Josh, Google Ads API Team
