### ISSUE TITLE
Bidding Strategy Learning Status

### ISSUE THREAD

**Issue by dmitrii-stebliuk** [googleads/google-ads-java#164]
In AdWords UI there is a "Learning" Bidding Strategy status.

It is not available with Google Ads API.

Is it feasible this feature can be implemented by an external contributor?
Do you have any plans to implement this feature?

**Comment by nwbirnie** [comment]
It's a good question, but not something that we officially support currently. In general, I would think that this is quite hard to implement consistently - the optimization algorithms change frequently enough to make it a significant maintenance issue. Also the bidding strategies are always "learning" in the sense that they continually adjust bids based on incoming data. What exactly did you have in mind?

**Comment by dmitrii-stebliuk** [comment]
@nwbirnie Thank you for your response.
I have in mind exactly the same status I see in Adwords UI: https://ads.google.com
like that:
```
Campaign: Eligible
Active and can show ads
Bid strategy: Learning
Google Ads is optimising your new bid strategy. Performance may improve further. No action is needed at this time.
6 days left for learning
1 day since the last significant change
```
So being able to read this:
```
Bid strategy: Learning
6 days left for learning
1 day since the last significant change
```
would be super nice feature for the google ads api.
If you have it in UI why do you say it is such a pain to reuse it in API?

**Comment by dmitrii-stebliuk** [comment]
You see this "Learning" status for some days when you use smart bidding for a campaign and do some significant change on your campaign or bidding strategy.

**Comment by nwbirnie** [comment]
Interesting - so if this is already surfaced in the UI it should be easier to add to the API. I'll file a feature request on the internal issue tracker.

Please be aware that it might take a while until someone looks at it, we're currently working on [improving performance of the API](https://ads-developers.googleblog.com/2019/07/google-ads-api-returning-to-beta.html) so we're not focusing on adding new features at the moment.

Thanks again for flagging the issue.

**Comment by dmitrii-stebliuk** [comment]
@nwbirnie thank you, do I have a possibility to subscribe for the issue you create?

**Comment by nwbirnie** [comment]
Sorry, we don't publish these directly - however feel free to loop back here and I can check the status.

b/138286625

**Comment by dmitrii-stebliuk** [comment]
@dmitrii-stebliuk thank you again, I will ping once in 3 months then, if it is fine for you :)

**Comment by nwbirnie** [comment]
No worries :)

**Comment by dmitrii-stebliuk** [comment]
Hello, @nwbirnie . Do you know if there is any update on this? If it is possible to get the learning status we see in Google Ads UI through any API?

**Comment by nwbirnie** [comment]
Hey, we're looking into this at the moment. The general consensus is that we should surface the overall statuses, not just the learning status in the API. We're not working on adding this just yet, will keep an eye on this going forwards.

**Comment by jradcliff** [comment]
The [`bidding_strategy_system_status` field](https://developers.google.com/google-ads/api/reference/rpc/v17/Campaign#bidding_strategy_system_status) on `Campaign` provides information about the learning status of the strategy.
