### ISSUE TITLE
Correlate a request List with a response List

### ISSUE THREAD

**Issue by dmitrii-stebliuk** [googleads/google-ads-java#166]
Hello,

I am using `AdGroupAdServiceClient.mutateAdGroupAds` to create List of Ads, let's say with attributes (h1, h2, h3, d1, d2).
As a response I get `List[MutateAdGroupAdResult]` where each `MutateAdGroupAdResult` has only `resource_name`.

I want to persist the result in some my datastore as List[(resource_name, h1, h2, h3, d1, d2)]
Is it safe to correlate requests and responses lists by order?
Is it possible to make Google Ads API to return the whole mutated operation instead of just `resource_name`?
Is it any other technique to safely achieve my goal?

**Comment by jradcliff** [comment]
Hi,

It is safe to assume that the elements of a mutate response are in the same order as the operations in your request. The API does not have an option to return the entire operation or result in the response, so if you need that information, you can issue a follow-up `GoogleAdsService.search` request using the resource names from the mutate response in the `WHERE` clause.

Thanks,
Josh, Google Ads API Team
