### ISSUE TITLE
Update Ad

### ISSUE THREAD

**Issue by danieleago** [googleads/google-ads-java#168]
I try to update an ad using AdService/MutateAds 
if the ad type is EXTENDED_TEXT_AD the service works correctly.
if the ad type is GMAIL_AD the service fails.
By the following the request and the response:

Request
-------
MethodName: google.ads.googleads.v2.services.AdService/MutateAds
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=XXXXXX, x-goog-api-client=gl-java/1.8.0_201 gapic/ gax/ grpc/}
Body: customer_id: "XXXXXX"
operations {
  update {
    final_urls {
      value: "XXXXXX"
    }
    type: GMAIL_AD
    tracking_url_template {
      value: "XXXXXX"
    }
    resource_name: "customers/XXXXXX/ads/XXXXXX"
  }
  update_mask {
    paths: "resource_name"
    paths: "final_urls"
    paths: "tracking_url_template"
    paths: "type"
  }
}

Response
--------
Headers: Metadata(content-type=application/grpc,request-id=r1ZL8RaOBYJpVdl-3dvpEA,date=Thu, 08 Aug 2019 14:54:14 GMT,alt-svc=quic=":443"; ma=2592000; v="46,43,39")
Body: null
Failure message: errors {
  error_code {
    ad_error: INVALID_AD_TYPE
  }
  message: "Invalid Ad type. A specific type of Ad is required."
  trigger {
    string_value: ""
  }
  location {
    field_path_elements {
      field_name: "operations"
      index {
      }
    }
    field_path_elements {
      field_name: "update"
    }
    field_path_elements {
      field_name: "resource_name"
    }
  }
}

**Comment by nwbirnie** [comment]
Please ask this question on the [forum](https://groups.google.com/forum/#!forum/adwords-api) - it's not directly related to the Java client library.
