### ISSUE TITLE
How to get customerId with API?

### ISSUE THREAD

**Issue by inf3cti0n95** [googleads/google-ads-java#17]
How to get customerId with API? Which is being used as a parameter in almost all of the examples I see.

**Comment by jradcliff** [comment]
Hi,

The beta does not yet include a service that will return the list of customers available to your OAuth credentials. In the meantime, you can get the customer ID from the AdWords UI, where it appears in the upper left corner as a ten digit number separated by hyphens (`-`). When passing that to the examples, please remove the hyphens. For example, for `123-456-7890`, you should pass `1234567890` in the example.

Thanks,
Josh, Google Ads API Team
