### ISSUE TITLE
LoginCustomerId is not reset after GoogleAdsClient.toBuilder().setLoginCustomerId()

### ISSUE THREAD

**Issue by nwbirnie** [googleads/google-ads-java#174]

**Comment by jradcliff** [comment]
@nwbirnie is this still an issue?

**Comment by nwbirnie** [comment]
Yes, the transport channel provider is cached and the headers don't reset because provider.needsHeaders() returns false.

**Comment by jradcliff** [comment]
Closing since #430 fixed this issue. @nwbirnie , please LMK if I missed remaining work on this one.

**Comment by jradcliff** [comment]
Reopening since #430 isn't done yet (misread the history above).

**Comment by devchas** [comment]
A fix for this has been implemented and will be available in the next release of the library.

**Comment by jradcliff** [comment]
Fix included in release [17.0.0](https://github.com/googleads/google-ads-java/releases/tag/17.0.0).
