### ISSUE TITLE
How to add Audience and Demographic in Campaign 

### ISSUE THREAD

**Issue by thakorji007** [googleads/google-ads-java#176]
Hello sir , 

i am trying to create Display Ads Campaign and in this Campaign i need to add Audience and Demographic but i don't know How can i add it , because i can not find anything to create Audience and Demographic in Campaign 

can you please help me to find out the solution for it ?

**Comment by jradcliff** [comment]
Hi,

For questions about the API that are not specific to this library, please reach out to our experts on the [AdWords API and Google Ads API Forum](https://groups.google.com/forum/#!forum/adwords-api).

Thanks,
Josh, Google Ads API Team
