### ISSUE TITLE
Error for Select Segment

### ISSUE THREAD

**Issue by spearkkk** [googleads/google-ads-java#180]
Hello, I use google ads API but I got an error message for segments.
I want to select segment data using GoogleAdsService.
However, there is error message: 'PROHIBITED_SEGMENT_IN_SELECT_OR_WHERE_CLAUSE'.
How to get segment data using API?

MethodName: 
google.ads.googleads.v2.services.GoogleAdsService/Search

query: 
"SELECT segments.product_item_id, campaign.id, campaign.name, ad_group.id, ad_group.name, segments.device, metrics.impressions, metrics.clicks, metrics.cost_micros FROM ad_group_ad WHERE segments.date = 20191006"

com.google.ads.googleads.v2.errors.GoogleAdsException: errors {
  error_code {
    query_error: PROHIBITED_SEGMENT_IN_SELECT_OR_WHERE_CLAUSE
  }
  message: "Cannot select or filter on the following segments: \'segments.product_item_id\'(could not support requested resources: \'AD_GROUP_AD\', \'AD_GROUP_AD\'), since segment is incompatible with the resource in the FROM clause or other selected segmenting resources."
}

**Comment by jradcliff** [comment]
Hi,

For product questions like this that are not specific to a client library, please post to the [API forum](https://groups.google.com/forum/#!forum/adwords-api) instead so our experts there can help out.

Thanks,
Josh, Google Ads API Team
