### ISSUE TITLE
Unable to get campaign via recommendation, or campaign resource

### ISSUE THREAD

**Issue by lyingfromyou** [googleads/google-ads-java#182]
My query is as follows：

"SELECT recommendation.type, "
						+ "campaign.name, "
						+ "recommendation.impact, "
						+ "recommendation.campaign, "
						+ "recommendation.campaign_budget_recommendation "
						+ "FROM recommendation "
						+ "WHERE recommendation.type = CAMPAIGN_BUDGET";

I use  'googleAdsRow.getCampaign().getName().getValue()'  or 'googleAdsRow.getRecommendation().getCampaign().getValue()' ， The result is an empty string

**Comment by nwbirnie** [comment]
This is likely an issue with your query string. According to the [reference docs](https://developers.google.com/google-ads/api/fields/v1/recommendation), you can select the campaign entity with the recommendation entity.

Please ask on the [forum](https://groups.google.com/forum/#!forum/adwords-api) for the correct syntax here.
