### ISSUE TITLE
SearchPagedResponse got stuck for longtime.. without returning anything

### ISSUE THREAD

**Issue by ssureshkumar24** [googleads/google-ads-java#185]
Hi,

I am trying to get the recommendations for my google ads account, I am using the sample code mentioned here - https://github.com/googleads/google-ads-java/blob/c290a6deb3d0d358d800b2953bd1f4364455c97a/google-ads-examples/src/main/java/com/google/ads/googleads/examples/recommendations/GetTextAdRecommendations.java

When I ran the program, the authentication was successful, but there was no response from SearchGoogleAdsRequest, also no errors - it got stuck there for so long.

Is there any problem with the GoogleAdsClient services? Please let me know.

Suresh

**Comment by nwbirnie** [comment]
Hey Suresh, there should be no issue with the servers at the moment. Could you try the request again please?

**Comment by ssureshkumar24** [comment]
> 
> 
> Hey Suresh, there should be no issue with the servers at the moment. Could you try the request again please?

Hey,

thanks for the response.  Still the same issue. below is the code i am using to list the customers. it got stuck after this line - System.out.println("customer service ==>"+customerService );
there was no response. the attached file shows that the process got stuck there for long time. Not sure what went wrong. Am I doing anything wrong here? Please let me know.

```

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import com.google.ads.googleads.lib.GoogleAdsClient;
import com.google.ads.googleads.v2.errors.GoogleAdsException;
import com.google.ads.googleads.v2.services.*;

public class ListCustomers {
  public static void main(String[] args) throws IOException {
    GoogleAdsClient googleAdsClient;
    try {
      googleAdsClient = GoogleAdsClient.newBuilder()
              .fromPropertiesFile(new File("C:/DF/ads.properties")).build();
    } catch (FileNotFoundException fnfe) {
      System.err.printf("Failed to load GoogleAdsClient configuration from file. Exception: %s%n", fnfe);
      return;
    } catch (IOException ioe) {
      System.err.printf("Failed to create GoogleAdsClient. Exception: %s%n", ioe);
      return;
    }
    try {
      new ListCustomers().runExample(googleAdsClient);
    } catch (GoogleAdsException gae) {
      System.err.printf("Request ID %s failed due to GoogleAdsException. Underlying errors:%n",
          gae.getRequestId());
    }
  }
  private void runExample(GoogleAdsClient client) {
	  System.out.println("Client ==>"+client);
    try (CustomerServiceClient customerService =
        client.getLatestVersion().createCustomerServiceClient()) {
    	System.out.println("customer service ==>"+customerService ); 
      ListAccessibleCustomersResponse response =
          customerService.listAccessibleCustomers(ListAccessibleCustomersRequest.newBuilder().build());
      System.out.printf("Total results: %d%n", response.getResourceNamesCount());
      for (String customerResourceName : response.getResourceNamesList()) {
        System.out.printf("Customer resource name: %s%n", customerResourceName);
      }
    }
  }
}
```
![listcustomers](https://user-images.githubusercontent.com/34052085/68299098-02918200-00c1-11ea-8fc9-71f3f7a1b63c.png)


Suresh

**Comment by nwbirnie** [comment]
The code looks fine, I'm guessing there's an issue with your dependency setup. Can you post the dependency tree for your project? E.g. if you're using maven `mvn dependency:tree`.

**Comment by ssureshkumar24** [comment]
Here is the dependency tree, can you please take a look and point me in the right direction

[INFO] com.cloudsense.messaging:cs-digital-fulfilment-java-gaw:jar:0.6.1-SNAPSHOT
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.5:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.5:compile
[INFO] +- com.google.api-ads:ads-lib:jar:4.6.0:compile
[INFO] |  +- com.google.guava:guava:jar:20.0:compile
[INFO] |  +- com.google.inject:guice:jar:4.2.2:compile
[INFO] |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- com.google.inject.extensions:guice-assistedinject:jar:4.2.2:compile
[INFO] |  +- com.google.inject.extensions:guice-multibindings:jar:4.2.2:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- commons-configuration:commons-configuration:jar:1.10:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- net.sf.opencsv:opencsv:jar:1.8:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.7:compile
[INFO] |  +- joda-time:joda-time:jar:2.8.2:compile
[INFO] |  +- com.google.api-client:google-api-client:jar:1.23.0:compile
[INFO] |  |  \- com.google.oauth-client:google-oauth-client:jar:1.23.0:compile
[INFO] |  +- com.google.http-client:google-http-client-jackson2:jar:1.23.0:compile
[INFO] |  |  \- com.google.http-client:google-http-client:jar:1.23.0:compile
[INFO] |  |     \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |        +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |        \- commons-codec:commons-codec:jar:1.3:compile
[INFO] |  +- com.beust:jcommander:jar:1.48:compile
[INFO] |  +- com.sun.xml.bind:jaxb-ri:pom:2.3.2:compile
[INFO] |  |  \- org.glassfish.jaxb:txw2:jar:2.3.2:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  \- com.sun.activation:javax.activation:jar:1.2.0:compile
[INFO] +- com.google.api-ads:google-ads:jar:4.2.0:compile
[INFO] |  +- com.google.api:gax:jar:1.45.0:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.15.0:compile
[INFO] |  |  +- com.google.api:api-common:jar:1.7.0:compile
[INFO] |  |  \- io.opencensus:opencensus-api:jar:0.21.0:compile
[INFO] |  +- com.google.api:gax-grpc:jar:1.45.0:compile
[INFO] |  |  +- io.grpc:grpc-stub:jar:1.21.0:compile
[INFO] |  |  +- io.grpc:grpc-auth:jar:1.21.0:compile
[INFO] |  |  +- io.grpc:grpc-protobuf:jar:1.21.0:compile
[INFO] |  |  |  \- io.grpc:grpc-protobuf-lite:jar:1.21.0:compile
[INFO] |  |  +- com.google.auth:google-auth-library-credentials:jar:0.15.0:compile
[INFO] |  |  +- io.grpc:grpc-netty-shaded:jar:1.21.0:compile
[INFO] |  |  \- io.grpc:grpc-alts:jar:1.21.0:compile
[INFO] |  |     \- io.grpc:grpc-grpclb:jar:1.21.0:compile
[INFO] |  |        \- com.google.protobuf:protobuf-java-util:jar:3.7.1:compile
[INFO] |  +- com.google.api.grpc:grpc-google-common-protos:jar:1.0.0:compile
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:1.16.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.5.1:compile
[INFO] |  +- io.grpc:grpc-all:jar:1.21.0:compile
[INFO] |  |  +- io.grpc:grpc-api:jar:1.21.0:compile (version selected from constraint [1.21.0,1.21.0])
[INFO] |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.3.2:compile
[INFO] |  |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] |  |  +- io.grpc:grpc-core:jar:1.21.0:compile (version selected from constraint [1.21.0,1.21.0])
[INFO] |  |  |  +- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  |  |  +- com.google.android:annotations:jar:4.1.1.4:compile
[INFO] |  |  |  \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.21.0:compile
[INFO] |  |  +- io.grpc:grpc-context:jar:1.21.0:compile
[INFO] |  |  +- io.grpc:grpc-netty:jar:1.21.0:compile
[INFO] |  |  |  +- io.netty:netty-codec-http2:jar:4.1.34.Final:compile (version selected from constraint [4.1.34.Final,4.1.34.Final])
[INFO] |  |  |  |  +- io.netty:netty-common:jar:4.1.34.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-buffer:jar:4.1.34.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-transport:jar:4.1.34.Final:compile
[INFO] |  |  |  |  |  \- io.netty:netty-resolver:jar:4.1.34.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-codec:jar:4.1.34.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-handler:jar:4.1.34.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec-http:jar:4.1.34.Final:compile
[INFO] |  |  |  \- io.netty:netty-handler-proxy:jar:4.1.34.Final:compile
[INFO] |  |  |     \- io.netty:netty-codec-socks:jar:4.1.34.Final:compile
[INFO] |  |  +- io.grpc:grpc-okhttp:jar:1.21.0:compile
[INFO] |  |  |  +- com.squareup.okhttp:okhttp:jar:2.5.0:compile
[INFO] |  |  |  \- com.squareup.okio:okio:jar:1.13.0:compile
[INFO] |  |  +- io.grpc:grpc-protobuf-nano:jar:1.21.0:compile
[INFO] |  |  |  \- com.google.protobuf.nano:protobuf-javanano:jar:3.0.0-alpha-5:compile
[INFO] |  |  \- io.grpc:grpc-testing:jar:1.21.0:compile
[INFO] |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.7.Final:compile
[INFO] +- com.google.api-ads:adwords-axis:jar:4.6.0:compile
[INFO] |  \- com.google.api-ads:ads-lib-axis:jar:4.6.0:compile
[INFO] |     +- commons-discovery:commons-discovery:jar:0.4:compile
[INFO] |     +- javax.xml:jaxrpc-api:jar:1.1:compile
[INFO] |     +- org.apache.axis:axis:jar:1.4:compile
[INFO] |     \- wsdl4j:wsdl4j:jar:1.6.2:compile
[INFO] +- com.cloudsense.messaging:digital-fulfilment-java-common:jar:0.7.3:compile
[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.11.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.11.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-jcl:jar:2.11.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.11.1:compile
[INFO] |  +- com.cloudsense.messaging:cs-messaging:jar:0.4.4:compile
[INFO] |  |  +- org.mule:mule-core:jar:3.6.1:compile
[INFO] |  |  |  +- com.github.stephenc.eaio-uuid:uuid:jar:3.4.0:compile
[INFO] |  |  |  |  \- com.github.stephenc.eaio-grabbag:grabbag:jar:1.8.1:compile
[INFO] |  |  |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  |  |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  |  |  +- commons-pool:commons-pool:jar:1.6:compile
[INFO] |  |  |  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:compile
[INFO] |  |  |  +- org.apache.geronimo.specs:geronimo-j2ee-connector_1.5_spec:jar:1.1:compile
[INFO] |  |  |  +- com.lmax:disruptor:jar:3.3.0:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-1.2-api:jar:2.1:compile
[INFO] |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.7:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-jul:jar:2.1:compile
[INFO] |  |  |  +- asm:asm:jar:3.1:compile
[INFO] |  |  |  +- asm:asm-commons:jar:3.1:compile
[INFO] |  |  |  |  \- asm:asm-tree:jar:3.1:compile
[INFO] |  |  |  +- org.mule.mvel:mule-mvel2:jar:2.1.9-MULE-005:compile
[INFO] |  |  |  +- org.jgrapht:jgrapht-jdk1.5:jar:0.7.3:compile
[INFO] |  |  |  \- org.mule.common:mule-common:jar:3.6.1:compile
[INFO] |  |  |     +- org.apache.xmlbeans:xmlbeans:jar:2.3.0:compile
[INFO] |  |  |     +- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  |  |     +- org.json:json:jar:20140107:compile
[INFO] |  |  |     \- org.antlr:antlr-runtime:jar:3.5:compile
[INFO] |  |  |        \- org.antlr:stringtemplate:jar:3.2.1:compile
[INFO] |  |  +- org.reflections:reflections:jar:0.9.10:compile
[INFO] |  |  |  +- org.javassist:javassist:jar:3.19.0-GA:compile
[INFO] |  |  |  \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-frontend-jaxws:jar:3.1.0:compile
[INFO] |  |  |  +- xml-resolver:xml-resolver:jar:1.2:compile
[INFO] |  |  |  +- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-core:jar:3.1.0:compile
[INFO] |  |  |  |  +- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:compile
[INFO] |  |  |  |  |  \- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |  |  |  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.1:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-bindings-soap:jar:3.1.0:compile
[INFO] |  |  |  |  +- org.apache.cxf:cxf-rt-wsdl:jar:3.1.0:compile
[INFO] |  |  |  |  \- org.apache.cxf:cxf-rt-databinding-jaxb:jar:3.1.0:compile
[INFO] |  |  |  |     +- com.sun.xml.bind:jaxb-impl:jar:2.2.11:compile
[INFO] |  |  |  |     \- com.sun.xml.bind:jaxb-core:jar:2.2.11:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-bindings-xml:jar:3.1.0:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-frontend-simple:jar:3.1.0:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-ws-addr:jar:3.1.0:compile
[INFO] |  |  |     \- org.apache.cxf:cxf-rt-ws-policy:jar:3.1.0:compile
[INFO] |  |  |        \- org.apache.neethi:neethi:jar:3.0.3:compile
[INFO] |  |  \- org.apache.cxf:cxf-rt-transports-http:jar:3.1.0:compile
[INFO] |  +- net.jodah:failsafe:jar:1.0.5:compile
[INFO] |  +- com.rabbitmq:amqp-client:jar:3.6.1:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.5:compile
[INFO] |  \- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.11:compile
[INFO] |     \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] +- com.cloudsense.security:cs-security-service-java-client:jar:0.1.8:compile
[INFO] |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.52:compile
[INFO] |  |  \- org.bouncycastle:bcprov-jdk15on:jar:1.52:compile
[INFO] |  \- org.springframework:spring-web:jar:4.2.1.RELEASE:compile
[INFO] +- org.springframework:spring-context:jar:4.1.9.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.1.9.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.1.9.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:4.1.9.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.1.9.RELEASE:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.springframework:spring-test:jar:4.1.9.RELEASE:test
[INFO] +- org.mockito:mockito-all:jar:1.10.19:test
[INFO] \- org.awaitility:awaitility:jar:3.0.0:test
[INFO]    +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO]    \- org.objenesis:objenesis:jar:2.5.1:test

Thanks,
Suresh.

**Comment by ssureshkumar24** [comment]
Hi,

I think I found the cause. It was the dependency order. I just changed and it worked. Thanks for your time. Much appreciated.

Suresh
