### ISSUE TITLE
Reg: Forming a query for SearchGoogleAdsRequest

### ISSUE THREAD

**Issue by ssureshkumar24** [googleads/google-ads-java#186]
Hi,

I am trying to form a search query for Recommendation Services. Is this query similar to SQL? Can I use the keywords available in SQL like, 'IN', 'LIKE', etc.,?

Is there any help document for creating the query ?

And, how can I create an object for GetRecommendationRequest? Is there any sample program which uses this API?
Please let me know.

Suresh

**Comment by nwbirnie** [comment]
Hey, please reach out to our [forum](https://groups.google.com/forum/#!forum/adwords-api) where our API experts can help with your query.
