### ISSUE TITLE
Customer details from Customer Name with spaces

### ISSUE THREAD

**Issue by ssureshkumar24** [googleads/google-ads-java#187]
Hi,

How to get the customer details from customer name with spaces (Test Account).? 

I tried to create a query for Search, but throwing the following error,
query: "SELECT customer.resource_name, customer.id FROM customer where customer.descriptive_name = Test Account"

  error_code {
    query_error: UNEXPECTED_INPUT
  }
  message: "Error in query: unexpected input =."
}

Suresh

**Comment by nwbirnie** [comment]
Hey, please reach out to the [forum](https://groups.google.com/forum/#!forum/adwords-api) where our API experts can help with your query.
