### ISSUE TITLE
Hot to add Website visitors audiences as remarketing audience

### ISSUE THREAD

**Issue by ilprima** [googleads/google-ads-java#192]
How can i add Website visitors audiences as remarketing audience to my campaign? I searched for an example but i didn't find one.
I aslo asked time ago a similar question to creare a list of users: https://github.com/googleads/google-ads-java/issues/105

May i know also how to create audiences from a list of emails? Also for this problem i didnt find an example.

Thank you

**Comment by nwbirnie** [comment]
Hey, please reach out on the [forum](https://groups.google.com/forum/#!forum/adwords-api) for issues which aren't specific to the Java client library.

The general flow for adding user lists to campaigns is similar to the guide for the [AdWords API](https://developers.google.com/adwords/api/docs/guides/remarketing). Apologies, we don't yet have a remarketing guide/examples available for the beta API.

A quick summary is:

- First create a user list using [UserListService](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#userlistservice). 
- (Optional) Attach it at campaign level with CampaignCriterionService.
- (Optional) Attach it at ad group level with [AdGroupCriterionService](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#adgroupcriterionservice).
