### ISSUE TITLE
Determine if additional cleanup is required in GoogleAdsClient

### ISSUE THREAD

**Issue by jradcliff** [googleads/google-ads-java#2]
When running examples via `mvn exec:java`, the following warnings appear during shutdown:

```
[WARNING] thread Thread[threadDeathWatcher-1-1,1,com.google.ads.googleads.examples.basicoperations.GetCampaigns] was interrupted but is still alive after waiting at least 14995msecs
[WARNING] thread Thread[threadDeathWatcher-1-1,1,com.google.ads.googleads.examples.basicoperations.GetCampaigns] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-1,5,com.google.ads.googleads.examples.basicoperations.GetCampaigns] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-2,5,com.google.ads.googleads.examples.basicoperations.GetCampaigns] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-3,5,com.google.ads.googleads.examples.basicoperations.GetCampaigns] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-4,5,com.google.ads.googleads.examples.basicoperations.GetCampaigns] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-5,5,com.google.ads.googleads.examples.basicoperations.GetCampaigns] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-shared-destroyer-0,5,com.google.ads.googleads.examples.basicoperations.GetCampaigns] will linger despite being asked to die via interruption
[WARNING] NOTE: 7 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.google.ads.googleads.examples.basicoperations.GetCampaigns,maxpri=10]
java.lang.IllegalThreadStateException
        at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:321)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
...
```

As a workaround, I set the `cleanupDaemonThreads` option of `exec-maven-plugin` to `false` ([default is `true`](http://www.mojohaus.org/exec-maven-plugin/java-mojo.html#cleanupDaemonThreads)), but we should verify that there is no additional cleanup required in `GoogleAdsClient`.

**Comment by jradcliff** [comment]
Bumping the priority of this to P1, as we're still seeing warnings about executors not being cleaned up.

**Comment by jradcliff** [comment]
I may have been conflating:
1. *This* issue, which is about *daemon* threads
1. **Fixed** issue #63 , which is about properly closing the `GoogleAdsClient`.

Upon closer examination, *this* issue (1) does not seem like an issue to me at all. From the [Maven exec plugin docs on `cleanupDaemonThreads`](https://www.mojohaus.org/exec-maven-plugin/java-mojo.html#cleanupDaemonThreads):

> Whether to interrupt/join and possibly stop the daemon threads upon quitting. 
If this is false, maven does nothing about the daemon threads. When maven has no more work to do, the VM will normally terminate any remaining daemon threads.

The wording there requires some parsing, but my interpretation is that:
* `true` (**default**): The exec plugin will attempt to interrupt or join any daemon threads before shutting down, and complain with the warning mentioned in this issue if that process times out.
* `false`: The exec plugin will not worry about daemon threads, and will simply shut down the VM when the `mainClass` execution completes.

Given that the threads in question are *daemon* threads, the behavior for `cleanupDaemonThreads = false` looks completely reasonable to me. After all, these are daemon threads. The whole point of them is that they're background threads that shouldn't prevent VM shutdown. I don't see why, in our use case, Maven should do extra work to try to shut down daemon threads in an orderly fashion.

@nwbirnie I plan to close this as working as intended, but please let me know if you disagree.

Thanks

**Comment by nwbirnie** [comment]
So it looks a little suspicious that GAX/gRPC isn't shutting down the daemon threads on `Thread.interrupt()`. I would suggest that we run this past GAX/gRPC first, just to check if this is known/expected behaviour. I can see the scenario where a long running process only uses our library occasionally, so they wouldn't want a bunch of daemon threads running forever.

**Comment by nwbirnie** [comment]
Pretty sure we're cleaning up our clients correctly at this point.
