### ISSUE TITLE
Please fix SetAdParameters.java to use IDs instead of resource names...

### ISSUE THREAD

**Issue by AnashOommen** [googleads/google-ads-java#207]
https://github.com/googleads/google-ads-java/blob/master/google-ads-examples/src/main/java/com/google/ads/googleads/examples/campaignmanagement/SetAdParameters.java uses a resourcename as parameter. Google Ads typically focus on IDs instead, so please modify the code example to use (customerId, adGroupId, criterionId) instead.

**Comment by devchas** [comment]
This example uses IDs, not resource names, as params.
