### ISSUE TITLE
 connection timed out: googleads.googleapis.com

### ISSUE THREAD

**Issue by levelmax** [googleads/google-ads-java#219]
when i run ReachPlanServiceClient i got information as follow.
it's looks like googleads.googleapis.com can't be connectioned

![image](https://user-images.githubusercontent.com/19588185/72308189-2a035d00-36b7-11ea-8557-5d168a587a98.png)

**Comment by nwbirnie** [comment]
Hey, it's possible that this was just a transient issue with the network. Have you retried since?

Does your network possibly require a proxy to connect to HTTP servers? If so, please see the docs [here](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html).
