### ISSUE TITLE
Hi. When i use api v2.0 it`s ok, but on v4.0 or 5.0 i have error Error:java: OutOfMemoryError: insufficient memory. I dont know why. But i change nothing in source code. 

### ISSUE THREAD

**Issue by noobason11** [googleads/google-ads-java#255]
**Which version of the client library are you using?**

**Which version of Java are you using?**

**Which operating system (Linux, Windows, ...) and version?**

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]

**Expected result**

**Actual result**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by noobason11** [comment]
I use version Java 8, Windows.

**Comment by nwbirnie** [comment]
Can you elaborate on how you're using the client library please?

- How many instances of GoogleAdsClient do you create?
- How many calls do you make before running out of memory?
- Do you always run out of memory on the same service call?

Also are you remembering to close connections once they've been opened? For example:

```
try (GoogleAdsServiceClient client = googleAdsClient.getLatestVersion().createGoogleAdsServiceClient()) {

}
```
