### ISSUE TITLE
The googleAdsRow.getCampaignCriterion().getBidModifier().getValue() both return 0 when Google Ads UI Bid adjustment = "--" or -100%

### ISSUE THREAD

**Issue by rjackyi** [googleads/google-ads-java#261]
**Which version of the client library are you using?**
    
![image](https://user-images.githubusercontent.com/28681878/77630246-a9e65700-6f85-11ea-81f4-1801efecdb19.png)

**Which version of Java are you using?**
 **jre1.8.0_211**

**Which operating system (Linux, Windows, ...) and version?**
 **Linux Darwin 11.4.2 and Windows 7**

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
![image](https://user-images.githubusercontent.com/28681878/77630808-a0112380-6f86-11ea-87f4-aecfe8ed8772.png)

query = 
SELECT
   customer.id,
   customer.currency_code,
   customer.descriptive_name,
   campaign.id,
   campaign.name,
   campaign_criterion.criterion_id,
   campaign_criterion.type,
   campaign_criterion.status,
   campaign_criterion.bid_modifier,
   campaign_criterion.device.type,
   campaign_criterion.negative
FROM
   campaign_criterion
WHERE
   campaign_criterion.type IN ('DEVICE','MOBILE_DEVICE')

![image](https://user-images.githubusercontent.com/28681878/77631819-15312880-6f88-11ea-9abc-0501d9a32627.png)

**Expected result**
**we expect the return value of bid modifier can distinguish between the "--" and -100%**
 **But all the device bid modifier result are "0".  Is there any other way to recognize them?**
**As you can see in the UI of below image**
![image](https://user-images.githubusercontent.com/28681878/77634293-ae157300-6f8b-11ea-9f36-24e78fa4c276.png)

**Actual result**
![image](https://user-images.githubusercontent.com/28681878/77632312-c8018680-6f88-11ea-81f0-29bbf327653c.png)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by nwbirnie** [comment]
Hey, thanks for reaching out. You can use `CampaignCriterion.hasBidModifier()` to detect if the bid modifier was present or not. 

The general idea is that all [scalar value type fields](https://developers.google.com/protocol-buffers/docs/proto3#scalar) in a protocol buffer (v3) message have a default value. So let's say you have a message:
```
message CampaignCriterion {
  double bid_modifier = 1;
}
```
When you send a response not containing this field, it will always be 0.
```
CampaignCriterion c = CampaignCrtierion.newBuilder().build();
c.getBidModifier(); // returns 0.0
```
To represent presence in this message, we add a wrapper type DoubleValue.
```
message DoubleValue {
  double value = 1;
}

message CampaignCriterion {
  DoubleValue bid_modifier = 1;
}
```
Now when you access the wrapped value, you still get back 0.0, but you can also test to see if the value was present:
```
CampaignCriterion c = CampaignCrtierion.newBuilder().build();
c.getBidModifier().getValue(); // returns 0.0
c.hasBidModifier(); // returns false
``` 
All scalar values that are optional in Google Ads API are represented using wrapper types.

Hope this helps, please let me know if you have any questions.
