### ISSUE TITLE
Migrate examples to use nested builder pattern

### ISSUE THREAD

**Issue by nwbirnie** [googleads/google-ads-java#284]
**Describe the problem you are trying to solve**

All library examples should use a consistent pattern for protobuf builders. In some cases we create the builder for each object separately and call `OuterBuilder.setInner(InnerBuilder.newBuilder().setFoo("bar").build())` other times we create one builder and use `OuterBuilder.getInnerBuilder().setFoo("bar")`.

**Describe the solution you would like**

Converge on the inner builder pattern which is a better paradigm to use.

**Describe alternatives you've considered**

**Additional context**

**Comment by jradcliff** [comment]
We should also be consistent about whether we call `.build()` on every builder. Many methods accept either a builder or a built object. I propose that we only call `.build()`:

1.  When required by a method call accepting the object as a parameter.
1.  On the 'top-level' resource. For example, if building [`AdGroupAd`](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.resources#adgroupad) objects, call `build()` on the `AdGroupAd.Builder` but not on each one's inner `Ad` object.

**Comment by nwbirnie** [comment]
@jradcliff agreed

**Comment by nwbirnie** [comment]
It seems this commonly comes up as a point of confusion in code reviews so dropping the request.
