### ISSUE TITLE
CompletableFuture DeadlineExceededException

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#301]
Hello!

I hesitate to file this report as I'm mostly looking for guidance on ways to mitigate this error or avoid it altogether. 

I am creating an ExecutorService fixed thread pool and submitting CompletableFuture objects to it. These CompletableFutures each may create their own GoogleAdsClient via the newBuilder() method.

Skeleton code:

final ExecutorService rsPool = Executors.newFixedThreadPool( 3 );
final List<CompletableFuture<RSFuture>> futures = Lists.newArrayList();

futures.add( CompletableFuture.completedFuture( rsFuture ).thenComposeAsync( this::processFuture, rsPool ) );

futures.forEach(  CompletableFuture::join );

final GoogleAdsClient googleAdsClient = GoogleAdsClient.newBuilder()
                .setCredentials( credentials )
                .setDeveloperToken( devToken )
                .setLoginCustomerId( loginCustomerId )
                .build();

I am not able to replicate the error with any sort of regularity, but sometimes these futures fail with the following error:

Caused by: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 3599999947000ns. [buffered_nanos=63573020, buffered_nanos=96300251, remote_addr=googleads.googleapis.com/172.217.9.74:443]

Full stack trace pasted at the bottom of this report.

These GoogleAdsClient instances always create GoogleAdsServiceClient objects via the try-with-resources mechanism.

Should I be caching and re-using ( for a short time frame ) the constructed GoogleAdsClient objects?

Any other best practices to help sidestep this error?

Thanks
Pete

**Which version of the client library are you using?**
com.google.api-ads:google-ads:5.1.0

**Which version of Java are you using?**
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

**Which operating system (Linux, Windows, ...) and version?**
Linux ip-172-31-154-182 4.14.133-88.105.amzn1.x86_64 #1 SMP Thu Jul 11 00:44:15 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Caused by: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 3599999947000ns. [buffered_nanos=63573020, buffered_nanos=96300251, remote_addr=googleads.googleapis.com/172.217.9.74:443]
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:51)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1039)
at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1165)
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:749)
at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:520)
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:495)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:111)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

**Comment by nwbirnie** [comment]
It's most likely that you're getting DEADLINE_EXCEEDED from the API because the RPC is timing out. Our default deadline is 60 minutes. What operations are you running here? Are they long running?

**Comment by nwbirnie** [comment]
You can also override the deadline by specifying a GrpcCallContext on each API call. For example:
```
try (CampaignBudgetServiceClient campaignBudgetServiceClient =
        googleAdsClient.getLatestVersion().createCampaignBudgetServiceClient()) {
      MutateCampaignBudgetsResponse response =
          campaignBudgetServiceClient
              .mutateCampaignBudgetsCallable()
              .call(
                  request,
                  GrpcCallContext.createDefault()
                      .withCallOptions(
                          CallOptions.DEFAULT.withDeadline(Deadline.after(10, TimeUnit.HOURS))));
```

**Comment by PeterLavetsky** [comment]
Hi Nick,

In this instance all of the operations are GoogleAdsServiceClient search requests. None of the operations are long running. 

try ( final GoogleAdsServiceClient googleAdsServiceClient = googleAdsClient.getLatestVersion().createGoogleAdsServiceClient() ) {

                final GoogleAdsServiceClient.SearchPagedResponse searchPagedResponse = googleAdsServiceClient.search( request );

                return Lists.newArrayList( searchPagedResponse.iterateAll());
            }

Pete

**Comment by nwbirnie** [comment]
It's very possible to have a search request take longer than 1 hour to complete. It might be a good idea to check how long these requests actually take to execute. Is it possible that you have some query + account combinations that exhibit worst-case behavior? The GAS.search() server will first materialize the entire result set, prior to returning the response. 

Also consider whether you actually need all the data that you're requesting. Adding a filter for e.g. LAST_7_DAYS could considerably speed up your queries.

As an aside, it's worth considering switching these over from the paging API -> streaming API. This includes useful primitives for running async/non-blocking processing.

**Comment by PeterLavetsky** [comment]
I can say with 100% certainty that the queries we're running do not take over an hour to complete.

This problem only arose when we migrated to the async / thread pool implementation.

I'll look into the streaming API

Thanks
Pete

**Comment by nwbirnie** [comment]
It could also be that there's an ongoing outage on our side. I'd suggest starting a thread on the [forum](https://groups.google.com/forum/#!forum/adwords-api) to check.

I'm guessing if this is related to threading issues, that the streaming API should solve this. However, there shouldn't be any issue with reusing the GoogleAdsClient across threads, as you mention. Nor should there be any issue with creating many new GoogleAdsServiceClients. Please let me know if one of these actually fixes the problem, since this would point towards there being an issue with our library.

**Comment by PeterLavetsky** [comment]
Nick,

I've implemented the Streaming API and will report back after a few days of data collection. 

This async process is part of a job that runs overnight for thousands of distinct CIDs and our DeadlineExceeded error rate before was about 4.7%.

Does the following code adhere to current best practices? We're not interested in working with subsets of the complete data which is why we iterate, add to collection, and then return the entire dataset.

```
final List<GoogleAdsRow> rows = Lists.newArrayList();

final ServerStream<SearchGoogleAdsStreamResponse> stream = googleAdsServiceClient.searchStreamCallable().call( request );

for( final SearchGoogleAdsStreamResponse response : stream ) {
    rows.addAll( response.getResultsList() );
}

return rows;
```

Thanks
Pete

**Comment by nwbirnie** [comment]
Yes, what's there looks good. I can't see the creation of the googleAdsServiceClient, so FYI this should be (1) closed via AutoClosable and (2) reused between threads.

I'd like to take a look at the requests on our server to see if there's anything clearly broken there. Could you share a couple of the CIDs that you were seeing deadline exceeded errors on please?

Also, you can enable full logging from the gRPC stack by setting the level for `io.grpc=ALL`. Can you take a look there and see if there's anything to explain this? Be careful if you post anything here since this will contain unredacted credentials.

**Comment by PeterLavetsky** [comment]
When getting the CIDs for you I noticed that all the stack traces I inspected were coming from code where we are searching for Campaign Criterion or AdGroup Criterion. This is something I missed when reporting the original "bug".

Here are 3 CIDs that failed with DeadlineException on 6/19/2020 between the hours of 1am EST and 4am EST. 

```
2519278641
3001010842
2513464472
```

Regarding the code, we are grabbing the GoogleAdsServiceClient via try-with-resources so yes should be AutoClosable.

```
try ( final GoogleAdsServiceClient googleAdsServiceClient = googleAdsClient.getLatestVersion().createGoogleAdsServiceClient() ) {
    //
    streamCallable.call( request )
    //

}
```

However, regarding "(2) reused between threads", our GoogleAdsClient is newly constructed each time we make it to this point in the code.

Broadly:

final ExecutorService rsPool = Executors.newFixedThreadPool( ASYNC_POOL_SIZE );
final List<CompletableFuture<RSFuture>> futures = Lists.newArrayList();

futures.add( getsCampaigns )
futures.add( getsAdGroups )
futures.add( getsAdGroupNegativeKeywords )

futures.forEach( CompletableFuture::join );

async( getCampaigns -> get new GoogleAdsClient().getLatestVersion().createGoogleAdsServiceClient() )
async( getAdGroups -> get new GoogleAdsClient().getLatestVersion().createGoogleAdsServiceClient() )
async( getAdGroupNegativeKeywords -> get new GoogleAdsClient().getLatestVersion().createGoogleAdsServiceClient() )

We're not re-using the same GoogleAdsClient between threads.

Going back to the fact that the problem seems to be stemming from Campaign Criterion and AdGroup Criterion searches, those queries are a bit gross from our side, in that we're asking for many / most fields across 4 different resources: Campaign, UserInterest, UserList and CampaignCriterion.

The queries are not different when using the paging API vs the streaming API, and I've only witnessed this error when doing the calls asynchronously, but perhaps this is some additional color that will give a better picture of what's going on.

I'll see if logging io.grpc=ALL turns up anything, but I probably won't have data back on that for at least a day or two as I have not been able to replicate this problem working locally and not in big batches.

Thanks
Pete

**Comment by nwbirnie** [comment]
I checked our logs and don't see any evidence of DEADLINE_EXCEEDED being returned from the server side. In fact, the longest request was ~ 2 seconds (per page).

`CampaignCriterion` and `AdGroupCriterion` can potentially be very large queries. There can easily be millions of rows returned, and more if segments are used (linear in number of distinct fields in segments). It would be worth checking if the query actually executes server side, i.e. if you actually get rows back before the deadline is hit. Similarly, it would be good to check if 1 hour actually elapses between when you send the request and when the deadline is hit.

I've reported an issue with the [middleware folks](https://github.com/googleapis/gax-java/issues/1132) (GAX) to check if there's any best practices we're not following for multi-threading.

**Comment by PeterLavetsky** [comment]
Nick,

I appreciate your continued effort to resolve this with us.

Using the Streaming API our DeadlineExceeded error rate last night was 0.5%. This compares to a 4.7% error rate on the Paging API the night before. The same accounts and the same queries were issued both nights.

4140203075 is a CID with a DeadlineExceeded error last night.

I did confirm that the error does throw 1 hour after the request is issued:

```
2020-06-23 07:15:05,394 INFO  Asynchronous : Ad Schedules
2020-06-23 08:15:05,430 ERROR 
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.RuntimeException: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 3599999966897ns. [buffered_nanos=63037051, buffered_nanos=78498570, remote_addr=googleads.googleapis.com/216.58.192.202:443]
```

I should note here that after the async call for Ad Schedules ( Campaign Criterion ) at 07:15 was issued, there were other async search calls for the same CID ( but different queries ) issued afterwards that did respond successfully in a timely manner.

All search queries construct a new GoogleAdsClient that in turn makes the try-with-resources createGoogleAdsServiceClient() call.

The following is munged down, but with minimal and irrelevant hand waving. Every search call goes through:

```
public List<GoogleAdsRow> search( final Long ourCustomerId, final Long googleCID, final String query ) {

    final ApiCredentials apiCredentials = getApiCredentialsByCustomerId( ourCustomerId );

    final Credentials googleCredentials = UserCredentials.newBuilder()
            .setClientId( apiCredentials.getClientId() )
            .setClientSecret( apiCredentials.getClientSecret() )
            .setRefreshToken( apiCredentials.getRefreshToken() )
            .build();

    final GoogleAdsClient googleAdsClient =  GoogleAdsClient.newBuilder()
            .setCredentials( googleCredentials )
            .setDeveloperToken( apiCredentials.getDeveloperToken() )
            .setLoginCustomerId( googleCID )
            .build();

    final SearchGoogleAdsStreamRequest request = SearchGoogleAdsStreamRequest.newBuilder()
            .setQuery( query )
            .setCustomerId( googleCID.toString() )
            .build();

    try ( final GoogleAdsServiceClient googleAdsServiceClient = googleAdsClient.getLatestVersion().createGoogleAdsServiceClient() ) {

        final List<GoogleAdsRow> rows = Lists.newArrayList();

        final ServerStream<SearchGoogleAdsStreamResponse> stream = googleAdsServiceClient.searchStreamCallable().call( request );

        for( final SearchGoogleAdsStreamResponse response : stream ) {
            rows.addAll( response.getResultsList() );
        }

        return rows;
    }
}
```

Thanks
Pete

**Comment by nwbirnie** [comment]
So the comment from Igor on the [GAX bug](https://github.com/googleapis/gax-java/issues/1132#issuecomment-648210895) is very helpful. He points out that by running in this paradigm, we're effectively creating a new gRPC connection every time a service client is requested. This is bad for a number of reasons, but perhaps most importantly because if you create enough connections in parallel, it will be detected as a DOS attack and the packets will be dropped. This would explain why I didn't see any DEADLINE_EXCEEDED errors in the ads API logs -they could be dropped before getting to us.

A gRPC connection can handle 100 parallel requests. If you need more requests, you should create a new client. In your case, this translates to calling `googleAdsClient.getLatestVersion().createGoogleAdsServiceClient()`. Creating multiple GoogleAdsClients should be fine, it is creating the service clients which will open a new gRPC connection.

**Comment by PeterLavetsky** [comment]
Nick,

Couple points of confusion here.

If we're to reuse the GoogleAdsServiceClient instances, how are to use the try-with-resources paradigm on googleAdsClient.getLatestVersion().createGoogleAdsServiceClient()?

If we don't have to use try-with-resources when creating the GoogleAdsServiceClient instances, is there a suggested TTL we should monitor on the cached GoogleAdsServiceClient instance? 

Also, since the AccessToken is created on the GoogleAdsClient itself, and we're effectively disjoining the GoogleAdsClient and the GoogleAdsServiceClient instances by caching the GoogleAdsServiceClient instance, isn't there the possibility of us running into an OAuth issue if we run over the AccessToken expiry? I don't believe I have access to the AccessToken value on the GoogleAdsClient object so if I wanted to use that as part of my cache key I would be out of luck. 

Thanks 
Pete

**Comment by nwbirnie** [comment]
> Couple points of confusion here.
Apologies.

> If we're to reuse the GoogleAdsServiceClient instances, how are to use the try-with-resources paradigm on googleAdsClient.getLatestVersion().createGoogleAdsServiceClient()?

No need to use try-with-resources. Just make sure you call `GoogleAdsServiceClient.close()` when you're done with the client.

> If we don't have to use try-with-resources when creating the GoogleAdsServiceClient instances, is there a suggested TTL we should monitor on the cached GoogleAdsServiceClient instance?

The client should be good for the life of the process.

> Also, since the AccessToken is created on the GoogleAdsClient itself, and we're effectively disjoining the GoogleAdsClient and the GoogleAdsServiceClient instances by caching the GoogleAdsServiceClient instance, isn't there the possibility of us running into an OAuth issue if we run over the AccessToken expiry? I don't believe I have access to the AccessToken value on the GoogleAdsClient object so if I wanted to use that as part of my cache key I would be out of luck.

It looks like you're using a refresh token. This will automatically regenerate an access token once the grant expires (every 60 minutes). gRPC will call `Credentials.getRequestMetadata()` which will request a new access token when the old one expires.

```
    final Credentials googleCredentials = UserCredentials.newBuilder()
            .setClientId( apiCredentials.getClientId() )
            .setClientSecret( apiCredentials.getClientSecret() )
            .setRefreshToken( apiCredentials.getRefreshToken() )
            .build();
```

**Comment by PeterLavetsky** [comment]
OK cool ... and just to clarify the following:

> No need to use try-with-resources. Just make sure you call `GoogleAdsServiceClient.close()` when you're done with the client.
> 
> The client should be good for the life of the process.

... that's essentially a green light to reuse the GoogleAdsServiceClient instances for very long times like days / weeks? 

We don't enter situations where we need more than 100 concurrent gRPC requests, so essentially 1 GoogleAdsServiceClient instance to 1 CID would be our use case.

And lastly, what state do we enter if we have a bad shutdown or some other circumstance that doesn't allow us to GoogleAdsServiceClient.close()? On app restart and new googleAdsClient.getLatestVersion().createGoogleAdsServiceClient() instantiation we'd be good to go?

Thanks
Pete

**Comment by PeterLavetsky** [comment]
> So you have a separate credential for each customer ID? Then you effectively need `O(num CIDs) clients` since the credential is bound to the channel. In the example you gave earlier you'd save 3x client creation, is that going to be enough to meaningfully reduce the number of clients being created?
> 

We do not have separate credentials for each customer ID, but we do have many credentials. 

I intend to cache the serviceClient using the following key:

```
final String key = keyJoiner.join(
            googleAdsClient.getLoginCustomerId(),
            googleAdsClient.getDeveloperToken(),
            googleAdsClient.getCredentials().toString()
        );
```

The toString on the UserCredentials object includes the following details:

```
@Override
  public String toString() {
    return MoreObjects.toStringHelper(this)
        .add("requestMetadata", getRequestMetadataInternal())
        .add("temporaryAccess", getAccessToken())
        .add("clientId", clientId)
        .add("refreshToken", refreshToken)
        .add("tokenServerUri", tokenServerUri)
        .add("transportFactoryClassName", transportFactoryClassName)
        .toString();
  }
```

**Comment by nwbirnie** [comment]
Ok, so that should bring the scale of the problem down. We should probably keep thinking about how to best handle the "worst case" scenario, but I'm guessing that if you have a relatively small number of credentials compared to the number of requests, this should bring your QPS back into the safe zone.

Worth mentioning that Igor points out that we can [override the credentials on a per call basis](https://github.com/googleapis/gax-java/issues/1132#issuecomment-648944663). This should mean we can at least mitigate this entirely on the client side.

**Comment by PeterLavetsky** [comment]
Cool. I will start in on this strategy.

A couple of out loud thoughts:

We received a DeadlineExceeded exception whereas it looks like it may have been the result of a QPS infraction. Is there client library work that could be done to make the true cause clearer?

We saw the same method calls ( search CampaignCriterion, search AdGroupCriterion ) as the origin points for every instance of this exception. The same list of search requests were put into the futures jobs in the same order each night, so perhaps when it got to those method calls we just happened to be at the QPS tipping point each time, but that seems a bit too tidy of an explanation.  

In conjunction with that, we were making createGoogleAdsServiceClient() calls immediately before and immediately after the futures jobs for search CC and search AGC were joined and they returned fine. Wouldn't it be likely those would trigger QPS as well? Are there different limits for different resources?

Speaking of limits, this is interesting:

```
https://developers.google.com/google-ads/api/docs/best-practices/quotas

By default gRPC has a maximum message size of 4 MB. It's possible to exceed this limit; for example, a search request that includes a very high number of fields may generate a response that exceeds 4 MB in size

Requests that violate this limitation will not generate a GoogleAdsError. They will generate an error at the gRPC error with a 429 Resource Exhausted error. 
```

"a very high number of fields" is definitely what I alluded to earlier with the fields / resources we request for the CC and AGC searches.

And finally, if it was a QPS issue, are you able to see that infraction on your end in the logs to put any other theories to bed? 

Thanks for your persistence on this Nick.

Pete

**Comment by nwbirnie** [comment]
Forgot to mention earlier... I think you want to tweak your cache key to be related to the refresh token, rather than the whoe credential. 

> ```
> @Override
>   public String toString() {
>     return MoreObjects.toStringHelper(this)

These fields will both contain the access token, which means that the cache will be invalidated every hour.:

>         .add("requestMetadata", getRequestMetadataInternal())
>         .add("temporaryAccess", getAccessToken())

These are fine, I would suggest considering avoiding converting the refresh token back to a string from a security point of view, e.g. what happens if this ends up in compromised log file? How about a hash of clientId + refreshToken instead?

>         .add("clientId", clientId)
>         .add("refreshToken", refreshToken)
>         .add("tokenServerUri", tokenServerUri)
>         .add("transportFactoryClassName", transportFactoryClassName)
>         .toString();
>   }
> ```

**Comment by nwbirnie** [comment]
> Cool. I will start in on this strategy.
> 
> A couple of out loud thoughts:
> 
> We received a DeadlineExceeded exception whereas it looks like it may have been the result of a QPS infraction. Is there client library work that could be done to make the true cause clearer?

So quota related errors are handled by the ads API, and will come back with ResourceExhausted.

> > We saw the same method calls ( search CampaignCriterion, search AdGroupCriterion ) as the origin points for every instance of this exception. The same list of search requests were put into the futures jobs in the same order each night, so perhaps when it got to those method calls we just happened to be at the QPS tipping point each time, but that seems a bit too tidy of an explanation.

> > In conjunction with that, we were making createGoogleAdsServiceClient() calls immediately before and immediately after the futures jobs for search CC and search AGC were joined and they returned fine. Wouldn't it be likely those would trigger QPS as well? Are there different limits for different resources?

Hmm, it's certainly odd. Although these requests are more likely to run slowly, hence there could be more open TCP connections. There's more logs that we can pull from gRPC if the issue persists (see thread on GAX re. opencensus).


> > Speaking of limits, this is interesting:
> 
> ```
> https://developers.google.com/google-ads/api/docs/best-practices/quotas
> 
> By default gRPC has a maximum message size of 4 MB. It's possible to exceed this limit; for example, a search request that includes a very high number of fields may generate a response that exceeds 4 MB in size
> 
> Requests that violate this limitation will not generate a GoogleAdsError. They will generate an error at the gRPC error with a 429 Resource Exhausted error. 
> ```
> 
> "a very high number of fields" is definitely what I alluded to earlier with the fields / resources we request for the CC and AGC searches.

We [override](https://github.com/googleads/google-ads-java/blob/d49f19067392b8d933257afeba319609b1784aa7/google-ads/src/main/java/com/google/ads/googleads/lib/GoogleAdsClient.java#L82-L87) this to 64MB already.

> > And finally, if it was a QPS issue, are you able to see that infraction on your end in the logs to put any other theories to bed?

Sorry, not a QPS issue per se. It's a too many TCP connections issue. There's no sign of QPS limits for your developer token on our side over the last 3 days.

**Comment by PeterLavetsky** [comment]
> Forgot to mention earlier... I think you want to tweak your cache key to be related to the refresh token, rather than the whoe credential.
> 
> These are fine, I would suggest considering avoiding converting the refresh token back to a string from a security point of view, e.g. what happens if this ends up in compromised log file? How about a hash of clientId + refreshToken instead?

Noted and implemented.

With no cache implementation deployed we had a 0.0% DeadlineExceeded error rate last night so ¯\_(ツ)_/¯

I will be rolling out the GoogleAdsServiceClient caching soon. Would you recommend we implement the same strategy for all BackgroundResources? ie. CampaignServiceClient for mutates etc.

Thanks
Pete

**Comment by nwbirnie** [comment]
Yes, ideally you would create the gRPC client at the start of the process and retain it for the duration. Also you can use GoogleAdsService to send mutates for the vast majority of operations (using only one service client).

**Comment by PeterLavetsky** [comment]
Implemented cache on the GoogleAdsServiceClient and have not seen DeadlineExceeded issues in days. 

Closing issue.
