### ISSUE TITLE
createGoogleAdsServiceClient() not working

### ISSUE THREAD

**Issue by amberxie88** [googleads/google-ads-java#303]
Hi,

I'm facing a bug when running this line of code, and I am not sure why:

GoogleAdsServiceClient googleAdsServiceClient = googleAdsClient.getLatestVersion().createGoogleAdsServiceClient();

I have taken the client library code and I am trying to reconfigure it in a Java servlet (still using Maven). The code compiles, but when it gives me an error with that line of code. The errors are as such:

(1) The first time I run, I get this error:
CAUSED BY:	java.lang.reflect.UndeclaredThrowableException
CAUSED BY:	java.lang.reflect.InvocationTargetException
CAUSED BY:	java.lang.NoSuchMethodError: 'com.google.protobuf.Parser com.google.protobuf.MessageLite.getParserForType()'

(2) When I reload the page, I get this error:
CAUSED BY:	java.lang.reflect.UndeclaredThrowableException
CAUSED BY:	java.lang.reflect.InvocationTargetException
CAUSED BY:	java.lang.NoClassDefFoundError: Could not initialize class com.google.ads.googleads.v3.services.stub.GrpcGoogleAdsServiceStub

When running this code (taken from GetCampaigns.java) in the client library, it works, so I suspect it has to do with some dependency or something with the pom.xml file. I've experimented with copying over different things in the google-ads-java and google-ads-examples pom.xml files, but none have worked.

Any help would be appreciated. Thanks!

**Comment by nwbirnie** [comment]
It looks like you have a conflicting version of protobuf on the classpath, most likely pulled in from another dependency in your tree. You can verify this is the case by running `mvn dependency:tree -Dverbose -Dincludes=protobuf-java`, the one under google-ads will most likely be marked as overridden by a conflict. Try adding an explicit dependency on `com.google.protobuf:protobuf-java:3.10.0`. This should restore the version required by google-ads.
