### ISSUE TITLE
GoogleAdsRow to JSON

### ISSUE THREAD

**Issue by amberxie88** [googleads/google-ads-java#304]
Is there an easy way to parse GoogleAdsRow into JSON? In addition, how does one access the field_mask in the SearchGoogleAdsStreamResponse?

**Comment by nwbirnie** [comment]
**Json:** Add a dependency on `com.google.protobuf:protobuf-java-util:3.10.0` and you can convert any protobuf message to JSON by doing `JsonFormat.printer().print(message)`

**FIeld mask:** The field mask is available directly from the [response object](https://github.com/googleads/google-ads-java/blob/2515ad3d48084a1e73c148e4e16bc5c329554436/google-ads/src/main/java/com/google/ads/googleads/v3/services/SearchGoogleAdsStreamResponse.java#L988-L994). So for example:

```
      ServerStream<SearchGoogleAdsStreamResponse> stream =
          googleAdsServiceClient.searchStreamCallable().call(request);

      for (SearchGoogleAdsStreamResponse response : stream) {
        response.getFieldMask();
      }
```

**Comment by amberxie88** [comment]
Wonderful! Thanks so much for the help.
