### ISSUE TITLE
V4 Client Library?

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#306]
Good morning all,

Is there an anticipated date for release of the Java Client Library supporting v4 of the API?

Usually we see the client library deployed about a week after the API announcement but I haven't seen any messaging around ramping up for the release of the client library to the googleads/google-ads-java list.

We've been invited to the Optiscore API Pilot and wanted to start digging in.

Thanks
Pete

**Comment by nwbirnie** [comment]
Hey, apologies for the delay. It should be released later today.

**Comment by nwbirnie** [comment]
We're also targeting the week following the API release for client library releases. Generally the API release is on a Wednesday, so client libs are due for Friday. Usually I would intend to fast-follow the API release, but on this occasion we had a hold up in our QA process, leading to it landing a bit later than usual.

**Comment by PeterLavetsky** [comment]
Sweet, thanks!
