### ISSUE TITLE
Optimization Recommendation Uplift Score?

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#309]
Hi All,

I've already asked this question in the API forum but it's clear they either don't know the answer or they don't know how to answer : https://groups.google.com/forum/#!topic/adwords-api/xe1gQYeYWYU

I'll quote here since it's pretty cut + dry : 

Articles about optimization recommendations ( https://support.google.com/google-ads/answer/9061546?hl=en ) reference a "score uplift" being associated with each recommendation.

Is this uplift score currently available through the API? We're on V4 FWIW.

I see the RecommendationImpact object ( https://developers.google.com/google-ads/api/reference/rpc/v4/Recommendation.RecommendationImpact ) but that just looked to be something you would delta yourself, and not result in an actual uplift score.

Thanks
Pete

**Comment by nwbirnie** [comment]
Hey Pete,

Thanks for reaching out. It looks to me like the optiscore uplift metric is only available in the UI, not the API. I've reached out to the support folks to suggest that they should file a feature request for this. Let's continue our discussion on the forum.

Best wishes,
Nick
