### ISSUE TITLE
Easier Way To Unset / Clear Values

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#314]
Hi All,

We're in a position where we need to Unset / Clear some values on a Campaign, tracking_url_template and final_url_suffix specifically.

Currently the Campaigns have values for those attributes set and we want to null them out.

Referencing here : https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#field-masks-in-update-operations it talks about adding those paths to the FieldMask, but not setting any value.

We make extensive use in our code base of the FieldMasks.allSetFieldsOf( campaign ) helper

We really would rather not have to manually keep track of set attributes and manually curate the FieldMask paths, and would rather instead rely on the FieldMasks utility class

Here is what I attempted to do, which does not work, but in my opinion very much should:

```
googleCampaignBuilder.setTrackingUrlTemplate( StringValue.newBuilder() );
...
campaign = googleCampaignBuilder.build()
...
                operationBuilder
                    .setUpdate( campaign )
                    .setUpdateMask(FieldMasks.allSetFieldsOf( campaign ) );
```

This results in a request / response of:

```
operations {
  update {
    resource_name: "customers/ABC/campaigns/XYZ"
    tracking_url_template {
    }

  update_mask {
    paths: "resource_name"
    paths: "tracking_url_template"

partial_failure_error {
  code: 3
  message: "Multiple errors in \342\200\230details\342\200\231. First error: The field\'s value is invalid., at operations[0].update.tracking_url_template"


```

To me that code explicitly says I'm intending to set the tracking_url_template and I'm intending that value to be null

Other attempts like using StringValue.of( "" ) or setTrackingUrlTemplate( null ) both fail

We thought using googleCampaignBuilder.clearTrackingUrlTemplate() might work since the method is described as:

```
    /**
     * <pre>
     * The URL template for constructing a tracking URL.
     * </pre>
     *
     * <code>.google.protobuf.StringValue tracking_url_template = 11;</code>
     */
    public Builder clearTrackingUrlTemplate() {
```

But that doesn't send over the FieldMask for tracking_url_template

Is there some other convenience way for clearing out a value? What's the best practice here, other than manually massaging the FieldMask paths?

Thanks
Pete

**Comment by jradcliff** [comment]
Hi Pete,

In your use case, do you have the object with existing values? If so, you could use the [`compare` method of the `FieldMasks` utility](https://github.com/googleads/google-ads-java/blob/master/google-ads/src/main/java/com/google/ads/googleads/lib/utils/FieldMasks.java#L47) as described in the second section of our [Field Masks guide](https://developers.google.com/google-ads/api/docs/client-libs/java/field-masks). That method will detect which attributes have changed between the original and modified object and return the appropriate `FieldMask`.

Thanks,
Josh

**Comment by PeterLavetsky** [comment]
Josh,

In most cases we do have access to the object with existing values, however the compare method doesn't really get us any farther down the road. 

For the time being we're manually massaging the FieldMask when we want to clear out values.

We really would like to see something like

```
googleCampaignBuilder.setTrackingUrlTemplate( StringValue.newBuilder() );
```

be valid in the future. Or some convenience method like builder.nullXXX.

Right now the builder.clearXXX methods are of no value to us since we're typically building up from an empty builder. I guess the clear methods are intended to be used when you have a fully populated object and don't want to mutate some attributes?

It's intended use case / value is a bit of a mystery to us.

Thanks
Pete

**Comment by jradcliff** [comment]
Hi Pete,

The intended approach for `compare` is demonstrated in [this line of the ApproveMerchantCenterLink example](https://github.com/googleads/google-ads-java/blob/50ff69456fa3434703166cd7d9f041a3cfbb5de8/google-ads-examples/src/main/java/com/google/ads/googleads/examples/accountmanagement/ApproveMerchantCenterLink.java#L156). The key step is that you call `toBuilder()` on the _existing instance_ instead of calling `newBuilder()` on the _class_. This will give you a builder whose values are initialized to the existing instance's values instead of an "empty" builder.

If you constructed `googleCampaignBuilder` in your example using this approach, then you could call `googleCampaignBuilder.clearTrackingUrlTemplate()` to clear the value for that field on your builder. Then, when you call `FieldMasks.compare(existingCampaign, googleCampaignBuilder.build())`, the `compare` method should detect the change in the tracking template and return that field in the mask. This is where the `clearX()` methods become useful.

Does that help solve the mystery, and would it work for your use case?

Thanks,
Josh

**Comment by PeterLavetsky** [comment]
Hi Josh,

I understand the use cases that you present.

What it comes down to is we build up rather than tear down our objects. For the attributes of objects that we care about we have them persisted in a database. ie. Campaign id, name, final_url_suffix ... when a user manages a Campaign in our system and makes a change, we build up a Campaign object via all the attributes we have persisted:

```
Campaign googleCampaign = Campaign.newBuilder()
    .setId( id )
    .setName( name )
    .setFinalUrlSuffix( finalUrlSuffix )
    .build();
```

We then use the FieldMasks utility and do the mutate and in 99% of cases everything is perfect and we're fine. 

When a user manages a Campaign and sets one of those attributes like final_url_suffix to null, we have to do the massaging of FieldMask because null is not a valid value to use for any of those set methods.

What you present boils down to something along the lines of: ( and, as always, correct me if these assumptions are egregiously out of whack )

```
User updates a Campaign in our system
Make an Ads API call to get the instance of that Campaign
Campaign.Builder existingCampaign = liveCampaign.toBuilder()
Campaign.Builder toUpdateCampaign = liveCampaign.toBuilder()

Iterate over all the attributes of the Campaign the user had the ability to update in our UI
    If isNull( attribute )
       toUpdateCampaign.clearAttribute
    else
      toUpdateCampaign.setAttribute( attribute )

FieldMask.compare
Mutate 
```

Having to check if the value is null before determining which method to call ( clear or set ) seems quite clumsy to me, and since the library was designed this way I guess I'm surprised that most developers would be pulling live instances via the Ads API first before making any mutate call. 

A straight forward approach seems that any set method that gets called on a builder object would immediately add that path to the FieldMask list ( maybe onChanged does that, I haven't gone down that rabbit hole )

If the developer called builder.setXYZ( null ) then so be it; they expressed a desire to set this attribute and the value of this attribute happened to be null.

Pete

**Comment by nwbirnie** [comment]
We are planning some changes to the API surface which I think should resolve this shortly. Let's revisit this after the v5 release.

**Comment by nwbirnie** [comment]
Hey, I think that the move to optional fields should have resolved this. Setting an optional field to it's default value will now trigger `FieldMaskUtil.allSetFields(msg)`.

**Comment by PeterLavetsky** [comment]
@nwbirnie can you expand a bit on setting an optional field to its default value?

We're still not able to clear out an attribute like finalUrlSuffix ( which is a String ) when we're constructing from a newBuilder() without manually adding final_url_suffix to the update_mask

calling setFinalUrlSuffix( null ) results in an NPE:

```
    public Builder setFinalUrlSuffix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
```

calling setFinalUrlSuffix( "" ) results in:

```
partial_failure_error {
  code: 3
  message: "The field\'s value is invalid., at operations[0].update.final_url_suffix"
  details {
    type_url: "type.googleapis.com/google.ads.googleads.v6.errors.GoogleAdsFailure"
    value: "\nX\n\003\350\003\004\022\035The field\'s value is invalid.\032\002*\000\".\022\016\n\noperations\030\000\022\b\n\006update\022\022\n\020final_url_suffix"
  }
}
```

Calling something like this:

```
googleCampaignBuilder.setFinalUrlSuffix("foo");
googleCampaignBuilder.clearFinalUrlSuffix();
```

results in FieldMasks.allSetFieldsOf not adding final_url_suffix to the update_mask

We're on 10.0.0 of the library FWIW.

Without going the compare route that @jradcliff mentions, and without manually adding final_url_suffix to the update_mask, is it possible to clear out an existing value?

Thanks
Pete

**Comment by nwbirnie** [comment]
Unfortunately this didn't work as I was hoping. There really isn't an alternatively to manually adding the field that you want to clear.

**Comment by PeterLavetsky** [comment]
@nwbirnie Can we reopen the feature request then?

**Comment by nwbirnie** [comment]
I'm not sure that we'll add this feature as described. We can't address this in the client library directly since the data classes are generated by protocol buffers. So next port of call would be to consider adding this to protobuf. I'm happy to ask them, but I doubt that they'll agree to take this on... I'm thinking that the use-case here is quite narrow, and moreover that there is a fairly simple workaround (just add the fields to clear manually). Does this substantially increase the complexity of your code? Do you have a sample of the workaround I could take a look at?

**Comment by PeterLavetsky** [comment]
Hi Nick,

In general we have a single point in the code where we mutate each resource, so adding manual checks is relatively pain free.

```
final FieldMask.Builder fieldMaskBuilder = FieldMasks.allSetFieldsOf( campaign ).toBuilder();

if( !fieldMaskBuilder.getPathsList().contains( "tracking_url_template" ) ) {
    fieldMaskBuilder.addPaths( "tracking_url_template" );
}

if( !fieldMaskBuilder.getPathsList().contains( "final_url_suffix" ) ) {
    fieldMaskBuilder.addPaths( "final_url_suffix" );
}

operationBuilder
  .setUpdate( campaign )
  .setUpdateMask( fieldMaskBuilder.build() );
```

We've had this in place for a while and it works so we're currently in an OK spot, at least for Campaigns.

Referencing the path as string literals is also not an envious position as obviously those could change in future API versions. If there are public static strings in the client library to reference the field path values I'd appreciate finding out about those.

As far as this issue being narrowly scoped to our implementation, you have all the data regarding how your customers interact with the API so I have no rebuttal for that. 

If other implementations clear the tracking_url_template for a campaign by first making a real time API call to Google to get the full instance before calling clearTrackingUrlTemplate() and using FieldMaks.compare() then I find that hugely inefficient. 

If the tracking_url_template needs to be cleared out on 2,000,000 AdGroupCriterion are other implementations pulling down all those objects first, in real time, before a clearTrackingUrlTemplate() and then compare() and then mutate?

Is an alternative solution to my use-case to construct a dummy Campaign first and then use compare()?

Like:

```
final Campaign dummyCampaign = Campaign.newBuilder()
                        .setTrackingUrlTemplate( "foo" )
                        .setFinalUrlSuffix( "bar" )
                        .build();
                
final FieldMask fieldMask = FieldMasks.compare( dummyCampaign, modifiedCampaign );
```

Thanks
Pete

**Comment by nwbirnie** [comment]
> In general we have a single point in the code where we mutate each resource, so adding manual checks is relatively pain free.
> 
> We've had this in place for a while and it works so we're currently in an OK spot, at least for Campaigns.
> 
> Referencing the path as string literals is also not an envious position as obviously those could change in future API versions. If there are public static strings in the client library to reference the field path values I'd appreciate finding out about those.

What about structuring the call differently - so you pass both the Campaign object, together with another Campaign that contains the fields to clear? I'm thinking something like this would work:

```
public void mutateCampaign(Campaign toSet, Campaign toClear) {
  FieldMask maskToSet = FieldMasks.allSetFieldsOf(toSet);
  FieldMask maskToClear = FieldMasks.allSetFieldsOf(toClear);
  googleAdsClient.mutate(toSet, FieldMasks.union(maskToSet, maskToClear));
}
```

This is quite similar to the option you suggest below.

> If other implementations clear the tracking_url_template for a campaign by first making a real time API call to Google to get the full instance before calling clearTrackingUrlTemplate() and using FieldMaks.compare() then I find that hugely inefficient.

I agree that this would be suboptimal. The common case is that folks have a local copy of the ads entity data (with some background job that syncs this periodically). The thing that makes this narrow is that it's only an issue when clearing fields by setting them to their default value. That's not to say that we shouldn't look at options, just that we should be mindful of how likely they are to be feasible.

> If the tracking_url_template needs to be cleared out on 2,000,000 AdGroupCriterion are other implementations pulling down all those objects first, in real time, before a clearTrackingUrlTemplate() and then compare() and then mutate?

Assuming that you have a local copy of the ads entities, it should be possible to avoid the round trip. However it requires a bit of knowledge about what was intended for the update. For instance, if this is an interactive UI, then the user would likely have indicated that a field should be cleared and that can be used to construct the update mask. Is that what you're doing? Executing an update based on a UI request?

> Is an alternative solution to my use-case to construct a dummy Campaign first and then use compare()?
> 
> Like:
> 
> ```
> final Campaign dummyCampaign = Campaign.newBuilder()
>                         .setTrackingUrlTemplate( "foo" )
>                         .setFinalUrlSuffix( "bar" )
>                         .build();
>                 
> final FieldMask fieldMask = FieldMasks.compare( dummyCampaign, modifiedCampaign );
> ```

This is generally correct, I have a few suggestions...

- This assumes that `trackingUrlTemplate` and `finalUrlSuffix` are always to be updated. But `modifiedCampaign` might not specify those fields because either they are not to be mutated, or they are to be cleared. Based on your code above where these paths are always added to the mask if not present I would think that you always mean to update these though.
- If you have any other fields that are supposed to be cleared in `modifiedCampaign` these would also need to be added to `dummyCampaign`.
- I think I'd prefer the interface suggested above, explicitly specifying the fields to clear.

**Comment by PeterLavetsky** [comment]
Thanks Nick. I think we're both pointing in the same direction.

We'll be able to work with the existing patterns, tho here are a couple notes / asks.

> The common case is that folks have a local copy of the ads entity data (with some background job that syncs this periodically). 

Yep. This is our implementation.

> The thing that makes this narrow is that it's only an issue when clearing fields by setting them to their default value. That's not to say that we shouldn't look at options, just that we should be mindful of how likely they are to be feasible.

I can buy this, tho a DIRTY_BIT String would be nice to have to set back to default value ( rather than set( null ) ). We originally thought clearTrackingUrlTemplate() did this.

>For instance, if this is an interactive UI, then the user would likely have indicated that a field should be cleared and that can be used to construct the update mask. Is that what you're doing? Executing an update based on a UI request?

Yes in most instances we are executing an update from the UI that has modified the persisted local copy. Our implementation does not indicate which fields changed in the UI request however. The UI passes the whole entity to the backend and says here's the current state. Not field by field. There are also times when we manually update the database directly but that's really neither here nor there.

> * This assumes that `trackingUrlTemplate` and `finalUrlSuffix` are always to be updated. But `modifiedCampaign` might not specify those fields because either they are not to be mutated, or they are to be cleared. Based on your code above where these paths are always added to the mask if not present I would think that you always mean to update these though.

Yes. The chain of responsibility in our mutate call includes a transform() operation from our full local copy to a com.google.ads.googleads.v6.resources.Campaign. We're sending name, tracking_url_template ... everything, whether it was actually modified or not.
