### ISSUE TITLE
Response with errors from ConversionAdjustmentUploadServiceClient isn't handled correctly by ErrorUtils

### ISSUE THREAD

**Issue by nachman16** [googleads/google-ads-java#325]
I'm trying to get errors from a response to the ConversionAdjustmentUploadService using the following util:

ErrorUtils.getInstance().getGoogleAdsErrors(operationIndex, partialFailureError);

There seems to be an issue with the path field name in the response where when that method is called to get errors, none are returned. I've attached a request and response
[response.txt](https://github.com/googleads/google-ads-java/files/5071136/response.txt)
[request.txt](https://github.com/googleads/google-ads-java/files/5071137/request.txt)

The problem seems to be that getGoogleAdsErrors calls another method called getGoogleAdsErrors here:

result.addAll(getGoogleAdsErrors(operationIndex, failure));

And that method below looks for path field names the need to match the following condition:

if (("operations".equals(path.getFieldName())
              || "mutate_operations".equals(path.getFieldName()))

which aren't in the response error -- I believe the path field name in the response in the error is conversion_adjustments.

Here is the partial error passed to the original method:

code: 3
message: "A conversion for the supplied conversion action and conversion identifier pair could not be found., at conversion_adjustments[0]"
details {
  type_url: "type.googleapis.com/google.ads.googleads.v3.errors.GoogleAdsFailure"
  value: "\n\207\001\n\003\230\a\005\022bA conversion for the supplied conversion action and conversion identifier pair could not be found.\"\034\022\032\n\026conversion_adjustments\022\000"
}

The operation index is 0.

**Comment by nwbirnie** [comment]
This looks like a similar issue to #230. It appears that `ConversionAdjustmentUploadService` is assuming that the index into  `Status.getDetailsList()` is used to indicate the location of the failed response; in fact there should be an operations element by convention. I've filed a bug internally for this, will update the thread here with progress.

In the meantime, you can work around this by doing:

`response.getPartialFailureError().getDetails(failedOperationIndex).unpack(GoogleAdsFailure.class)`

b/164324199

**Comment by nwbirnie** [comment]
Response from conversions folks:

>There's no bug and this is just a special corner case for index = 0. The user just has to call getValue() to get index 0. For other cases, we already correctly return the index.
