### ISSUE TITLE
Error in setting up Property 

### ISSUE THREAD

**Issue by sanket-tandalekar** [googleads/google-ads-java#329]
**Which version of the client library are you using?**
- We are using the latest client library v4 

**Which version of Java are you using?**
- Using the Java 1.8 version.

**Which operating system (Linux, Windows, ...) and version?**
- Windows

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
- We have just hardcoded the credentials and didn't make any updates in the script and then execute the script

**Expected result**
- The property file should have got set and the script continues to execute further.

**Actual result**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.

- We are getting an error while setting up the property file in the script. We are getting "NULLPOINTEREXCEPTION" on setting up the property file. We are working on the v4 version of Google Ads API and there are library files missing in the GoogleAdsClient.java file which seems to be important for the script execution. 
 
**Anything else we should know about your project / environment**
- Local System
![missing-file-error](https://user-images.githubusercontent.com/70307468/91383859-cd6e4000-e84a-11ea-8f15-bdad8ea49e26.jpg)
![null-auth-error](https://user-images.githubusercontent.com/70307468/91383862-cf380380-e84a-11ea-9a65-4f2af74ed356.jpg)

**Comment by jradcliff** [comment]
Hi,

The library has several annotation processors, so if you're using an IDE, please make sure you have enabled annotation processing for the project.

For example, if using IntelliJ IDEA, you'll want to:

1. Select **File -> Settings**.
1. Go to **Build, Execution, Deployment -> Compiler -> Annotation processors**, select **google-ads**, and check **Enable annotation processing**.

That should fix the compilation issues with `GoogleAdsClient`.

Thanks,
Josh

**Comment by sanket-tandalekar** [comment]
> Hi,
> 
> The library has several annotation processors, so if you're using an IDE, please make sure you have enabled annotation processing for the project.
> 
> For example, if using IntelliJ IDEA, you'll want to:
> 
> 1. Select **File -> Settings**.
> 2. Go to **Build, Execution, Deployment -> Compiler -> Annotation processors**, select **google-ads**, and check **Enable annotation processing**.
> 
> That should fix the compilation issues with `GoogleAdsClient`.
> 
> Thanks,
> Josh

Hi Josh,

I'm using Eclipse IDE - Eclipse for Enterprise Java Developers Edition. I tried the Annotation setting you asked me to set but I did not see 'google-ads' as an option in properties setting. 

Also, I tried to set the Annotation settings but after building the error did not go away
![annotation-setting](https://user-images.githubusercontent.com/70307468/91632524-03ecbc00-e9ff-11ea-90ee-e9832c81822b.jpg)

Also, I enabled the Factory path but after applying the settings and building the application it goes back to disabled.
![factory-path-setting](https://user-images.githubusercontent.com/70307468/91632562-31d20080-e9ff-11ea-9f67-74e33c665156.jpg)

Please help me with this. Is there anything I'm maybe missing some steps that need to be set. I have JavaSE 1.8. 

Thanks,
Sanket

**Comment by jradcliff** [comment]
Hi Sanket,

I'll be perfectly honest: I'm not sure why Eclipse isn't picking up the annotation processor on the library. :disappointed: 

However, if your goal is to _use_ the library (as opposed to modify or contribute to it), a quick workaround would be to modify the  `<version>` of `google-ads` in [google-ads-examples/pom.xml](https://github.com/googleads/google-ads-java/blob/master/google-ads-examples/pom.xml#L54) to the _released_ version: `8.0.0`. With that change, you can just import the `google-ads-examples` project into Eclipse, and it shouldn't need to locally build the library.

Please let me know if that works for you.

Thanks,
Josh

**Comment by sanket-tandalekar** [comment]
Hi Josh,

So I have modified the POM file in the <version> of google-ads in google-ads-examples/pom.xml to the released version: 8.0.0 as suggested and the imported the google-ads-example project into Eclipse and it worked perfectly well. 
Now, I'm able to set the properties file and able to execute my script to request and capture the response.
Thank you soo much for the help and guidance. :)

Thanks,
Sanket

**Comment by jradcliff** [comment]
Hi Sanket,

Glad to hear the suggestion worked! I'll make a note of this so we cover this approach in our [library documentation](https://developers.google.com/google-ads/api/docs/client-libs/java). I'm sure there are plenty of others who will have a use case similar to yours, and we can save them some trouble & frustration.

Cheers,
Josh
