### ISSUE TITLE
Don't Lose Exception Details When Wrapped Into com.google.api.gax.rpc.InvalidArgumentException

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#332]
With DEBUG logging on for com.google.ads.googleads.lib.request.detail I can see the following request and response:

```
Request
-------
MethodName: google.ads.googleads.v4.services.GoogleAdsService/SearchStream
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=ABC, x-goog-api-client=gl-java/1.8.0_161 gapic/ gax/1.57.0 grpc/1.30.0}
Body: customer_id: "XYZ"
query: "select customer.id, campaign_budget.id, metrics.cost_micros, metrics.clicks, metrics.conversions, metrics.impressions, campaign_budget.period, campaign_budget.reference_count, campaign_budget.amount_micros, campaign_budget.name from campaign_budget where segments.date   DURING   THIS_MONTH "
```

```
Response
--------
Headers: Metadata(content-type=application/grpc,request-id=wKbcK0j7Cw3Kkp-CdTm8zQ,date=Sat, 05 Sep 2020 14:47:42 GMT,alt-svc=h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43")
Body: null
Failure message: errors {
  error_code {
    query_error: REQUESTED_METRICS_FOR_MANAGER
  }
  message: "Metrics cannot be requested for a manager account. To retrieve metrics, issue separate requests against each client account under the manager account."
}
```

However this gets wrapped into a thrown exception of com.google.api.gax.rpc.InvalidArgumentException and as far as I can tell there's no way to unpack this exception to get any valuable details ie.:

```
detailMessage : io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
```

The true error should be exposed in the thrown Exception so adequate handling may be done.

Thanks
Pete

Java Client Library : com.google.api-ads:google-ads:8.0.0

**Comment by nwbirnie** [comment]
Thanks for reporting. It looks like we're missing a few cases in `GrpcGoogleAdsExceptionFactory`. Rather than spend time hacking them into that pattern it seems like it would be better to update GAX (middleware) to allow us to customize the exception mapping. I'll file a PR with GAX shortly to address this and follow up with a change to the Java library to provide a custom mapping.

**Comment by nwbirnie** [comment]
Created googleapis/gax-java#1178 to expose an interface for hooking into the GAX ApiExceptionFactory code. This will allow us to override the exception returned in one place for all call types.

**Comment by nwbirnie** [comment]
And googleads/google-ads-java#336 has the ads API side of the GAX change.

**Comment by nwbirnie** [comment]
This is now fixed in master and will be in the next release.
