### ISSUE TITLE
getTotalResultsCount() always returns zero.

### ISSUE THREAD

**Issue by hkoosha** [googleads/google-ads-java#334]
**Which version of the client library are you using?**
8.0.0 and 9.0.0
Previously I used the version 4.x of the library and everything worked just fine. After upgrading to 8, the issue emerged.

**Which version of Java are you using?**
java version "1.8.0_241"

**Which operating system (Linux, Windows, ...) and version?**
Linux 5.4.60-2-MANJARO SMP PREEMPT x86_64 GNU/Linux

**Actions taken**
Using the library to fetch ads, the call to `getTotalResultsCount()` always returns 0 (while `pageResponse.getResultsList().size()` works as expected).

```java
UnaryCallable<SearchGoogleAdsRequest, SearchGoogleAdsResponse> callable = GoogleAdsClient
            .newBuilder()
            .fromPropertiesFile(credential...)
            .build()
            .getVersion4()
            .createGoogleAdsServiceClient()
            searchCallable();
SearchGoogleAdsRequest request = SearchGoogleAdsRequest
        .newBuilder()
        .setCustomerId(customerId...)
        .setPageSize(1_000)
        .build();
SearchGoogleAdsResponse pageResponse = callable.call(request, GrpcCallContext.createDefault());
assert pageResponse.getTotalResultsCount() > 0;
```

**Expected result**
`getTotalResultsCount()` should return the actual total results, not zero.

**Actual result**
`getTotalResultsCount()` always returns 0.

**Comment by nwbirnie** [comment]
A [request parameter](https://developers.google.com/google-ads/api/reference/rpc/v5/SearchGoogleAdsRequest) was added to the API in v3 which must be specified to return the total results count.

**Comment by nwbirnie** [comment]
Please set `SearchGoogleAdsRequest.setReturnTotalResultsCount(true)` in your request to retrieve the total results.
