### ISSUE TITLE
I just spent too much time(more than 40min) to build the project. Any way to getting faster to run a test?

### ISSUE THREAD

**Issue by beangou** [googleads/google-ads-java#346]
I just spent too much time(more than 40min) to build the project. Any way to getting faster to run a test?

**Comment by nwbirnie** [comment]
Hey, we are planning to improve the build times. Can I ask why you needed to build the project? We distribute release artifacts on Maven, so generally you shouldn't need to build the project.

**Comment by nwbirnie** [comment]
The gradle build files should provide a much faster build. The first time building will be slower, but thereafter it should be really fast. Please take a look and let us know if you have feedback.
