### ISSUE TITLE
How to enable logging in Java client library?

### ISSUE THREAD

**Issue by kimpoy05** [googleads/google-ads-java#35]
How to enable logging in this Java client library? It seems like it doesn't have a configuration for logging just like in AdWords API Java client lib. I want to get my request and response logs and it seems its not included in any of your guides.

looking forward for your immediate response.

Thanks
Kimpoy

**Comment by nwbirnie** [comment]
You've reported this on the bug tracker for the new Google Ads API (currently in beta, see docs [here](https://developers.google.com/google-ads/api/docs/start)). Logging for this library is configured differently to the AdWords API. 

If you're using Google Ads API we don't currently have a cohesive logging setup (stay tuned!) but you can enable logging for the gRPC trace by defining a logging.proprties file with the following:

  handlers=java.util.logging.ConsoleHandler
  io.grpc.netty.level=FINE
  java.util.logging.ConsoleHandler.level=FINE
  java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

and starting your application with -Djava.util.logging.config.file=logging.properties.

For AdWords API, please add these dependencies:

    <dependency>
      <groupId>log4j</groupId>
      <artifactId>log4j</artifactId>
      <version>1.2.16</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>1.7.7</version>
    </dependency>
  </dependencies>

Then copy the log4j configuration file from [here](https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/resources/log4j.properties) into your project under src/main/resources. This should start logging the SOAP request/responses to the console.

**Comment by nwbirnie** [comment]
This is now fixed in the latest version. Please update to 0.7.0 and review the [logging configuration](https://github.com/googleads/google-ads-java#requestresponse-logging) section of the docs.
