### ISSUE TITLE
Difficulty setting up retry settings with GoogleAdsClient

### ISSUE THREAD

**Issue by sean-abbott** [googleads/google-ads-java#359]
Kotlin 1.4.10, jvmTarget 11

Linux, Ubuntu 18.04

 We're migrating one of our reports from ruby to java (well, ok...kotlin).

In implementing this,  I ran into a server error, which in ruby we'd retry.

Then, as I tried to set up retries via the java client, I ran into some weird inconsistencies.

Originally, I had (abbreviate):

```
        val gClient = GoogleAdsClient
                .newBuilder()
                .setCredentials(creds)
                .setDeveloperToken(devToken)
                .setLoginCustomerId(CG_MCC_ID)
                .build()

       val totalInserts = gClient.latestVersion.createGoogleAdsServiceClient().use { gServClient ->
```

etc.

However, the client I get from `GoogleAdsClient.latestVersion.createGoogleAdsServiceClient` did not appear to have a way to modify the `GoogleAdsServiceSettings`

So I ended up doing

`GoogleAdsServiceClient.create(getDefaultRetrySettings(creds, headerProvider))`  (where I create a settings builder and set everything in the `getDefaultRetrysettings` function)

But in order to do the latter, I had to implement a custom `HeaderProvider` to set the developer token and the login customer id.

Did I miss something in one of those two versions?

I'd expect to either be able to mutate the retry settings in the former, or to be able to set developer token and login-customer-id in the latter.

Thanks!

sean

**Comment by nwbirnie** [comment]
Hey thanks for reporting. This is actually a known limitation of the GoogleAdsClient surface. We currently generate a default *Settings object for every client, though as you mention there is no way to override this while still using our client factory methods.

Can I ask which error code you're receiving and trying to retry? We may be able to add that to our list of retryable error codes so that it's retried by default. Did you also want to configure the exponential backoff params?

**Comment by sean-abbott** [comment]
We were also configuring the exponential backoff params.

The error code in question was just SERVER_ERROR (from memory, but you get
the idea), so it should've been retried but I don't believe it was.

It was transient, but the failure happened fast enough I really don't think
it went through retries.

We run a batch system, so we have retry settings that are probably much
longer than the defaults?

**Comment by nwbirnie** [comment]
Hmm, I don't know if we'd want to make that retryable for all API clients. 

So we are planning some work here to expose the service-level settings object in the client factory, however that's not going to be ready imminently.

I think if you want to use the built in retry behavior, the solution you posted is really the best thing for the time being (as ugly as it is).

I would not recommend this though, and would just instead implement a simple retrying exponential backoff.

@devchas our resident timeouts + retry expert in case there's anything you'd like to add.

**Comment by sean-abbott** [comment]
Thanks!

Incidentally, your github settings seem...weird? I can't comment or react
on this from github, but I can respond to the emails I'm getting.

**Comment by foobarbaz123321** [comment]
Test

**Comment by nwbirnie** [comment]
Can you share a screenshot of the reply box perhaps? Since you need to email it, please use imgur.com (or similar) thanks.

**Comment by sean-abbott** [comment]
https://imgur.com/a/21vKJvJ

The reaction wasn't working at  all earlier, now I can select a reaction
but it doesn't post.

**Comment by devchas** [comment]
As Nick mentioned, we have some things in the works to fix this long term. For now, agree which Nick that your best option is to implement exponential backoff.

**Comment by nwbirnie** [comment]
This is now fixed in the upstream library and will be available in the next release.

Usage is: `GrpcCallContext.createDefault().withRetrySettings(RetrySettings.newBuilder().build())`

In the meantime you can override the version of GAX to 1.63.0 which contains these changes.

```
    <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>gax</artifactId>
      <version>1.63.0</version>
    </dependency>
```

**Comment by nwbirnie** [comment]
@devchas Could you add a quick set of docs to [this page](https://developers.google.com/google-ads/api/docs/client-libs/java/advanced-usage) please?

**Comment by devchas** [comment]
Docs [added](https://developers.google.com/google-ads/api/docs/client-libs/java/advanced-usage#retry_settings).
