### ISSUE TITLE
Unable to authenticate GoogleAdsClient over Java 1.8

### ISSUE THREAD

**Issue by ahmadhashlamoun** [googleads/google-ads-java#360]
I'm trying to use Google Ads API, I already have my ads.properties file ready, and I added the following dependencies to my pom file:

` <dependency>
            <groupId>com.google.api-ads</groupId>
            <artifactId>google-ads</artifactId>
            <version>9.0.0</version>
        </dependency>`
       ` <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>27.0-jre</version>
        </dependency>`
       ` <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.8</version>
        </dependency>`

But when I try to run the code like this:
`File file = new File(this.getClass().getClassLoader().getResource("/ads.properties").getFile());`
`GoogleAdsClient googleAdsClient = GoogleAdsClient.newBuilder().fromPropertiesFile(file).build();`

I get the following error:
**_org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V_**

Is there a problem with the library? And how could I fix it?
Would this be a problem with my credentials?

**Comment by nwbirnie** [comment]
This is a common version conflict with the Guava dependency. Which version of the client library are you using? If it's 9.0.0 your version of Guava should be `28.2-android`

**Comment by ahmadhashlamoun** [comment]
@nwbirnie I tried `28.2-jre` but still same issue, I'm not using it for android tho, it's for our general APIs
Any clue?
What else versions I may use?

**Comment by nwbirnie** [comment]
Please use `28.2-android`. We use the android version because we explicitly want to support usage from android ([see details](https://github.com/google/guava#adding-guava-to-your-build)).

**Comment by ahmadhashlamoun** [comment]
@nwbirnie Still same error!
Here's my maven dependencies:

```
        <dependency>
            <groupId>com.google.oauth-client</groupId>
            <artifactId>google-oauth-client-servlet</artifactId>
            <version>1.19.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>servlet-api</artifactId>
                    <groupId>javax.servlet</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-oauth2</artifactId>
            <version>v2-rev83-1.19.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client-jackson</artifactId>
            <version>1.19.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.api-ads</groupId>
            <artifactId>google-ads</artifactId>
            <version>9.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>28.2-android</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.8</version>
        </dependency>
```

**Comment by ahmadhashlamoun** [comment]
If I want to use version 8, which Guava version would work?

**Comment by nwbirnie** [comment]
If you move the Guava dependency to the top of the list it should work.

```
  <dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>28.2-android</version>
    </dependency>
    <dependency>
      <groupId>com.google.oauth-client</groupId>
      <artifactId>google-oauth-client-servlet</artifactId>
      <version>1.19.0</version>
      <exclusions>
        <exclusion>
          <artifactId>servlet-api</artifactId>
          <groupId>javax.servlet</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-oauth2</artifactId>
      <version>v2-rev83-1.19.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.http-client</groupId>
      <artifactId>google-http-client-jackson</artifactId>
      <version>1.19.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.api-ads</groupId>
      <artifactId>google-ads</artifactId>
      <version>9.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpcore</artifactId>
      <version>4.4.8</version>
    </dependency>
  </dependencies>
```

Are you using Intellij by any chance? It appears that maven CLI doesn't require this reordering, but IntelliJ does for some reason...

If you want to see the required dependencies for a version, simply add a dependency on that version, then run `mvn dependency:tree -Dverbose` and look for the entries you're interested in under `google-ads`. In the case of `8.0.0` the Guava dependency is also `28.2-android`.

**Comment by ahmadhashlamoun** [comment]
@nwbirnie yes I'm using IntelliJ for this.
I tried putting the Guava dependency on top, and still the same issue :/

Here's a screenshot from our dependencies tree, please check if we're making a mistake here:\

![Screen Shot 2020-10-27 at 1 21 58 PM](https://user-images.githubusercontent.com/6437485/97294985-69bac000-1857-11eb-8bdc-fa6594f891f4.png)
![Screen Shot 2020-10-27 at 12 59 05 PM](https://user-images.githubusercontent.com/6437485/97293333-34ad6e00-1855-11eb-955d-4ce7a3d50294.png)
![Screen Shot 2020-10-27 at 12 59 30 PM](https://user-images.githubusercontent.com/6437485/97293327-324b1400-1855-11eb-915f-4e7d83cc1d2f.png)

Is this seems right? And why it's saying com.google.guava:guava:jar:28.2-android:compile - omitted for duplicate:
`
[INFO]+- com.google.api-ads:google-ads:jar:9.0.0:compile
[INFO] |  +- com.google.api:gax:jar:1.57.1:compile
[INFO] |  |  +- (com.google.guava:guava:jar:28.2-android:compile - omitted for duplicate)
[INFO] |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:compile - omitted for duplicate)
`

I just have it once in my dependencies file

**Comment by nwbirnie** [comment]
Can you create a repo with a minimal failing example please?

**Comment by ahmadhashlamoun** [comment]
@nwbirnie it's so hard doing so, esp the project is huge and not easy to do so, but I can provide a full image of dependencies tree if that would make it easier?

**Comment by ahmadhashlamoun** [comment]
![diagram](https://user-images.githubusercontent.com/6437485/97295857-899eb380-1858-11eb-8139-b9945c339d25.png)
@nwbirnie check above

**Comment by nwbirnie** [comment]
I only need the minimal dependencies required to produce an error case, similar to what you pasted earlier.

**Comment by nwbirnie** [comment]
To give you a starting point, here is the [pom.xml](https://gist.github.com/nwbirnie/9646277097fd5f5b04caa2393c93a34b) and [test case](https://gist.github.com/nwbirnie/aa504f06a194f386091e1a3da3214a29) I created earlier which fixes the dependency list you originally sent over.

**Comment by ahmadhashlamoun** [comment]
@nwbirnie you mean something like so?

`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>Mashvisor</groupId>
    <artifactId>Mashvisor</artifactId>
    <packaging>war</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>Mashvisor Maven Webapp</name>
    <url>http://maven.apache.org</url>
    <dependencies>
        <dependency>
            <groupId>org.jasypt</groupId>
            <artifactId>jasypt</artifactId>
            <version>1.9.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>28.2-android</version>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client</artifactId>
            <version>1.19.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.oauth-client</groupId>
            <artifactId>google-oauth-client</artifactId>
            <version>1.19.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.oauth-client</groupId>
            <artifactId>google-oauth-client-servlet</artifactId>
            <version>1.19.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>servlet-api</artifactId>
                    <groupId>javax.servlet</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-oauth2</artifactId>
            <version>v2-rev83-1.19.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client-jackson</artifactId>
            <version>1.19.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.api-ads</groupId>
            <artifactId>google-ads</artifactId>
            <version>9.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.8</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>debop-releases-bintray</id>
            <url>http://dl.bintray.com/debop/maven</url>
        </repository>
        <repository>
            <id>terracotta-releases</id>
            <url>http://www.terracotta.org/download/reflector/releases</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
        <finalName>v1</finalName>
        <plugins>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.3.6.v20151106</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
`

**Comment by nwbirnie** [comment]
This pom works correctly for me in IntelliJ. 

![Screenshot from 2020-10-27 11-42-09](https://user-images.githubusercontent.com/410275/97297381-ddee6700-1849-11eb-81ec-98573b5ba9fe.png)


On the command line I had to change packaging war -> pom, but it does [work](https://gist.github.com/nwbirnie/5c1eb340d73833adbce24a6c19294653) there too.

**Comment by nwbirnie** [comment]
Are you possibly running an old version of IntelliJ? Or is there something about your war deployment that might be causing the issue?

**Comment by ahmadhashlamoun** [comment]
@nwbirnie I'm using IntelliJ Idea 14.1.15

I'll try updating it now and see, and if it's about my war, I need some help therechecking if that the issue

**Comment by ahmadhashlamoun** [comment]
@nwbirnie I tried updating the IntelliJ for the most recent version, and still the same
is it possible to have quick call about this and finish it ASAP?

**Comment by nwbirnie** [comment]
Sure, I could do 3.30pm UK time if that works?

**Comment by ahmadhashlamoun** [comment]
@nwbirnie  I work in 2 different timezones, what about anything after 7:00 pm UK time? If it doesn't work with you, please let's do it tomorrow morning?

**Comment by nwbirnie** [comment]
How's 11am tomorrow?

**Comment by ahmadhashlamoun** [comment]
@nwbirnie Super! Sounds perfect! 
Can i get your email to send a calendar invite?

**Comment by nwbirnie** [comment]
Just sent you one :)

**Comment by nwbirnie** [comment]
As discssed on VC, this is now fixed. The culprit was
 ```
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-oauth2</artifactId>
            <version>v2-rev83-1.19.0</version>
        </dependency>
``` 
and updating to latest resolved this.

**Comment by ahmadhashlamoun** [comment]
Just solved it!
So the thing that the Guava dependency for 28.2 and Google Ads 9.0.0 has conflict with older versions of Oauth2 package,
It works fine if you update the OAuth 2 to the latest one **_v2-rev157-1.25._**:

`<dependency>
           <groupId>com.google.apis</groupId>
           <artifactId>google-api-services-oauth2</artifactId>
           <version>v2-rev157-1.25.0</version>
       </dependency>`
