### ISSUE TITLE
Got error when use FieldMasks.allSetFieldsOf() to setUpdateMask() of CampaignCriterionOperation ==> Generated message class "com.google.ads.googleads.v5.resources.CampaignCriterion" missing method "getCampaignCase"

### ISSUE THREAD

**Issue by tsungfuxie** [googleads/google-ads-java#362]
**Which version of the client library are you using?**
![image](https://user-images.githubusercontent.com/73671325/97676445-9ecf4880-1acb-11eb-9735-8a49206cff37.png)

**Which version of Java are you using?**
java version "11.0.8" 2020-07-14 LTS

**Which operating system (Linux, Windows, ...) and version?**
Linux CentOS 7 + 8 / Windows 7

**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
Either use the following apporach
![image](https://user-images.githubusercontent.com/73671325/97676934-61b78600-1acc-11eb-9158-80efdf59aeff.png)

or use these both got same error
![image](https://user-images.githubusercontent.com/73671325/97677232-eefada80-1acc-11eb-8f11-ff77e89e4951.png)

=============The overall code snippet================
![image](https://user-images.githubusercontent.com/73671325/97678155-56fdf080-1ace-11eb-8c6f-b5b92fc29e6a.png)

![image](https://user-images.githubusercontent.com/73671325/97678252-78f77300-1ace-11eb-8006-bdf927adcfad.png)

**Expected result**
We expect the api could mutate CampaignCriterion_DeviceBidModifier successfully.

**Actual result**
Got error message like below
![image](https://user-images.githubusercontent.com/73671325/97677640-85c79700-1acd-11eb-9504-bf0dd70e1e25.png)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by nwbirnie** [comment]
I tried to reproduce this but was unable. Could you take a look at my code and tell me if I'm missing something please?

https://gist.github.com/nwbirnie/7e8835c9527cc950622cba5e6a0be4d7

**Comment by tsungfuxie** [comment]
Hi nwbirnie,
 
 Thank you for providing the test code, and it is correct.
 Finally, I tested that the same error message still appears when using **_java 11.0.8_**, which is the java version I used at the beginning.
The code will break and errors occur in the yellow block, as shown in the figure below
![image](https://user-images.githubusercontent.com/73671325/97824823-fa7e1980-1cf7-11eb-8281-f4fd510e6084.png)


However, when using the **_java 1.8.0_**, everything is normal, and the results show that both methods can be modified normally.
![image](https://user-images.githubusercontent.com/73671325/97824611-6449f380-1cf7-11eb-946f-24c67289cfd9.png)
![image](https://user-images.githubusercontent.com/73671325/97824647-7f1c6800-1cf7-11eb-85b1-11668b40bd12.png)

Because the main difference between the two environments I tested is the java version, can you please help clarify the possible reasons, thanks a lot.

**Comment by nwbirnie** [comment]
I tested on both Open JDK 11 and Oracle JDK 11 and it appears to be working correctly.

Can you please:

1. Provide the full stack trace of the error (not just the summary message).
2. Enable [logging](https://developers.google.com/google-ads/api/docs/client-libs/java/logging) in the client library and provide the full request/response logs.

**Comment by tsungfuxie** [comment]
Hi Nick,

 Thanks for your advice, i had found the root cause.
 **The protobuf-java<3.12.0> package was omitted from google-ads library, because it conflicts with mysql-connector-java compile dependencies protobuf-java<3.11.4>**, as you can see from the below figure
![image](https://user-images.githubusercontent.com/73671325/97947793-65e3ec00-1dc9-11eb-9b86-6d281175ac04.png)
**After eliminating dependency package conflicts, both FieldMasks.allSetFieldsOf(updated) and FieldMasks.compare(original, updated) work perfectly**, and here is the detail request/response log

2020-11-03 11:12:51.561 [Gax-2] INFO  com.google.ads.googleads.lib.request.summary - SUCCESS REQUEST SUMMARY. Method: google.ads.googleads.v5.services.CampaignCriterionService/MutateCampaignCriteria, Endpoint: googleads.googleapis.com:443, CustomerID: Customer123, RequestID: G3QrLt913_V4eTUhEOrL-A, ResponseCode: OK, Fault: null. 
2020-11-03 11:12:51.565 [grpc-nio-worker-ELG-1-3] DEBUG i.g.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x72f5be07, L:/192.168.2.181:64761 - R:googleads.googleapis.com/172.217.160.74:443] INBOUND PING: ack=true bytes=1234 
2020-11-03 11:12:51.566 [grpc-nio-worker-ELG-1-3] DEBUG i.g.netty.shaded.io.grpc.netty.NettyClientHandler - Window: 1048576 
2020-11-03 11:12:51.597 [Gax-2] DEBUG com.google.ads.googleads.lib.request.detail - SUCCESS REQUEST DETAIL.


Request
-------
MethodName: google.ads.googleads.v5.services.CampaignCriterionService/MutateCampaignCriteria
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=loginCID, x-goog-api-client=gl-java/11.0.8 gapic/ gax/1.57.0 grpc/1.30.0}
Body: customer_id: "Customer123"
operations {
  update {
    resource_name: "customers/Customer123/campaignCriteria/campaignId~criteriaId"
    bid_modifier: 2.85
  }
  update_mask {
    paths: "bid_modifier"
  }
}


Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,request-id=G3QrLt913_V4eTUhEOrL-A,date=Tue, 03 Nov 2020 03:12:49 GMT,alt-svc=h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43")
Body: results {
  resource_name: "customers/Customer123/campaignCriteria/campaignId~criteriaId"
}

Failure message: null
Status: Status{code=OK, description=null, cause=null}. 
2020-11-03 11:12:51.622 [main] INFO  c.a.a.r.a.d.CreateUpdateCampaignCriterion_DeviceBidModifier_Test - ============Total update 1 campaign criteria=========== 
2020-11-03 11:12:51.623 [main] INFO  c.a.a.r.a.d.CreateUpdateCampaignCriterion_DeviceBidModifier_Test - Update DeviceInfo criteria: customers/Customer123/campaignCriteria/campaignId~criteriaId 
2020-11-03 11:12:51.623 [main] INFO  c.a.a.r.s.ScheduleJobGoogleAdsCenterApplication - Execute: DEMO_CREATING_GOOGLE_CAMPAIGN_CRITERION...End
![image](https://user-images.githubusercontent.com/73671325/97948053-49947f00-1dca-11eb-819e-3ccafe03dd22.png)

**Because the main function of the system includes get google-ads data by api and store in the database, and my project using spring boot jpa which also need mysql-connector-java package to connect mysql, are there any recommended best practices for dependency conflicts in this situation?**

**Comment by nwbirnie** [comment]
By far the easiest option here is to attempt to find a common version of the dependency that works for both google-ads and mysql-connector-java. Since google-ads requires at least 3.12.2 (which is very close to the [latest version](https://search.maven.org/artifact/com.google.protobuf/protobuf-java)), you will likely need to override the mysql version. Looking at mysql-connector-java, their [newest release](https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.22/mysql-connector-java-8.0.22.pom) depends on protobuf-java 3.11.4. These are actually quite close together, so just try adding the following dependency to your pom.

```
<dependency>
  <groupId>com.google</groupId>
  <artifactId>protobuf-java</artifactId>
  <version>3.12.2</version>
</dependency>
```

There's more details about how to solve this problem in the maven docs, see the dependency mediation section which explains how maven resolves conflicts. You can see the status of conflicts in your project by running `mvn dependency:tree -Dverbose`.
