### ISSUE TITLE
Expose Remarketing Tags In API

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#367]
Hi All,

In v201809 of the AdWords API we could query the CustomerService for the RemarketingSettings in order to get the Remarketing Tags ( called snippet in the API object model ) for the account:

```
https://developers.google.com/adwords/api/docs/reference/v201809/CustomerService.RemarketingSettings
```

As of V6 of the Ads API I'm still not sure where to find that data via the API. I brought it up with the AdWords API forum back in January and they said they put in the feature request:

```
https://groups.google.com/g/adwords-api/c/BD3cC-Ht4_o
```

Are the remarketing tags currently exposed via the Ads API? If not, is there a roadmap for them? It's one of the last hurdles for our complete migration from AdWords API to Ads API.

Thanks
Pete

**Comment by nwbirnie** [comment]
This is available from [ConversionAction.tag_snippets](https://developers.google.com/google-ads/api/fields/v6/conversion_action#conversion_action.tag_snippets).

**Comment by PeterLavetsky** [comment]
Nick,

It's not the same data.

AdWords API v201809 customer.getRemarketingSettings().getSnippet() gives a JS snippet that looks like this:

```
<!-- Google Code for Remarketing Tag -->
<!--------------------------------------------------
Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
--------------------------------------------------->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = ABC123;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/ABC123/?guid=ON&amp;script=0"/>
</div>
</noscript>
```

The ConversionAction TagSnippets for the same customer through the Ads API does not contain the above data.

Pete

**Comment by jradcliff** [comment]
I'll chime in here, as I was involved in some of the changes made in the Google Ads API around this feature. The AdWords API blurred the line between "conversion action" and "remarketing action", so we decided to officially make them separate concepts in the Google Ads API, as they are in the UI.

I'll look through our notes to see if I can shed more light on this.

**Comment by nwbirnie** [comment]
I'm guessing that this is the correct resource? [remarketing_action.tag_snippets](https://developers.google.com/google-ads/api/fields/v6/remarketing_action#remarketing_action.tag_snippets)

**Comment by jradcliff** [comment]
Right, but @PeterLavetsky mentioned in [the forum post](https://groups.google.com/g/adwords-api/c/BD3cC-Ht4_o) that `tag_snippets` was empty in responses. I'm looking into the example provided there.

**Comment by jradcliff** [comment]
@PeterLavetsky , I'm not seeing any remarketing actions on the account you mentioned on the forum. Could you try with another account and let us know if you get back snippets? The response:

```
Body: field_mask {
  paths: "remarketing_action.id"
  paths: "remarketing_action.name"
  paths: "remarketing_action.resource_name"
  paths: "remarketing_action.tag_snippets"
}
```

Means that no rows were returned.

**Comment by PeterLavetsky** [comment]
Full disclosure: I'm working with a different customer today than the customer from the forum post in January but the two customers are in the same boat: no remarketing actions exist but they *do* both get a remarketing snippet back from the AdWords API.

My current thought process is to construct the remarketing tag manually since the only piece of dynamic data in the JS snippet appears to be the google_conversion_id and I do get that value back from the Customer resource:

```
customer.getConversionTrackingSetting().getConversionTrackingId()
```

However it seems a little loose and prone to errors if Google changes that JS code in the future.

In the meantime I'll look for another account that does have remarketing actions and see if the snippets come back there.

**Comment by PeterLavetsky** [comment]
I looked through a couple dozen accounts and didn't find any remarketing actions.

However I did move forward with manually constructing the remarketing tag using the conversionTrackingId found on Customer and I've been able to achieve parity that way.

Assuming that JS snippet doesn't change much ( hardly ever? ) I should be able to make this solution work.

**Comment by jradcliff** [comment]
Thanks for the update. I'm checking in with some folks on our side to try to get more info on why this changed.

**Comment by jradcliff** [comment]
I filed a feature request to have this added to the API, but I don't have a timeline at this point. One of the challenges is that unlike the conversion event snippet, the remarketing event snippet requires further customization after you retrieve it (there are some placeholders in there for values you need to update), so the snippet is not ready for use "out of the box".

I'll close this library issue, but if and when we add this to the API, we'll be sure to include it in the appropriate version's [release notes](https://developers.google.com/google-ads/api/docs/release-notes).

Thanks,
Josh

**Comment by PeterLavetsky** [comment]
Cool ... thanks @jradcliff
