### ISSUE TITLE
Set endpoint override information on ServiceClients based on the GoogleAdsClient that created it

### ISSUE THREAD

**Issue by keith-wiersema** [googleads/google-ads-java#388]
**Describe the problem you are trying to solve**
I am running into some unexpected behavior when setting the endpoint on the GoogleAdsClient, my endpoint override set in the GoogleAdsClient is ignored by any service created from that GoogleAdsClient. 

In this example, I would expect both the GoogleAdsClient and the AdGroupCriterionServiceClient to be pointing to `localhost:8080` but the AdGroupCriterionServiceClient is still pointing to `googleads.googleapis.com:443`:
```
GoogleAdsClient googleAdsClient = GoogleAdsClient.newBuilder().fromProperties(properties)
                    .setEndpoint("localhost:8080")
                    .build();
System.out.println("Google Ads Client Endpoint: " + googleAdsClient.getEndpoint());

AdGroupCriterionServiceClient adGroupCriterionServiceClient = googleAdsClient.getLatestVersion().createAdGroupCriterionServiceClient();
System.out.println("Ad Group Criterion Service Client Endpoint: " + adGroupCriterionServiceClient.getSettings().getEndpoint());
```

**Describe the solution you would like**
One way to accomplish this would be to have the `ClientSettings` `setTransportChannelProvider()` method also call `setEndpoint()` with the endpoint information on the `TransportChannelProvider` (admittedly hacky). Alternatively, the create client methods in the `GeneratedCatalog` could be modified to call the `setEndpoint()` method with the endpoint in the `TransportChannelProvider`.

**Describe alternatives you've considered**
I would like to be able to mock responses coming back from the api to write offline end-to-end integration tests for my application. I was able to accomplish this with the old Adwords client by specifying endpoint overrides to the client. 
If the google ads test accounts were able to generate mock report data that is not all zeros, that would eliminate the biggest issue that requires me to do response mocking for testing.

**Comment by nwbirnie** [comment]
It looks like the correct endpoint should be connected, but the service settings will return the wrong value. This is unintuitive but probably working as intended... the settings are one of the inputs used to create the client, but we don't specify the endpoint there. Instead we specify the endpoint via the `TransportChannelProvider` as you mentioned. 

I ran this test...

```
    Properties properties = new Properties();
    properties.put("api.googleads.endpoint", "localhost:4444");
    properties.put("api.googleads.clientId", "foo");
    properties.put("api.googleads.clientSecret", "bar");
    properties.put("api.googleads.refreshToken", "baz");
    properties.put("api.googleads.developerToken", "bam");
    GoogleAdsClient client =
        GoogleAdsClient.newBuilder()
            .fromProperties(properties)
            .setEndpoint("localhost:5555")
            .build();

    try (GoogleAdsServiceClient gasClient =
        client.getLatestVersion().createGoogleAdsServiceClient()) {
      gasClient.search("123", "foo bar");
    }
```

... and created two server sockets with netcat: `nc -k -l 4444`, `nc -k -l 5555`. I can see that the client correctly connects to `localhost:5555` in this example. Are you seeing the client not connect to the endpoint specified by calling `setEndpoint()`?

If you don't have a signed SSL certificate to use with your tests, you'll most likely also want to access [`GoogleAdsClient.setTransportChannelProvider`](https://github.com/googleads/google-ads-java/blob/a82618168ea2a3a09bc9910c25674dc8d0877a71/google-ads/src/main/java/com/google/ads/googleads/lib/GoogleAdsClient.java#L351-L352). This is package-private so you'll need to declare a class in the same pacakge name to call this method. The two main options for transport are to either enable unencrypted TCP connections, or override with a mock service handler. We use the latter approach for our tests. You can see this in [`GoogleAdsClientTest`](https://github.com/googleads/google-ads-java/blob/master/google-ads/src/test/java/com/google/ads/googleads/lib/GoogleAdsClientTest.java#L629-L652). The [`MockServiceHelper`](https://github.com/googleads/google-ads-java/blob/a82618168ea2a3a09bc9910c25674dc8d0877a71/google-ads/src/test/java/com/google/ads/googleads/lib/GoogleAdsClientTest.java#L96-L97) class is a good one to use in my experience. 

Alternatively you can disable SSL by doing:

```java
GoogleAdsClient.Builder clientBuilder = ...;
InstantiatingGrpcChannelProvider provider = 
    (InstantiatingGrpcChannelProvider) clientBuilder.getTransportChannelProvider();
InstantiatingGrpcChannelProvider.Builder providerBuilder = provider.toBuilder()
    // Disable SSL.
    .setChannelConfigurator(ManagedChannelBuilder::usePlaintext)
    .build();
clientBuilder.setTransportChannelProvider(provider);
```

**Comment by keith-wiersema** [comment]
@nwbirnie I see the tests hang with no evidence that they have connected to the mock server I set up. I will take a look at `GoogleAdsClientTest` and attempt to replicate the approach there as this seems like an issue with ssl. I really appreciate the quick response and the clarification around the endpoint properties configuration.

**Comment by nwbirnie** [comment]
Maybe you still need to change the transport channel provider? Something like [here](https://github.com/googleads/google-ads-java/blob/aa72dae6542ce8faffb012135e0ad9fdbeb2e1bf/google-ads/src/test/java/com/google/ads/googleads/lib/GoogleAdsClientTest.java#L125-L126).

Sure, happy to help.

**Comment by keith-wiersema** [comment]
I've verified that the client is attempting to connect to the expected endpoint, closing this out.
