### ISSUE TITLE
Replace customers in a user list request

### ISSUE THREAD

**Issue by awant** [googleads/google-ads-java#415]
There is an example how to add customers to a specific user list (https://github.com/googleads/google-ads-java/blob/50a65751c0b714cadcdd7c3ff1f3eebc65090f6d/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/AddCustomerMatchUserList.java), but how to replace customers fully?
Looks like we should do something like this:
1) Run a job to wipe a user list with a single operation: 
```
OfflineUserDataJobOperation.newBuilder().setRemoveAll(true).build()
```
2) Add new users to the user list with operations:
```
UserData ud = ...;
OfflineUserDataJobOperation.newBuilder().setCreate(ud).build()
```

Is it true? And how do offline jobs execute in google backend? Can be the situation where the second job executes earlier than the first?

**Comment by nwbirnie** [comment]
These jobs could execute in parallel, so you should wait for the first job to complete before starting the second.

In terms of which request body to set here I'm not exactly sure. I'd suggest reaching out on our [forum](https://groups.google.com/g/adwords-api) where our support team will be able to point you in the right direction.

**Comment by awant** [comment]
Yep, that is exactly what I did in the first place. They suggested to reach you for this question: https://groups.google.com/g/adwords-api/c/Gqum3kL6qpk/m/ZR1yvZ6zAgAJ

**Comment by nwbirnie** [comment]
Oh I see. Yes, so your syntax above is correct.

```
OfflineUserDataJobOperation.newBuilder().setRemoveAll(true).build()
```

This will remove all users from the user list. Note that this [only supports](OfflineUserDataJobOperation.newBuilder().setRemoveAll(true).build()
) customer match user lists.

**Comment by jradcliff** [comment]
One additional note: I just confirmed that if your goal is to remove all members and add new members, then you can do so in a _single job_ by ordering the operations in the job as:

1. The operation with `removeAll = true`
2. The `create` operations

The first operation will mark all _existing_ members in the list for removal, but will not mark the members from the subsequent `create` operations for removal.

Thanks

**Comment by awant** [comment]
@jradcliff Thank you for a solution but there is an obstacle.
If we want to remove all members and add new, for example, 199,999 members, then we have to split adding in two batches (api can process only 100k operations in a single request).
So,
the first batch contains 1 removeAll operation and 99,999 members to add after that (100k operations)
the second batch contains 100k members to add

If the api doesn't support ordering by time, then they execute in parallel and it will be complete mess.

**Comment by jradcliff** [comment]
I think there may be a way to satisfy your use case using the [`external_id` attribute of `OfflineUserDataJob`](https://developers.google.com/google-ads/api/reference/rpc/v6/OfflineUserDataJob#external_id), but I need to confirm the behavior. I'll investigate and get back to you once I have an answer.

Thanks,
Josh

**Comment by jradcliff** [comment]
I've got good news: the 100k limit applies to each [`AddOfflineUserDataJobOperations`](https://developers.google.com/google-ads/api/reference/rpc/v6/OfflineUserDataJobService#addofflineuserdatajoboperations) request, _not_ to the job overall (I'll update our documentation accordingly). This means you do _not_ need to split the upload into multiple jobs. Instead, you can do this sequence of steps:

1. `AddOfflineUserDataJobOperations` where the first operation has `removeAll = true` and remaining 99,999 ops are `create`.
2. `AddOfflineUserDataJobOperations`with 100,000 more `create` operations.
3. `AddOfflineUserDataJobOperations`with 100,000 more `create` operations.
4. ...repeat until all operations added to the job.
5. `RunOfflineUserDataJob` to start the job and apply all operations.

I think that covers your use case, but let feel free to reopen this issue if you have additional questions.

Thanks,
Josh

**Comment by awant** [comment]
Unfortunately, this solution doesn't work.
I don't know to whom I should write about a strange behaviour, so let's start from here :).

I made the exact same sequence of steps and launched the job to apply all operations.
After a day it looked like it worked. I could get mine 'offline_user_data_job' and 'user_list'.
Also I saw that the user_list has size_for_display = 130k and size_for_search = 80k, but the offline_user_data_job was in the RUNNING status.
Next day I checked again offline_user_data_job's for the user_list and the user_list itself and it surprised me:
1) size_for_display is 130k, but size_for_search is 0 now.
2) there are two offline_user_data_job's now for the user_list. one (mine) is still in status RUNNING and the second is in status SUCCESS.

Is it expected?

**Comment by jradcliff** [comment]
Could you share the [IDs](https://developers.google.com/google-ads/api/reference/rpc/v6/OfflineUserDataJob#id) of those jobs?

Thanks

**Comment by awant** [comment]
Sure, ids:
6651197514 (RUNNING)
6664062721 (SUCCESS)

**Comment by nwbirnie** [comment]
It looks like your job may be stuck in the running state. I've reached out to the folks who own this service and will get back to you.

b/184946908

**Comment by awant** [comment]
Hi, @nwbirnie, Is there any update?

**Comment by nwbirnie** [comment]
Hey @awant yes there is. We fixed a bug where uploads to mobile user lists were not completing. You should now see that both jobs you mentioned are in status SUCCESS.

However, looking at the userlist in question it would appear that the same anomaly with the size is present. It appears very large on display but has < 100 users on search. I'm guessing that this isn't expected? If not, could you try the upload again? It's possible that something went wrong that may now be fixed.

**Comment by nwbirnie** [comment]
Also did you previously see the same (or similar) userlist have a larger size on search?
