### ISSUE TITLE
Error: "Principal must be an email address", Service Account maybe configured incorrectly in Java Client Library.

### ISSUE THREAD

**Issue by sahil-patel-transformco** [googleads/google-ads-java#417]
When sending the request to google.ads.googleads.v6.services.CampaignCriterionService/MutateCampaignCriteria the response i get :

Error getting access token for service account: 400 Bad Request
  "error": "invalid_request",
  "error_description": "Principal must be an email address"
The Google Ads Forum suggested that Service Account maybe configured incorrectly in Java Client Library.

Attached the code and the request response with error.
[Code.txt](https://github.com/googleads/google-ads-java/files/6236851/Code.txt)
[Request_Response.txt](https://github.com/googleads/google-ads-java/files/6236855/Request_Response.txt)

What changes to make in configuration to resolve this issue?

**Comment by nwbirnie** [comment]
I'm guessing that the JSON file for the service account credentials is possibly invalid or out of date. 

Could you sign in to [console.cloud.google.com/iam-admin/serviceaccounts](console.cloud.google.com/iam-admin/serviceaccounts) and download the JSON file again please?

**Comment by jradcliff** [comment]
Also, the "Principal" error may mean that your `api.googleads.serviceAccountUser` entry in your config is invalid or missing. Check out our [Service Accounts guide](https://developers.google.com/google-ads/api/docs/client-libs/java/oauth-service) for the expected format and contents of the config file.
