### ISSUE TITLE
Generate more useful object names in examples

### ISSUE THREAD

**Issue by jradcliff** [googleads/google-ads-java#42]
Examples such as [AddCampaigns.java](https://github.com/googleads/google-ads-java/blob/master/google-ads-examples/src/main/java/com/google/ads/googleads/examples/basicoperations/AddCampaigns.java#L108) use `System.currentTimeMillis()` to generate random names. This is _somewhat_ useful, but is there an approach we could take to make these names human-readable? For example, if we used `yyyyMMdd_HH:mm:ss` in **UTC**, then users could easily identify _when_ they ran each example or identify the most recently created objects.

**Comment by jradcliff** [comment]
As mentioned in #233 , date/time could still result in collisions.

**Comment by PierrickVoulet** [comment]
I created #385 to fix this issue.

**Comment by jradcliff** [comment]
Fixed back in Dec 2020 via the PR from @PierrickVoulet . Thanks!
