### ISSUE TITLE
MutateCustomerRequest should support partialFailures

### ISSUE THREAD

**Issue by dmitchell** [googleads/google-ads-java#425]
The api supports it but the java impl does not.

**Comment by jradcliff** [comment]
The `CampaignServiceClient.mutateCampaigns` does not provide this in the convenience method that takes the customer ID and operations list, but the method is overloaded to accept a `MutateCampaignsRequest` where you can set additional attributes like `partialFailure` and `validateOnly`:

```
      MutateCampaignsRequest request =
          MutateCampaignsRequest.newBuilder()
              .setCustomerId(Long.toString(customerId))
              .addAllOperations(operations)
              .setPartialFailure(true)
              .build();
      MutateCampaignsResponse response =
          campaignServiceClient.mutateCampaigns(request);
```

**Comment by dmitchell** [comment]
Sorry, yeah, I knew that I meant `MutateCustomerRequest` needs to accept
`setPartialFailures(true)`. I copied and pasted from the wrong place.

**Comment by jradcliff** [comment]
Closing the loop on this, `MutateCustomerRequest` only supports a _single_ operation per request, so `partialFailure` would not be useful for this request. However, you could use `validateOnly` if you want to test a request without actually making changes.

Thanks,
Josh

**Comment by dmitchell** [comment]
Ok, but that defeats using the same code template for all objects as you
well know.
