### ISSUE TITLE
Generating new access tokens

### ISSUE THREAD

**Issue by onurtokat** [googleads/google-ads-java#437]
**Which version of the client library are you using?**
Google Ads Rest API

**Which version of Java are you using?**
curl

**Which operating system (Linux, Windows, ...) and version?**
Mac OS

**Actions taken**

Before, I created ads.properties file. So, I can use this properties call Java API. But, when I used below property values for getting a token (secret and refresh_token are masked for showing you)

api.googleads.refreshToken
api.googleads.clientSecret
api.googleads.clientId

curl \
  --data "grant_type=refresh_token" \
  --data "client_id=316750529358-a4k7l3ctc9c018etpq004s8r4er2dsme.apps.googleusercontent.com" \
  --data “client_secret=xxxxxxxxxxxxxxx" \
  --data “refresh_token=xxxxxxxxxxxxxx" \
  https://accounts.google.com/o/oauth2/auth

**Expected result**
Access token

**Actual result**
it gives error

The document has moved "https://accounts.google.com/signin/oauth/error?authError=Cg9pbnZhbGlkX3JlcXVlc3QSLFJlcXVpcmVkIHBhcmFtZXRlciBpcyBtaXNzaW5nOiByZXNwb25zZV90eXBlGjdodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyIJAD&amp;client_id=316750529358-a4k7l3ctc9c018etpq004s8r4er2dsme.apps.googleusercontent.com"

 
**Anything else we should know about your project / environment**
customer id : 1533625050

**Comment by nwbirnie** [comment]
Hey, I'm really sorry I missed this thread. 

If you want to you can just provide the library the refresh token and we'll handle the access token exchange for you.

Looking at your request, you've got the wrong endpoint, it should be `https://oauth2.googleapis.com/token`. See the docs [here](https://developers.google.com/identity/protocols/oauth2/web-server?hl=en#exchange-authorization-code).
