### ISSUE TITLE
package com.google.ads.googleads.test does not exist

### ISSUE THREAD

**Issue by hommedahl15** [googleads/google-ads-java#439]
I've been trying to setup this library and run the GetCampaigns.java file but I've been getting this error shown below:

![image](https://user-images.githubusercontent.com/85193400/121736040-a40e6000-cabc-11eb-967c-554a11a8a17d.png)

I started the project using the repository URL and opened it as a Maven project.
![image](https://user-images.githubusercontent.com/85193400/121734420-60b2f200-caba-11eb-9199-9c21441c64de.png)

![image](https://user-images.githubusercontent.com/85193400/121734387-5264d600-caba-11eb-9d7d-cecd0997e566.png)

I'm using Oracle OpenJDK 16.0.1 on Windows 10 with this client library: https://github.com/googleads/google-ads-java

I tried enabling annotation processing per someone else's suggestion-- no luck. Still got the same error. 
![image](https://user-images.githubusercontent.com/85193400/121735062-3c0b4a00-cabb-11eb-9c6a-14e021f10d2b.png)

That's all I have done so far with this Library. I haven't entered any credentials on the ads.properties file yet, I'm just learning how to set up an IDE and clone libraries from Github. Should I be able to run the GetCampaigns.java file without getting this error? Or am I missing a step?

Any ideas on what to try next? Thank you in advance!

**Comment by nwbirnie** [comment]
Hey, you just need to generate the test sources. In the IDE menu bar, open `View -> Tool Windows -> Maven` then run the test target on the google-ads project.

**Comment by hommedahl15** [comment]
Hey. So I ran the test target on these shown here:
![Test Target Error](https://user-images.githubusercontent.com/85193400/122124203-94f91c00-cdf4-11eb-813b-4d3b61aec9c9.PNG)
![Java Examples Test Target Errr](https://user-images.githubusercontent.com/85193400/122124251-a3473800-cdf4-11eb-9ee2-e5c036885c22.PNG)

One error on the root file: "Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project google-ads-annotation-processing: Compilation failure
Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.google.ads.googleads.annotations.impl.GoogleAdsCatalogAnnotationProcessor not found"

and another error on the _Google Ads API client library for Java Examples_ referring me to this link: http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Any idea what's going on here? Thanks again for the help I really appreciate it.

**Comment by nwbirnie** [comment]
It looks like you're using gradle, so maven is actually not going to help much here. 

Can you reload the gradle projects?

![image](https://user-images.githubusercontent.com/410275/122202372-e822ab80-ce94-11eb-94ea-58e8e29c9108.png)

Then navigate to the `google-ads` module tests and right click -> Run All Tests.

![image](https://user-images.githubusercontent.com/410275/122202481-025c8980-ce95-11eb-801b-a1995d10365e.png)

That should trigger the code generators to run.

**Comment by hommedahl15** [comment]
Tried importing as a Gradle project and reloading, then running the module test shown here:
![Gradle Module Test](https://user-images.githubusercontent.com/85193400/122247628-1a300f80-ce8d-11eb-861f-935f83479c64.PNG)

Says build was successful after running the test. After that I tried running the GetCampaigns file-- got another error shown here:
![Gradle GetCampaigns error](https://user-images.githubusercontent.com/85193400/122247836-451a6380-ce8d-11eb-9b85-62a0a24a3c4c.PNG)

Full error:
Execution failed for task ':google-ads-examples:GetCampaigns.main()'.
> Process 'command 'C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2021.1.1/jbr/bin/java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by nwbirnie** [comment]
The IntelliJ gradle runner hides the full error details. You need to click on the top level error here:

![image](https://user-images.githubusercontent.com/410275/122249767-07cfc900-cec1-11eb-94c7-63e7350ced57.png)




I'm pretty sure you just need to add the command line args (in this case `--customerId XXX`).

**Comment by hommedahl15** [comment]
This may have worked! I entered the customer ID number on line 46 of GetCamapaigns.java

Now I'm seeing "Failed to load GoogleAdsClient configuration from file. Exception: java.io.FileNotFoundException: C:\Users\reid.hommedahl\ads.properties (The system cannot find the file specified)" 
![Gradle failed to load googleadsclient](https://user-images.githubusercontent.com/85193400/122281245-ab17e280-ceaf-11eb-9bfc-43ab8926d6c9.PNG)

From here do I enter the client ID, client secret and refresh token on the GoogleAdsCleint.java file? On lines 156-158?

Or is there another step that I need to complete yet?

Thank you again for the help!

**Comment by nwbirnie** [comment]
Great!

Instructions for the config file are available [here](https://developers.google.com/google-ads/api/docs/client-libs/java/config-file).

The getting started guide might also be useful.
