### ISSUE TITLE
V8 : CALL_AD : display_url VALUE_MUST_BE_UNSET

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#447]
We're migrating to V8 and seeing this error when attempting to mutate a CALL_AD

With no display_url being passed in we're receiving an error back that the VALUE_MUST_BE_UNSET

Prior to V8 we had this one-off snippet of code:

```
/* Not sure why this is needed but was throwing error without it */
if( CALL_ONLY_AD.equals(creativeType) ) {
    ad.setDisplayUrl( destinationUrl );
}
```

I've removed that snippet but we get the same error whether we pass in display_url or not

I've left out the contents of the Ad in the example but we're not passing in display_url as noted by the update_mask

```
Request
-------
MethodName: google.ads.googleads.v8.services.AdService/MutateAds
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=6751935783, x-goog-api-client=gl-java/1.8.0_161 gapic/ gax/1.65.1 grpc/1.37.0}
Body: customer_id: "2632884598"
operations {
  update {
    type: CALL_AD
    resource_name: "customers/2632884598/ads/478108505216"
    id: 478108505216
  }
  update_mask {
    paths: "resource_name"
    paths: "id"
    paths: "type"
    paths: "call_ad.country_code"
    paths: "call_ad.phone_number"
    paths: "call_ad.business_name"
    paths: "call_ad.description1"
    paths: "call_ad.call_tracked"
    paths: "call_ad.phone_number_verification_url"
  }
}

```

```
Response
--------
Headers: Metadata(content-type=application/grpc,request-id=IA7d5j6rgTc3Xnod-yUZew,date=Tue, 22 Jun 2021 15:11:23 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43")
Body: null
Failure message: errors {
  error_code {
    field_error: VALUE_MUST_BE_UNSET
  }
  message: "The field cannot be set."
  location {
    field_path_elements {
      field_name: "operations"
      index: 0
    }
    field_path_elements {
      field_name: "update"
    }
    field_path_elements {
      field_name: "display_url"
    }
  }
}
request_id: "IA7d5j6rgTc3Xnod-yUZew"

Status: Status{code=INVALID_ARGUMENT, description=Request contains an invalid argument., cause=null}.
```

```
com.google.api-ads:ads-lib:4.2.0
com.google.api-ads:google-ads:13.0.0
```

Thanks
Pete

**Comment by nwbirnie** [comment]
Hey, it looks like you're affected by the migration of call only ads to call ads. There's more details available [here](https://ads-developers.googleblog.com/2021/06/call-ads-replace-call-only-ads-in.html).

**Comment by PeterLavetsky** [comment]
@nwbirnie I understand there was a migration from Call Only Ads to Call Ads. 

We're now setting CallAdInfo instead CallOnlyAdInfo.

We are not setting display_url and yet the error returned is a reference stating that the display_url needs to be unset.

At this point we are not able to mutate existing Call Ads.

Please advise.

Pete

**Comment by nwbirnie** [comment]
Sounds like this could be a bug on the backend side. Could you report on the [forum](https://groups.google.com/forum/#!forum/adwords-api) please?

**Comment by PeterLavetsky** [comment]
@nwbirnie I've posted it on the forum. Time will tell if it will prove more economical than getting Google's left hand to talk to their right.

**Comment by nwbirnie** [comment]
It should be, that's the official process and there's a team dedicated to providing first line support. They'll identify if there's actually an issue on your side and hence you can go straight ahead to fix it. If not then they'll escalate to folks who will replicate the issue in more depth and possibly provide a solution or workaround. And of course if there is an issue on our side then it will be reported to exactly the right people to fix it, together with steps to reproduce the issue.

We work on the client library so we don't always have full context on every part of the API. It's not viable/economical for us to investigate every potential issue, particularly where it's unlikely to be caused by the client library. Also we don't necessarily know the details of every feature in the API, as in this case.

Hope that makes sense and it's not too frustrating. In general, issues that are most likely caused by the client library are fine to report here, but things that affect the API as a whole should go on the forum.

**Comment by PeterLavetsky** [comment]
@nwbirnie Understood, and appreciated.

A small sample of the reasons why this process is frustrating:

First page results on the forum have various threads with the following OP timestamps and first reply from Google:

```
5 days ago OP: 
2 days ago OP: Attention please, still no reply.
1 hour ago: Google response
```

```
4 days ago OP: 
10 hours ago: Google response
```

```
4 days ago OP:
9 hours ago: Google response
```

If there's a full team dedicated to providing first line support and > 72 hour response latency is acceptable then that's frustrating. 

My first post to the AdWords API forum was 12/29/06 : https://groups.google.com/g/adwords-api/c/UjSMdzMsYTM/m/vweyimQsPD4J and I've posted a total of 214 new topics to the forum. 

My first issue posted to this API bug board was 3/29/19 : https://github.com/googleads/google-ads-java/issues/63 and I've posted a total of 13 new bugs or enhancements.

Clearly I have an internal decision tree that speaks to "This should probably go to the AdWords API forum" or "This should probably go to the API GitHub bug board"

Having my API issue closed within the hour and being told "hey did you know there was a migration?", while I applaud the response time, is frustrating.

Lastly ... we're typically early adopters of the new API versions. Case in point: V8 was announced on 6/09 : https://developers.google.com/google-ads/api/docs/release-notes#v80_2021-06-09 and the Java client library was announced on 6/17 : https://github.com/googleads/google-ads-java/releases/tag/13.0.0

When a CallOnlyAdInfo mutates fine on V7 of the Client Library and on migration to V8 and with a sole change to a CallAdInfo object, I wouldn't think it's out of the realm of possibilities to think that the error may have something to do with the client library.

**Comment by nwbirnie** [comment]
Thanks for the feedback - we have a lot invested in the success of the forum support team, so I'm concerned to see the experience you're mentioning above. Rest assured that I'll bring this up with the folks who run the team.

My apologies if my response was curt, will try to be more helpful going forwards.

This one is almost certainly not to do with the client library - the backend is saying you must mutate a field which isn't in the request and seems unnecessary to provide. Given the history of needing a workaround I'm guessing that there's something wrong with the request validation.

**Comment by PeterLavetsky** [comment]
Similar to the work needed for https://github.com/googleads/google-ads-java/issues/272 here is the workaround I've implemented to get CallAd mutates working in V8:

```
final FieldMask.Builder fieldMaskBuilder = FieldMasks.allSetFieldsOf( ad ).toBuilder();

if( ad.hasCallAd() ) {
  fieldMaskBuilder.addPaths( "display_url" );
}
```

```
Request
-------
MethodName: google.ads.googleads.v8.services.AdService/MutateAds
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=6751935783, x-goog-api-client=gl-java/1.8.0_161 gapic/ gax/1.65.1 grpc/1.37.0}
Body: customer_id: "5502070884"
operations {
  update {
    type: CALL_AD
    resource_name: "customers/5502070884/ads/485401104129"
    id: 485401104129
    final_urls: "https://www.tuttleoutdoorpower.com"
    call_ad {
      country_code: "US"
      phone_number: "(830) 742-3516"
      business_name: "Tuttle Outdoor Power "
      description1: "Find Your Next Vehicle Today At Tuttle Outdoor Power. Call Us Today."
      call_tracked: true
      phone_number_verification_url: "https://www.tuttleoutdoorpower.com"
    }
  }
  update_mask {
    paths: "resource_name"
    paths: "id"
    paths: "final_urls"
    paths: "type"
    paths: "call_ad.country_code"
    paths: "call_ad.phone_number"
    paths: "call_ad.business_name"
    paths: "call_ad.description1"
    paths: "call_ad.call_tracked"
    paths: "call_ad.phone_number_verification_url"
    paths: "display_url"
  }
}
```

```
Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,request-id=L0H6EuizAuKQZVZrdxpoIQ,date=Tue, 22 Jun 2021 18:55:17 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43")
Body: results {
  resource_name: "customers/5502070884/ads/485401104129"
}
```

Thanks
Pete

**Comment by nwbirnie** [comment]
Thinking about it, the validation here might actually be correct. It could be saying _"you're changing the final_urls, so you must also update display_url"_.

**Comment by PeterLavetsky** [comment]
In conjunction with setting the final urls I've tried setting display_url to each of the following:

```
null
""
the same as final_urls
```

null throws NPE and the other two error with  field_error: VALUE_MUST_BE_UNSET

By not setting display_url ( on an existing ad ) it also gives VALUE_MUST_BE_UNSET unless I do my field mask work around posted above.

**Comment by AnashOommen** [comment]
@PeterLavetsky our sincerest apologies for the delays in responding to your posts on the Google Ads API forum. From the timeline, it looks related to a forum <-> support integration issue we had during the last couple of weeks. We normally respond to all forum questions within 24 hours. 

In the future, if you post something on the forum and takes more than a day for response, you can also mail the queue directly -- googleadsapi-support@google.com.
