### ISSUE TITLE
Campaigns not showing in console after running GetCampaigns file successfully 

### ISSUE THREAD

**Issue by hommedahl15** [googleads/google-ads-java#448]
I successfully ran the GetCampaigns.java file after setting up the configuration file. It says this in the console:

BUILD SUCCESSFUL in 9s
10 actionable tasks: 1 executed, 9 up-to-date
5:43:20 PM: Task execution finished 'GetCampaigns.main()'.

![Gradle GetCampaigns build successful](https://user-images.githubusercontent.com/85193400/123010271-e91b7780-d383-11eb-92f4-cf5ca89f83ef.PNG)

I'm using Gradle and Oracle OpenJDK 16.0.1 on Windows 10 with this client library: https://github.com/googleads/google-ads-java

I expected to see a list of the campaigns appear in the console. It says the build was successful though, am I missing something? Where can I view the campaigns to ensure that this file ran properly?

Thank you

**Comment by nwbirnie** [comment]
It looks like you ran this on a customer ID with no active campaigns. If you login to ads.google.com and look at the same customer ID do you see any campaigns if you filter by `status = "All enabled"`?

![image](https://user-images.githubusercontent.com/410275/123081834-4bbd5380-d416-11eb-9350-5a69100288c4.png)

**Comment by hommedahl15** [comment]
In short, yes I do see enabled campaigns in the Google Ads UI. 

In the first screenshot I provided, I used the manager account (MCC) customer ID number on line 46 of the GetCamapaigns.java file and on the ads.properties file. This manager Google account houses all of our individual client accounts. I still do not see the campaign names when running this file, even with the enabled campaigns from client accounts. This is what shows up in the console when using the manager account customer id number:

![Gradle GetCampaigns build successful](https://user-images.githubusercontent.com/85193400/123164348-70c2be00-d438-11eb-8f52-caf303838e6d.PNG)

I tried again using the client account customer ID number (not the manager account) on line 46 of the GetCampaigns.java file and in the ads.properties file. After running the GetCampaigns.java file it gave me an error saying I don't have permission to access customer. 

![client account CID permission error](https://user-images.githubusercontent.com/85193400/123165191-85ec1c80-d439-11eb-8731-712a339f7553.PNG)

I found this page talking about a ['\login-customer-id/' header. ](https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid). What file and line do I write this header? Do I just place that URL somewhere and swap out the customer ID number?  

![client account CID permission error](https://user-images.githubusercontent.com/85193400/123165842-55f14900-d43a-11eb-9764-af9e89cda07d.PNG)

![login customer id error](https://user-images.githubusercontent.com/85193400/123167394-14fa3400-d43c-11eb-8d7a-09835a8a4415.PNG)


![image](https://user-images.githubusercontent.com/85193400/123165800-4a058700-d43a-11eb-8443-ffe20bf871fa.png)

Thank you again so much for the help!

**Comment by nwbirnie** [comment]
Manager accounts don't have any reporting stats available, so that explains why you weren't seeing any results the first time.

When you access a customer ID by authenticating as a user with access to a manager, you must specify `GoogleAdsClient.newBuilder().setLoginCustomerId(XXX)` to the ID of the manager account. This tells the API how to authenticate your request (in this case using your permissions as the manager account).

**Comment by hommedahl15** [comment]
That makes sense. 

What file do I write this line? GoogleAdsClient.newBuilder().setLoginCustomerId(XXX)?

Thank you!!

**Comment by nwbirnie** [comment]
All the example code has the same preamble at the top which initializes the `GoogleAdsClient`. In the case of `GetCampaigns`, it would go [here](https://github.com/googleads/google-ads-java/blob/193ec9700df7b128405bd68eaf89a6155f3c1d7d/google-ads-examples/src/main/java/com/google/ads/googleads/examples/basicoperations/GetCampaigns.java#L51).
