### ISSUE TITLE
Add Similar User List to Campaign

### ISSUE THREAD

**Issue by vgopalkr** [googleads/google-ads-java#451]
**Looking for the API to add Similar User List(auto generated by Google) to the Campaign**

**Solution that I see is for adding UserList to Campaign**
GoogleAdsClient client = clientFactory.create(UserName, AccountId)
        CampaignCriterionServiceClient campaignCriterionServiceClient =  client.latestVersion.createCampaignCriterionServiceClient()

        UserListInfo userListInfo = UserListInfo.newBuilder().setUserList("{user-list-id}").build()
        CampaignCriterion campaignCriterion =  CampaignCriterion.newBuilder().setCampaign("{campaign-id}").mergeUserList(userListInfo).build()
        CampaignCriterionOperation criterionOperation = CampaignCriterionOperation.newBuilder().setCreate(campaignCriterion).build()

        campaignCriterionServiceClient.mutateCampaignCriteria("{customer-id}", [criterionOperation])

**Additional context**
Both the User List and the Similar User List can be added to the Campaign from the Ads UI but do not see any option for Similar User List to be added to the Campaign using the API.

**Comment by nwbirnie** [comment]
In general, please use the forum for questions such as this (where it's not a specifc question aobut the java client library, but rather a general question about how to use the API).

To answer your question, you'll want to run a Google Ads Service search query to retrieve the similar user lists.

The query for this would look something like:

```
SELECT user_list.id FROM user_list WHERE user_list.similar_user_list.seed_user_list = 'customers/XXX/userLists/YYY'
```

**Comment by vgopalkr** [comment]
Hi Nick,

Thanks for your email.
I want to link or add the similar user list to Campaign. The below query only fetches the list.
If you have any suggestions, please advice. Also please let me know forum link where I can post my queries.

Thanks,
Vimal

From: Nick Birnie ***@***.***>
Reply-To: googleads/google-ads-java ***@***.***>
Date: Wednesday, June 30, 2021 at 2:51 AM
To: googleads/google-ads-java ***@***.***>
Cc: "Gopalakrishnan, Vimal" ***@***.***>, Author ***@***.***>
Subject: Re: [googleads/google-ads-java] Add Similar User List to Campaign (#451)


In general, please use the forum for questions such as this (where it's not a specifc question aobut the java client library, but rather a general question about how to use the API).

To answer your question, you'll want to run a Google Ads Service search query to retrieve the similar user lists.

The query for this would look something like:

SELECT user_list.id FROM user_list WHERE user_list.similar_user_list.seed_user_list = 'customers/XXX/userLists/YYY'

**Comment by nwbirnie** [comment]
I included the forum URL on the github issue as a link: https://groups.google.com/forum/#!forum/adwords-api

The general idea is that you add either a CampaignCriterion or AdGroupCriterion and specify the user list details in there.

For [CampaignCriterion](https://developers.google.com/google-ads/api/reference/rpc/v8/CampaignCriterion), specify [CampaignCriterion.user_list.resource_name](https://developers.google.com/google-ads/api/reference/rpc/v8/CampaignCriterion#user_list) with the resource name retrieved from the query mentioned above.

For [AdGroupCriterion](https://developers.google.com/google-ads/api/reference/rpc/v8/AdGroupCriterion), the same idea, except you specify the [AdGroupCriterion.user_list.resource_name](https://developers.google.com/google-ads/api/reference/rpc/v8/AdGroupCriterion#user_list)

Note that the above explanation also contains links so you should view this on github, not just in email.

**Comment by vgopalkr** [comment]
Thanks for the response Nick.

My actual question here is – Can we assume User List and Similar User List are the same in terms of the API usage ? Can I use Similar User List Id/name and set that in CampaignCriterion.user_list.resource_name ? because I do not find an option that specifically says similar_user_list or something like that.

Thanks,


From: Nick Birnie ***@***.***>
Reply-To: googleads/google-ads-java ***@***.***>
Date: Thursday, July 1, 2021 at 9:58 AM
To: googleads/google-ads-java ***@***.***>
Cc: "Gopalakrishnan, Vimal" ***@***.***>, Author ***@***.***>
Subject: Re: [googleads/google-ads-java] Add Similar User List to Campaign (#451)


I included the forum URL on the github issue as a link: https://groups.google.com/forum/#!forum/adwords-api

The general idea is that you add either a CampaignCriterion or AdGroupCriterion and specify the user list details in there.

For CampaignCriterion<https://developers.google.com/google-ads/api/reference/rpc/v8/CampaignCriterion>, specify CampaignCriterion.user_list.resource_name<https://developers.google.com/google-ads/api/reference/rpc/v8/CampaignCriterion#user_list> with the resource name retrieved from the query mentioned above.

For AdGroupCriterion<https://developers.google.com/google-ads/api/reference/rpc/v8/AdGroupCriterion>, the same idea, except you specify the AdGroupCriterion.user_list.resource_name<https://developers.google.com/google-ads/api/reference/rpc/v8/AdGroupCriterion#user_list>

Note that the above explanation also contains links so you should view this on github, not just in email.

**Comment by nwbirnie** [comment]
Yes, they're all just user lists. The criteria can bid/target any user list in the account.
