### ISSUE TITLE
error: integer number too large | googleAdsClient.newBuilder().setLoginCustomerID(xxx)

### ISSUE THREAD

**Issue by hommedahl15** [googleads/google-ads-java#452]
**Which version of the client library are you using?**
v13.0.0 with Gradle

**Which version of Java are you using?**
Oracle OpenJDK 16.0.1

**Which operating system (Linux, Windows, ...) and version?**
Windows 10

**Actions taken**
I'm trying to edit line 51 of the GetCampaigns.java file with GoogleAdsClient.newBuilder().setLoginCustomerId(XXX)
because I'm using a manager account to access a client account on Google Ads. 
As shown in the screenshot below, line 51 of this file looks like this:
googleAdsClient = GoogleAdsClient.newBuilder().setLoginCustomerId(xxxxxxxxxx);
I used the 10 digit CID number of the manager account, without hyphens. 
![error integer number too long](https://user-images.githubusercontent.com/85193400/124018367-627f1f80-d9ad-11eb-8a85-683435f05c09.PNG)

**Expected result**
Campaign names returned

**Actual result**
error:  integer number too large

Thank you for all of the help on this!

**Comment by jradcliff** [comment]
If you add an `L` to the end of the number, the compiler should interpret the literal as a `long`. Please give that a try and let us know if that doesn't fix it for you.

Thanks,
Josh, Google Ads API Team

**Comment by hommedahl15** [comment]
Hey, just tried it-- no luck. Here's the error it's giving me: 

![error incompatible types](https://user-images.githubusercontent.com/85193400/124035488-38842800-d9c2-11eb-90c6-49dff68e3a7a.jpg)

**Comment by nwbirnie** [comment]
You need to call .build() on the builder.

**Comment by hommedahl15** [comment]
Hey there,

Just tried this and got a different error:

![error in corresponding try statement](https://user-images.githubusercontent.com/85193400/124190758-6a5fc200-da88-11eb-8faa-93f4562c1029.PNG)

Full error: 
Line 52
error: exception FileNotFoundException is never thrown in body of corresponding try statement
    } catch (FileNotFoundException fnfe) {

Line 56
error: exception IOException is never thrown in body of corresponding try statement
    } catch (IOException ioe) {
      ^

Any other ideas?

**Comment by nwbirnie** [comment]
Need to load the configuration file: `GoogleAdsClient.newBuilder().setLoginCustomerId(xxxxxxxxxxL).fromPropertiesFile().build()`.

The config file is as configured [here](https://developers.google.com/google-ads/api/docs/client-libs/java/config-file).

**Comment by hommedahl15** [comment]
It worked! 

I ran the GetCampaigns file successfully. Thank you!
