### ISSUE TITLE
ProviderNotFoundException on Android

### ISSUE THREAD

**Issue by Aorlinn** [googleads/google-ads-java#454]
**Which version of the client library are you using?**
13.0.0

**Which version of Java are you using?**
Java 1.8 

**Which operating system (Linux, Windows, ...) and version?**
Android (SDK Version 30)

I use the client library with my own credentials, because I use other Google client APIs as well, which authenticate with `GoogleSignInAccount` and I don't want to force the user to log in twice. So I extract the token from the signed in account and handle it to a com.google.auth.oauth2.OAuth2Credentials.
It looks like that:

		Credentials credentials = OAuth2Credentials.newBuilder()
				.setAccessToken(new AccessToken(
						GoogleAuthUtil.getToken(mContext,
								GoogleSignIn.getLastSignedInAccount(mContext).getAccount(),
								"oauth2:" + scope)),
						// Set expiration time in one hour, as credentials are created every time
						// this method is called.
						new Date(System.currentTimeMillis() + 60 * 60 * 1000))
				.build();
		GoogleAdsClient client = GoogleAdsClient.newBuilder()
				.setCredentials(mAuthorizationService.getCredentials(SCOPE_ADWORDS))
				.setDeveloperToken(mDeveloperToken)
				.build();

		String query = "SELECT metrics.cost_micros"
				+ "FROM campaign "
				+ "WHERE segments.date BETWEEN '" + getDate(start) + "' AND '" + getDate(start) + "' ";
		SearchGoogleAdsRequest request = createRequest(client, query);
		try (GoogleAdsServiceClient googleAdsService = createServiceClient(client))
		{
			GoogleAdsServiceClient.SearchPagedResponse response = googleAdsService.search(request);
		}

The last command (`googleAdsService.search(request)`) throws the following exception:

    io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
        at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43)
        at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:325)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1800(InstantiatingGrpcChannelProvider.java:81)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:231)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:241)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:219)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:199)
        at com.google.ads.googleads.v7.services.stub.GrpcGoogleAdsServiceStub.create(GrpcGoogleAdsServiceStub.java:97)
        at com.google.ads.googleads.v7.services.stub.GoogleAdsServiceStubSettings.createStub(GoogleAdsServiceStubSettings.java:185)
        at com.google.ads.googleads.v7.services.GoogleAdsServiceClient.<init>(GoogleAdsServiceClient.java:138)
        at com.google.ads.googleads.v7.services.GoogleAdsServiceClient.create(GoogleAdsServiceClient.java:119)
        at com.google.ads.googleads.lib.catalog.GeneratedCatalog$V7Client.createGoogleAdsServiceClient(GeneratedCatalog.java:4948)
 
The problem is, that the provider of grpc-netty-shaded seems not considered in Android, as the method `getHardCodedClasses()` of `io.grpc.ManagedChannelRegistry`, which is used for Android only lists `io.grpc.okhttp.OkHttpChannelProvider` and `io.grpc.netty.NettyChannelProvider`.

I'm not sure, whether the problem would happen, with the default authentication flow, as I didn't try it the other way.

I was able to "fix" the problem temporarily by adding a reference to `io.grpc:grpc-okhttp:1.37.0`, so one of the two providers is available.
But of course this is not a very nice trick, as I need to check the version frequently to prevent a clash.
Please add a reference to one of the two libraries to fix the problem.

Btw. if you know a better way to use the authentication token from `GoogleSignInAccount` I'm very interested ;-)

**Comment by nwbirnie** [comment]
So the workaround you mentioned (adding the dependency) is the correct thing to do here, since gRPC [doesn't support](ManagedChannelProvider) using grpc-netty-shaded artifact on Android. I would suggest using `grpc-netty` rather than okhttp for performance reasons though.

In general, we could solve this in a couple of ways. We could provide a BOM which declares the versions that we require for all dependencies. Or we could just publish another POM which declares the correct dependencies for Android. Let me have a think about what to do here and get back to you.

**Comment by Aorlinn** [comment]
I tried to add `grpc-netty` in the first place, but there were so many conflicts on files (which I resolved using `pickFirst` in the `packagingOptions` of the `build.gradle` file). But there were so many that I just gave up and used `okhttp` instead.

I don't know a lot about BOM and POM. Is there a way to solve these file conflicts as well with one of the two methods?

**Comment by nwbirnie** [comment]
The idea with BOM would be that we provide a list of the versions required for each platform (android and non-android). Then when you depend on something that we also depend on, the version used would be the one we declare in the BOM.

Alternatively, we could provide an empty module which just declares a dependency on `google-ads` plus the necessary differences to get it building on android. It would mean you could depend on `google-ads-android` and get the right dependencies + versions that way.

Probably the POM is a cleaner solution for the android case, but BOMs would generally be applicable to a wider set of users.

**Comment by nwbirnie** [comment]
It occurred to me that we don't actually need another BOM here - there is already one available for grpc. So if you update your `build.gradle` something like this it should work:

```
dependencies {
  // Imports the versions required for grpc 1.37.0.
  // Should make sure that this version is kept up to date with google-ads.
  // Should be possible to make this automatically update with some gradle-fu.
  implementation enforcedPlatform("io.grpc:grpc-bom:1.37.0")
  implementation "com.google.api-ads:google-ads:14.0.0" {
    // Excludes grpc-netty-shaded since this doesn't work on android.
    exclude group: "io.grpc" module "gprc-netty-shaded"
  }
  // Overrides the HTTP implementation with the android compatible version.
  implementation "io.grpc:grpc-netty"
}
```

**Comment by Aorlinn** [comment]
Well I'm having the same issues again with your solution: There are so many conflicts to be resolved (added to the packagingOptions). Plus it's very dangerous, because I do not actively see, if GRPC version is matching the one used by Google Ads.

Btw. you had some typos:
```
    // Imports the versions required for grpc 1.37.0.
    // Should make sure that this version is kept up to date with google-ads.
    // Should be possible to make this automatically update with some gradle-fu.
    implementation enforcedPlatform("io.grpc:grpc-bom:1.37.0")
    implementation ("com.google.api-ads:google-ads:14.0.0") {
        // Excludes grpc-netty-shaded since this doesn't work on android.
        exclude group: "io.grpc", module: "gprc-netty-shaded"
    }
    // Overrides the HTTP implementation with the android compatible version.
    implementation "io.grpc:grpc-netty"
```

**Comment by nwbirnie** [comment]
Yeah it should be quite easy to write a check that verifies that the versions are kept in sync.

I'm not entirely sure why that didn't work. Could you post the resolved dependencies with the change? `./gradlew dependencies --configuration runtimeClasspath` should do the trick (might need to change the configuration name, I'm not sure how this is handled for Android).
