### ISSUE TITLE
Campaign names not displaying after filtering WHERE campaign.id AND campaign.id

### ISSUE THREAD

**Issue by hommedahl15** [googleads/google-ads-java#458]
**Which version of the client library are you using?**
v13.0.0 with Gradle

**Which version of Java are you using?**
Oracle OpenJDK 16.0.1

**Which operating system (Linux, Windows, ...) and version?**
Windows 10

**Actions taken**
Successfully ran the GetCampaigns.java file while using the following string query: 
  String query = "SELECT campaign.id, campaign.name, campaign.vanity_pharma.vanity_pharma_text FROM campaign WHERE campaign.id = xxxxxxxxxxx ORDER BY campaign.id";

This only returned one campaign, but I wanted to return two campaigns. So I added to the string query:
  String query = "SELECT campaign.id, campaign.name, campaign.vanity_pharma.vanity_pharma_text FROM campaign WHERE campaign.id = xxxxxxxxxxx **AND campaign.id = xxxxxxxxxxx** ORDER BY campaign.id";

**Expected result**
Have two results displaying correctly on the console. 

**Actual result**
The console did not print either result to the console, and said "build successful" shown below:

![image](https://user-images.githubusercontent.com/85193400/125532266-7ea00a2b-46ff-41fe-a53d-b5ebb2a57e38.png)

Thank you for all the help on this. I'm making good progress on my project!

**Comment by nwbirnie** [comment]
For general API usage queries, please reach out on the [forum](https://groups.google.com/forum/#!forum/adwords-api). 

The AND condition is a logical and, so in other words the query says _"get me all campaigns where the ID is both X and Y"_. This is literally impossible so there's 0 rows to return. Instead you should put:

```
WHERE campaign.id = xxxxxxxxxxx OR campaign.id = xxxxxxxxxxx
```

or more generally
```
WHERE campaign.id IN (xxxxxxxxxxx, xxxxxxxxxxx)
```
