### ISSUE TITLE
Library is too large to deploy to Google App Engine

### ISSUE THREAD

**Issue by tboedhram** [googleads/google-ads-java#463]
**Which version of the client library are you using?**
14.0.0

**Which version of Java are you using?**
1.8

I'm trying to deploy my application that uses the Google Ads API to Google App Engine, but the deployment fails because the library jar is too large. Is there a way to only use version 8 of the API without including v7 and v6? Is there a different way of using the Google Ads API with Google App Engine?

**Comment by nwbirnie** [comment]
Hey, thanks for reporting. Could you possibly point me at the documentation for the specific limit you're hitting?

I took a look at the binary size, and indeed it looks like the stubs for API versions take up about 80MB in the JAR with support for 4 API versions. When unzipped these take up about 260MB. So would be good to know what the target is so we can look at options to fix, thanks.

**Comment by nwbirnie** [comment]
A short term workaround would be to compile the library from scratch. Simply deleting the vX directories from [here](https://github.com/googleads/google-ads-java/tree/master/google-ads/src/main/java/com/google/ads/googleads) and [here](https://github.com/googleads/google-ads-java/tree/master/google-ads/src/test/java/com/google/ads/googleads) should work.

**Comment by tboedhram** [comment]
Thanks for the quick reply

This is the error message I got 
`ERROR: (gcloud.app.deploy) Cannot upload file [/opt/atlassian/pipelines/agent/build/default/build/staged-app/WEB-INF/lib/google-ads-14.0.0.jar], which has size [66095767] (greater than maximum allowed size of [33554432])`

It looks like the size limit is 32MB, but I couldn't find any current documentation specifying this limit

**Comment by nwbirnie** [comment]
Hmm, let me reach out to the app engine folks to see where this comes from and if it's possible to override.

**Comment by nwbirnie** [comment]
So there's not really a good workaround for the limit on the app engine side. It is at least documented [here](https://cloud.google.com/appengine/quotas#Code).

Would you be able to recompile the library from source, removing the old API versions?

**Comment by tboedhram** [comment]
When I removed the old API versions and recompiled, the jar size was 49.9 MB. It looks like I might have to start going through and cherry picking the API resources that I am using for the project

**Comment by tboedhram** [comment]
So I was able to find a solution for deploying to App Engine. Using the Google App Engine plugin for gradle I was able to add a staging task and set the `enableJarSplitting = true` . After that my deployments started working.

**Comment by nwbirnie** [comment]
Oh nice - thank you for investigating and for posting the solution.

**Comment by AnashOommen** [comment]
Nick, we should document this in our Java library documentation as a known
issue + workaround. Could you file a bug against yourself so we don't
forget?

**Comment by nwbirnie** [comment]
I know, it's on my list.
