### ISSUE TITLE
Fetch keyword concept while generating Keyword Ideas

### ISSUE THREAD

**Issue by Kaushikh961** [googleads/google-ads-java#466]
As we are using the planning services in Google Ads API for generating keyword ideas on our application, we would like to retrieve the keyword concept, which is none other than the theme of the keyword.
We are referring to the same code that has been provided in the API documentation and tried to fetch the Keyword Ideas results, and then the keyword annotation and then the keyword concept. We are getting an empty array from the Keyword Concept object for any input we try, as the Keyword Annotation is null in the output. We would like to know if there is any way to retrieve those values as this is going to be a value add to our application.

**Comment by nwbirnie** [comment]
This is most likely not an issue with the java client library - we're just deserializing what the API returns. Does the UI provide concepts if you view the same plan there? If not then there are no concepts to display. If so, then this is an API bug and should be reported on the [forum](https://groups.google.com/forum/#!forum/adwords-api).
