### ISSUE TITLE
Increase the limit of tasks in parallel with the same developer token

### ISSUE THREAD

**Issue by etorres** [googleads/google-ads-java#484]
We are migrating our processes that download Google Ads reports from the Adwords API to the Google Ads API and we cannot match the download times of the Adwords client. In fact, the total time it takes us to download all the reports with Google Ads is 8x the time it took us with Adwords. To give you an example, typically we download all the reports of a single MCC account in 2 minutes before migrating to the new Google Ads client. After the migration the same operation takes about 16 minutes to complete.

One fact that is definitely impacting on the total download time is that with Adwords we could perform 85 parallel tasks, while with the Google Ads we cannot exceed 16.

We would like to be able to run more tasks in parallel with the same developer token.

We already raised this concern to the Google Ads API Team and they suggested that we open an issue to the Java library team.

Thanks!

**Comment by AnashOommen** [comment]
Hi Erik,

Hmmm... That's interesting.  Could you pls reply to your mail to Google Ads
API team and ask them to escalate to me (Anash) as requested on this
thread? I'll take a look at your original email later today or tomorrow to
take another look at the API side and eliminate it as a source of problem.
I'll loop in more folks from the Java library side if that's where the
issue is.

Tx
Anash

**Comment by PeterLavetsky** [comment]
Just curious, are you getting a hard error for "cannot exceed 16"?

We're doing many more than 16 tasks in parallel with the same developer token.

You may want to look into caching your BackgroundResource.

**Comment by etorres** [comment]
Hi Peter,

We are using the latest version of the Google Ads library from Maven Central: "com.google.api-ads" % "google-ads" % "15.0.0".

We are creating the request with the following code:

val request = SearchGoogleAdsStreamRequest
.newBuilder()
.setCustomerId(customerId.value)
.setQuery(query)
.build()

val context = GrpcCallContext
.createDefault()
.withStreamWaitTimeout(Duration.ofMinutes(5L))
.withStreamIdleTimeout(Duration.ofMinutes(5L))

val streamResponse = googleAdsOriginalClientLatestVersion
.createGoogleAdsServiceClient()
.searchStreamCallable()
.call(request, context)

We have already tried increasing the concurrency above 16 but then about a quarter of all our requests fail with the following error:

10:35:42.817 [Gax-16] WARN  com.google.ads.googleads.lib.request.summary - FAILURE REQUEST SUMMARY. Method: google.ads.googleads.v8.services.GoogleAdsService/SearchStream, Endpoint: googleads.googleapis.com:443, CustomerID: 5768966594, RequestID: null, ResponseCode: CANCELLED, Fault: Call cancelled without message. -

10:36:19.647 [Gax-16] INFO  com.google.ads.googleads.lib.request.detail - FAILURE REQUEST DETAIL.
Request
-------
MethodName: google.ads.googleads.v8.services.GoogleAdsService/SearchStream
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=4377370570, x-goog-api-client=gl-java/1.8.0_301 gapic/0.0.0+3053-155f6237+20210913-1029 gax/1.65.1 grpc/0.0.0+3053-155f6237+20210913-1029}
Body: customer_id: "5768966594"
query: "SELECT campaign.id,campaign.name,campaign.status,ad_group.id,ad_group.name,ad_group.status,ad_group_criterion.criterion_id,ad_group_criterion.keyword.text,ad_group_criterion.status,ad_group_criterion.labels,ad_group_criterion.keyword.match_type,ad_group_criterion.final_urls,ad_group_criterion.effective_cpc_bid_micros,ad_group_criterion.quality_info.quality_score,ad_group_criterion.position_estimates.first_position_cpc_micros,ad_group_criterion.position_estimates.top_of_page_cpc_micros,ad_group_criterion.position_estimates.first_page_cpc_micros,ad_group_criterion.system_serving_status FROM keyword_view WHERE ad_group_criterion.status != \'REMOVED\' AND ad_group_criterion.negative = false AND ad_group.status != \'REMOVED\' AND campaign.status != \'REMOVED\' AND ad_group_criterion.criterion_id != 3000000 AND segments.date BETWEEN \"2021-09-13\" AND \"2021-09-13\""


Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,date=Mon, 13 Sep 2021 08:34:33 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43")
Body: results {
  campaign {
    resource_name: "customers/5768966594/campaigns/1382998523"
    status: ENABLED
    name: "SG:DE:4:DE|TYPE-02.1.5|auxiliary|BRD"
    id: 1382998523
  }
  ad_group {
    resource_name: "customers/5768966594/adGroups/51703962210"
    status: ENABLED
    id: 51703962210
    name: "TYPE-02.1.5:ADD-007:ADD-992:GEO-4.62428|auxiliary:airport:postoffice:munchen|BRD"
  }
  ad_group_criterion {
    resource_name: "customers/5768966594/adGroupCriteria/51703962210~458699703961"
    status: PAUSED
    keyword {
      match_type: BROAD
      text: "aushilfe deutsche post flughafen m\303\274nche"
    }
    system_serving_status: RARELY_SERVED
    criterion_id: 458699703961
    labels: "customers/5768966594/labels/3245013143"
    effective_cpc_bid_micros: 70000
    final_urls: "https://de.trovit.com/jobs/index.php/cod.search_adwords_jobs/type.0/what_d.aushilfe%20deutsche%20post%20flughafen%20munche/tracking.%7B%22acc%22%3A3841%2C%22c%22%3A1382998523%2C%22a%22%3A51703962210%2C
... TRUNCATED. See README.md to configure/disable log truncation.
Failure message: null
Status: Status{code=CANCELLED, description=Call cancelled without message, cause=java.util.concurrent.CancellationException: User cancelled stream
	at com.google.api.gax.grpc.GrpcDirectStreamController.cancel(GrpcDirectStreamController.java:77)
	at com.google.api.gax.grpc.ExceptionResponseObserver$1.cancel(ExceptionResponseObserver.java:57)
	at com.google.api.gax.rpc.Watchdog$WatchdogStream.cancelIfStale(Watchdog.java:328)
	at com.google.api.gax.rpc.Watchdog.runUnsafe(Watchdog.java:130)
	at com.google.api.gax.rpc.Watchdog.run(Watchdog.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
}. -

**Comment by PeterLavetsky** [comment]
Hi Erik,

Couple suggestions:

Try modifying your GrpcCallContext to:

GrpcCallContext.createDefault().withTimeout( Duration.of( 5, ChronoUnit.MINUTES ) )

So your request call would look like:

googleAdsOriginalClientLatestVersion
.createGoogleAdsServiceClient()
.searchStreamCallable()
.call( request, GrpcCallContext.createDefault().withTimeout( Duration.of( 5, ChronoUnit.MINUTES ) ) );

We don't use any of these directives and have no problems :

.withStreamWaitTimeout
.withStreamIdleTimeout

However, if that fails I would look into caching and re-using your BackgroundResource, which in this case is your GoogleAdsServiceClient

So it would look something like:

cachedAdsServiceClient
.searchStreamCallable()
.call( request, GrpcCallContext.createDefault().withTimeout( Duration.of( 5, ChronoUnit.MINUTES ) ) );

I haven't seen your exact error before but we have done some tuning in this area.

Hope this helps

Pete

**Comment by AnashOommen** [comment]
Also, is there a reason to keep 5mins as the timeout? Your requests are
getting cancelled from the client side because the wait/download time
exceeded 5 mins. The payload size and rowcount may most likely differ too,
so you may have to fine-tune the queries as well (e.g. you can reduce the
payload size significantly if you download the campaign and adgroup
details separately first and then just request the IDs in the keyword_view.
If you have say, a million rows, then a million adgroup name and campaign
name entries add up, but that's duplicate information).

The 16 thread concurrency seems like an entirely unrelated issue. As Pete
pointed out, we don't have limits there, so try caching the service
instance.

**Comment by nwbirnie** [comment]
As discussed over email we'll close this for now and revisit when @etorres has time to investigate further.
