### ISSUE TITLE
Lots of errors once imported to eclipse-Maven project

### ISSUE THREAD

**Issue by crazykalyan** [googleads/google-ads-java#502]
Hello Tech team,

I see bunch of issues when I download the code and import it into eclipse. Most of the errors are "cannot be resolved to a type".

We are trying to import this code to execute UploadStoreSalesTransactions.java, due to these errors, I could not run it.

please assist on this.

Thanks
Kalyan

**Describe the bug:**

**Steps to Reproduce:**

**Expected behavior:**

**Client library version and API version:**
Client library version:
Google Ads API version:
JDK version:

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by jradcliff** [comment]
Hi,

This looks like the same issue as #94 . Please take a look at the resolution there and reopen this issue if you still encounter problems.

Thanks,
Josh

**Comment by crazykalyan** [comment]
Hello Josh,

Thanks for the reply. The issue still exists , I see lots of errors once I
imported into eclipse. I have tried all the options mentioned in #94. But
still no luck.

Please see the below screenshot for the eclipse error details.

[image: eclipse.jpg]

Thanks
Kalyan.

**Comment by nwbirnie** [comment]
Hi there, it looks like your screenshot wasn't attached. Could you sign into Github and try posting it directly?
