### ISSUE TITLE
Code import issues

### ISSUE THREAD

**Issue by crazykalyan** [googleads/google-ads-java#503]
Hello Team,

I see lots of issues when I import the code into eclipse. I have made some configuration changes as suggested in #94 . but no luck.

Please see the below [screenshot.]

![image](https://user-images.githubusercontent.com/28395487/141802621-0e7826b2-f9c7-4da4-b985-42465afd743d.png)

**Describe the bug:**

**Steps to Reproduce:**

**Expected behavior:**

**Client library version and API version:**
Client library version:
Google Ads API version:
JDK version:

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by jradcliff** [comment]
Could you give the following a try?

1. Create a branch pointing to the latest release tag:
    ```
    git branch examples-16.0.0 16.0.0
    ```
2. Check out the branch
    ```
    git checkout examples-16.0.0
    ```
3. In Eclipse in a fresh project, _only_ import the pom from `google-ads-examples`.

With this setup, I'm hoping that Eclipse will not attempt to compile the library, but will instead pull version `16.0.0` of the library from Maven central.

I tried this on the command line, and `mvn` and it worked as expected, but I'd be interested to hear if Eclipse behaves similarly.

Thanks,
Josh

**Comment by crazykalyan** [comment]
Thanks Josh for the update.

Could you provide the latest repository Github- https url
*google-ads-examples*  details for the 16.0.0 version?

Thanks
Kalyan.

**Comment by jradcliff** [comment]
Hi Kalyan,

I'm not sure if you're referring to the clone URL or the URL for viewing the repo, so I'll cover both.

1. The clone URL is the same. 16.0.0 is the tag for the latest release, and is at https://github.com/googleads/google-ads-java/tags.

2. If you're looking to browse the repo at that tag, you can use https://github.com/googleads/google-ads-java/tree/16.0.0.

Thanks,
Josh

**Comment by jradcliff** [comment]
Hi Kalyan,

Closing this based on the suggestions provided, but feel free to reopen if you're still encountering issues.

Thanks,
Josh
