### ISSUE TITLE
updates won't work when fields are set to default values - null as default possible?

### ISSUE THREAD

**Issue by schabe77** [googleads/google-ads-java#504]
When updating items the way as suggested at https://developers.google.com/google-ads/api/docs/client-libs/java/field-masks there seems to be a problem, when the value is set (back) to the default value. 

e.g. I have a CustomerConversionGoal that is biddable and I want to deactivate that:
```
        CustomerConversionGoal goal = CustomerConversionGoal.newBuilder()
                .setResourceName("/ACCOUNTID/customerConversionGoals/DEFAULT~WEBSITE")
                .setBiddable(false)
                .build();
        System.out.println(FieldMasks.allSetFieldsOf(goal));
```
only returns
```
paths: "resource_name"
```
the "biddable" path is missing, because `false` is the default value. This behavior leads to undesired effects, if you do not remember that default values have to be considered separately every time.

The moment I create the goal I don't have the original item, so `FieldMasks.compare(original, goal)` is no option for me. As far as I found out the only option for my use case would be to not only set the values for the field but also collect the paths by myself, e.g.
```
        Set<Integer> changedFieldNumbers = Sets.newHashSet(CustomerConversionGoal.BIDDABLE_FIELD_NUMBER);
        List<String> changedFieldNames = CustomerConversionGoal.getDescriptor().getFields().stream()
                .filter(descriptor -> changedFieldNumbers.contains(descriptor.getNumber()))
                .map(FieldDescriptor::getName)
                .collect(Collectors.toList());
        System.out.println(FieldMask.newBuilder().addAllPaths(changedFieldNames).build());
```
But that's a lot of code and quite an overhead to not only set the value, but also keep the field (number) in order to create the field mask. I liked the way the old adwords lib worked: if a value different from `null` was set, this value was transferred, no matter if it was a default value or not.

Wouldn't it be possible to always use objects as fields and set the default to `null` and if the field value is different from `null` to add it to the field mask? Getters of the default items could stay null safe, by checking for a `null` value and returning the default value in case of a null value  instead.

**Comment by nwbirnie** [comment]
Unfortunately this is a known issue and there is not a good way to automate this. The problem stems from using proto3 to represent the API. Fields by default do not have presence, so there is no difference between a field that is not set and a field set to its default value. The [guidelines](https://google.aip.dev/203#optional) prohibit us simply making all mutable fields optional.

It looks like we need to update our guidance to move away from `FieldMasks.allSetFieldsOf()` I'll raise this as a suggestion to update our guidance around constructing mutates.

I'd recommned that you specify the fields manually by doing:

```java
FieldMasks.newBuilder().addPaths("biddable").build()
```

**Comment by schabe77** [comment]
I was afraid that would be the answer. Too bad. I don't like using potential changing strings, so I think I'll use the static field numbers to determine the paths.

By the way. Maybe it's a wanted behaviour and I don't mind if it stays like it is, so I didn't wanted to open a bug report for it:
I have a Convertion Action defined in manager account A and use this action in client account B. When I query the CustomerConversionGoal of account B, I get resource names like `customers/B/customerConversionGoals/DEFAULT~WEBSITE` when I try to update the goal with this resource name I get a `mutate_error: RESOURCE_NOT_FOUND`. e.g. requests kWbuEMzt7OPlL3dS62nwfQ, gm08Zppe7L31nTr-8JZniw.

**Comment by nwbirnie** [comment]
My guess would be that it's working as intended. @jradcliff IIRC we discussed this recently, can you confirm the behaviour here?

**Comment by jradcliff** [comment]
Yes, that's intended if A is the [effective conversion account](https://developers.google.com/google-ads/api/docs/conversions/overview#effective_conversion_account) for B. In that case, in queries on B, you'll be able to _retrieve_ the conversion actions, customer goals, and custom goals defined in A, but you will only be able to _mutate_ those objects via account A.

This is reflected in the UI when you look at the **Conversions --> Summary** page for B. It'll have a message like:

_Conversion goals and actions are managed by manager account (**[customer ID of A]**). To make changes, contact the manager of that account or disconnect from that manager account in your access settings._
