### ISSUE TITLE
Expose Business Operations Verification Status

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#508]
It would be helpful to have the ability to programmatically look at Customers and determine their Business Operations Verification status.

Although clients receive notice that the verification process needs to be completed, we've started seeing accounts suspended because appropriate action has not been taken.

```
Account suspended - Business operations verification is overdue

Dear Advertiser,

Per the Notice of Violation sent to you on November 13, 2021, your Google Ads account 123-456-7890 has been suspended because you failed to complete the Business Operations Verification within the specified time period.
```

Curating an action needed list by querying the Customer through the API would be helpful to us.

Having the field on the Customer object seems a prudent location, alongside other existing fields such as:

```
call_reporting_enabled : true
auto_tagging_enabled : true
has_partners_badge : false
```

Thanks
Pete

```
com.google.api-ads:google-ads:16.0.0
```

**Comment by nwbirnie** [comment]
Hey sorry for the slow reply on this. Please could you file feature requests on the [forum](https://groups.google.com/g/adwords-api)? There's an official process to translate these into product feedback from there. Sorry to send you round the houses :)
