### ISSUE TITLE
External dependencies are included in the jar

### ISSUE THREAD

**Issue by markusheiden** [googleads/google-ads-java#525]
**Describe the bug:**
Libraries like Guava are included in com.google.api-ads:google-ads:16.0.1. That makes the management of these libraries impossible for us when using them in our application too. That bug has been introduced with version 16.0.0. Version 15.0.0
looks fine.

**Steps to Reproduce:**
Look into the jar. It includes e.g. com.google.common.collect.Maps which is part of Guava. There are many many more examples like e.g.  apache commons, slf4j, netty, ....

**Expected behavior:**
Declare these dependencies only as transitive dependencies or include them as shaded jars.

**Client library version and API version:**
Client library version: 16.0.1
Google Ads API version: v9
JDK version: 17

**Comment by jradcliff** [comment]
Released [16.0.2](https://github.com/googleads/google-ads-java/releases/tag/16.0.2) with the fix.
