### ISSUE TITLE
Dereferencing fields by name from GoogleAdsRow

### ISSUE THREAD

**Issue by dmitchell** [googleads/google-ads-java#529]
I'm writing a generic shim over GoogleAdsServiceClient#search which allows the caller to pass any SELECT field in (in addition to a predefined set) and want to return a simple `Map<String,String>` of all these user specified fields which means I need some way to query a `GoogleAdsRow` using the same fieldname syntax as the string select query.

I see com.google.protobuf.GeneratedMessageV3#getField which may be as close as I can get, but it's nonTrivial (I can't figure out how to get FieldDescriptor by name). I can just camel case the snake case path and call those methods by name I guess.

Another option would be to iterate through all set fields in GoogleAdsRow filtering out the ones I know about as I can see how to generate the selectable fieldName from these.

So, does anyone know how to get a field by its name from GoogleAdsRow or how to iterate all set values in GoogleAdsRow and get map fieldName -> value?

Don Mitchell
Principal arch, CarGurus

**Comment by jradcliff** [comment]
The `getFieldValue()` method in our `FieldMasks` utility could be useful for your use case:

https://github.com/googleads/google-ads-java/blob/b994e0f125855cd8f9c3e63d732ceefaae27cd8c/google-ads/src/main/java/com/google/ads/googleads/lib/utils/FieldMasks.java#L179

Also, the `field_mask` on [SearchGoogleAdsStreamResponse](https://developers.google.com/google-ads/api/reference/rpc/v9/SearchGoogleAdsStreamResponse#field_mask) and [SearchGoogleAdsResponse](https://developers.google.com/google-ads/api/reference/rpc/v9/SearchGoogleAdsResponse#field_mask) will contain the dot-separated path to all requested fields from your query.

Cheers,
Josh

**Comment by dmitchell** [comment]
tyvm, perfect

**Comment by jradcliff** [comment]
You're welcome! I'll close this since it seems you have the info you need, but please reopen if I missed anything.

Thanks
