### ISSUE TITLE
Can we get the campaign ID / adgroup ID using campaign resource name / adgroup resource name?

### ISSUE THREAD

**Issue by gotham3** [googleads/google-ads-java#550]
Hi!

I'm aware of the method which fetches the resource name when provided with the customerId and campaignId.

`ResourceNames.campaign(customerId, campaignId)
`
However I need the opposite, i.e., given the campaign resource name and customerId, is it possible to get the campaignId?

I know about the alternate solution which is issuing a GET/Search request with the campaign resource name. However we don't want to exhaust the limits by making unnecessary API calls.

Any help is appreciated! Thanks.

**Comment by jradcliff** [comment]
Hi,

The `ResourceNames` utility is something we added for convenience, but the library also contains a generated `XName` class for each resource type `X`. For example, for `Campaign` you could use the [`CampaignName` class](https://github.com/googleads/google-ads-java/blob/main/google-ads-stubs-v9/src/main/java/com/google/ads/googleads/v9/resources/CampaignName.java#L73) as follows:

```
String campaignIdAsString = CampaignName.parse(resourceName).getCampaignId();
// Convert to a `long` if needed.
long campaignId = Long.valueOf(campaignIdAsString);
```

Cheers,
Josh

**Comment by gotham3** [comment]
Awesome! That helped. Thanks Josh. :)
