### ISSUE TITLE
The effectivetargetcpamicros field of the modified adgroup is invalid

### ISSUE THREAD

**Issue by ZhangYuJie-88** [googleads/google-ads-java#552]
```java
 AdGroup adGroup = AdGroup.newBuilder()
                    .setResourceName(ResourceNames.adGroup(googleAdsClient.getLoginCustomerId(), 129025713061))
                    .setEffectiveTargetCpaMicros(20000)
                    .build();
            List<AdGroupOperation> adGroupOperationList = new ArrayList<>()
 List<AdGroupOperation> adGroupOperationList = new ArrayList<>();
            adGroupOperationList.add(AdGroupOperation.newBuilder()
                    .setUpdate(adGroup)
                    .setUpdateMask(FieldMasks.allSetFieldsOf(adGroup))
                    .build());
            MutateAdGroupsResponse response =
                    adGroupServiceClient.mutateAdGroups(
                            String.valueOf(googleAdsClient.getLoginCustomerId()), adGroupOperationList)

mutateAdGroupResult is  resource_name: "customers/9226672588/adGroups/129025713061"
The effectivetargetcpamicros field is still the original value

**Comment by ZhangYuJie-88** [comment]
出价字段修改后依旧是原有的出价值

**Comment by jradcliff** [comment]
Hi,

The `effective_target_roas` field is read-only. If you want to override the campaign-level target ROAS, please set `target_roas` instead.

https://developers.google.com/google-ads/api/reference/rpc/v9/AdGroup#target_roas

Thanks,
Josh

**Comment by ZhangYuJie-88** [comment]
> 你好，
> 
> 该`effective_target_roas`字段是只读的。如果您想覆盖广告系列级目标广告支出回报率，请`target_roas`改为设置。
> 
> https://developers.google.com/google-ads/api/reference/rpc/v9/AdGroup#target_roas
> 
> 谢谢， 乔什
hi, 
It's effective_ target_ cpa_ Micros, not effective_ target_ roas

**Comment by jradcliff** [comment]
Oops, sorry about that!

Similar guidance applies to `effective_target_cpa_micros`. Each of the fields beginning with `effective_` is *output only* (read only) and is a convenience for allowing you to see which value will be used for the ad group, regardless of whether that value is coming from the campaign's bidding strategy or the ad group itself. If you want to override the value at the ad group level, please use the field without the `effective_` prefix ([`target_cpa_micros`](https://developers.google.com/google-ads/api/reference/rpc/v9/AdGroup#target_cpa_micros) in this case).

Thanks

**Comment by ZhangYuJie-88** [comment]
errors {
 error_code {
   operation_access_denied_error: OPERATION_NOT_PERMITTED_FOR_CAMPAIGN_TYPE
 }
 message: "This operation is not permitted on this campaign type"
 trigger {
   string_value: "MULTIPLE(MULTIPLE_MOBILE_APP)"
 }
 location {
   field_path_elements {
     field_name: "operations"
     index: 0
   }
   field_path_elements {
     field_name: "update"
   }
   field_path_elements {
     field_name: "target_cpa_micros"
   }
 }
}
request_id: "XiikqgkiKFf6pvC1OWD-2Q"

**Comment by ZhangYuJie-88** [comment]
> 糟糕，对此感到抱歉！
> 
> 类似的指导适用于`effective_target_cpa_micros`. 以开头的每个字段`effective_`都是_仅输出_（只读），方便您查看将用于广告组的值，无论该值是来自广告系列的出价策略还是来自广告组本身。如果您想在广告组级别覆盖该值，请使用不带`effective_`前缀的字段（[`target_cpa_micros`](https://developers.google.com/google-ads/api/reference/rpc/v9/AdGroup#target_cpa_micros)在这种情况下）。
> 
> 谢谢

Modified the target_cPA_micros field without effective_ prefix  ,
But remind me error
errors {
 error_code {
   operation_access_denied_error: OPERATION_NOT_PERMITTED_FOR_CAMPAIGN_TYPE
 }
 message: "This operation is not permitted on this campaign type"
 trigger {
   string_value: "MULTIPLE(MULTIPLE_MOBILE_APP)"
 }
 location {
   field_path_elements {
     field_name: "operations"
     index: 0
   }
   field_path_elements {
     field_name: "update"
   }
   field_path_elements {
     field_name: "target_cpa_micros"
   }
 }
}
request_id: "XiikqgkiKFf6pvC1OWD-2Q"

**Comment by jradcliff** [comment]
Hi,

The campaign in question has `advertising_channel_sub_type = APP_CAMPAIGN`. Per the [App campaigns guide](https://developers.google.com/google-ads/api/docs/app-campaigns/create-ad-group):

> If the advertising_channel_sub_type is APP_CAMPAIGN, you cannot override bid settings at the ad group level.

Thanks
