### ISSUE TITLE
GoogleAdsRow to Json

### ISSUE THREAD

**Issue by lpereirafernandez** [googleads/google-ads-java#553]
**Describe the problem you are trying to solve:**
For third party reporting tools using the new Google Ads API, it is fundamental to access the requested information that is returned  with the class GoogleAdsRow in the most flexible way. Unfortunately having to access the results via getter methods (ie row.getMetrics().getImpressions() or row.getAdGroup().getId()) is far from being flexible and makes it really difficult from a programmatic point of view.

**Describe the solution you'd like:**
It would be perfect if you could obtain a Json from the GoogleAdsRow.

**Describe alternatives you've considered:**
Right-now we are considering to a work around solution, based on manipulating the result you get with GoogleAdsRow.toString() to obtain a valid Json string and then parse it to get a proper Json. Obviously this an error promned process and far from being ideal.

**Additional context:**
It would be great if the current behaviour could be improved to provide simple programmatic access to the results in GoogleAdsRow.

**Comment by jradcliff** [comment]
Hi,

Is your goal to get JSON specifically, or simply be able to iterate through the fields of the row in a generic manner?

If you want JSON, you can use [JsonFormat.Printer](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/util/JsonFormat.Printer.html) from the protocol buffers library. However, this may be a rather expensive way to achieve your goal, as the conversion from protocol buffer message to a JSON string could get expensive, particularly on large collections of objects.

If you want a way to generically inspect a row but do not need JSON specifically, you can use the utility methods on [MessageOrBuilder](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/MessageOrBuilder) such as `getAllFields()`, `getField(...)`, and `hasField(...)`.

Would either of those approaches work for your use case?

Thanks,
Josh

**Comment by lpereirafernandez** [comment]
Hi Josh,

Looks like JsonFormat.printer().print(googleAdsRow) could work. We will evaluate the performance but definitely we would feel more comfortable with a JSON.

Many thanks,
Luis
