### ISSUE TITLE
How to use the in clause in query builder class ?

### ISSUE THREAD

**Issue by garuna-m6** [googleads/google-ads-java#558]
**What is your question?**

Quoting previous question https://github.com/googleads/google-ads-java/issues/556 , I still need help with the third point on using the query builder class com.google.api.ads.admanager.lib.utils.QueryBuilder, the library doesn't contain an IN clause condition :/ . 
<img width="936" alt="Screenshot 2022-02-06 at 8 29 43 PM" src="https://user-images.githubusercontent.com/23234342/152686870-5cc3561e-cbc4-4001-b144-1edd3db748db.png">

Also with adwords selector I could use predefined enums for field names like ManagedCustomerField.CustomerId or ManagedCustomerField.Name etc what is the alternative to that for google ads

Thanks in advance

**Comment by jradcliff** [comment]
Hi,

The client library for the Google Ads API does not contain a query builder, but there is a [Query Builder on our developer site](https://developers.google.com/google-ads/api/fields/v9/overview_query_builder) to help you build queries interactively.

If you are looking for a way to retrieve the field names for a resource, you can use `GoogleAdsFieldService` as described in the [guide](https://developers.google.com/google-ads/api/docs/concepts/api-structure?hl=en#retrieve_metadata) and demonstrated in the [GetArtifactMetadata example](https://github.com/googleads/google-ads-java/blob/main/google-ads-examples/src/main/java/com/google/ads/googleads/examples/basicoperations/GetArtifactMetadata.java).

Thanks,
Josh
