### ISSUE TITLE
Google Adwords Api to Google Ads API migration queries

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/google-ads-java#561]
1. Does new Google Ads API uses Rest  or Soap for  Java client lib?

2. Currently in our Adwords API we ere using Stub to call the Adwords API. What will the replacement for the same in Google Ads API? 
AdwordsAPI 
e.g. CampaignServiceSoapBindingStub ,AdGroupServiceSoapBindingStub

3. While using Google Ads API  what will be the replacement of below Adwords API dependencies in pom.xml:

<dependency>
<groupId>com.google.api-ads</groupId>
<artifactId>adwordwssclient</artifactId>
<version>v201809</version>
</dependency>
<dependency>
<groupId>com.google.api-ads</groupId>
<artifactId>googlereportbeans</artifactId>
<version>v201809</version>
</dependency>
<dependency>
<groupId>com.google.api-ads</groupId>
<artifactId>ads-lib</artifactId>
<version>4.1.0</version>
</dependency>

<dependency>
<groupId>com.google.api-ads</groupId>
<artifactId>adwords-axis</artifactId>
<version>4.1.0</version>
</dependency>

Thanks,
Saurabh

**Comment by jradcliff** [comment]
> 1. Does new Google Ads API uses Rest or Soap for Java client lib?

You can access the new Google Ads API using either protobuf/gRPC or REST/HTTP. This library uses protobuf/gRPC.

> 2. Currently in our Adwords API we ere using Stub to call the Adwords API. What will the replacement for the same in Google Ads API? e.g. CampaignServiceSoapBindingStub ,AdGroupServiceSoapBindingStub

Please see some of the examples such as [AddCampaigns.java](https://developers.google.com/google-ads/api/docs/samples/add-campaigns) and [GetCampaigns.java](https://developers.google.com/google-ads/api/docs/samples/get-campaigns), as they all follow the same pattern of:

a) In `main()`, create a `GoogleAdsClient`. This is similar to an `AdWordsSession` and `AdWordsServices` in the AdWords API library.

b) In `runExample()`, get the `XyzServiceClient` from the `GoogleAdsClient`, where `Xyz` is the service type. For example, `CampaignServiceClient` (for mutating campaigns) or `GoogleAdsServiceClient` (for issuing `search` and `searchStream` requests).

c) Use the `XyzServiceClient` methods to issue your requests, similar to the `XyzServiceSoapBindingStub` in the AdWords API.

> 3. While using Google Ads API what will be the replacement of below Adwords API dependencies in pom.xml:
>
> com.google.api-ads adwordwssclient v201809 com.google.api-ads googlereportbeans v201809 com.google.api-ads ads-lib 4.1.0 com.google.api-ads adwords-axis 4.1.0

To use the Google Ads API, you can just declare a dependency on the `google-ads` module as described in [our guide](https://developers.google.com/google-ads/api/docs/client-libs/java/getting-started).
