### ISSUE TITLE
in v10 introduced report parameter omit_unselected_resource_names breaks reports

### ISSUE THREAD

**Issue by schabe77** [googleads/google-ads-java#564]
Hi,

I use the following query to determine the spent campaign costs per day:
 `SELECT segments.date, metrics.cost_micros FROM campaign WHERE metrics.cost_micros > 0 AND segments.date BETWEEN '2021-11-12' AND '2022-02-10'`
this query gives me per line the costs of a campaign-date combination (I'm not interested in the campaign id, I just sum up the costs).

When using the newly introduces report parameter 
`SELECT segments.date, metrics.cost_micros FROM campaign WHERE metrics.cost_micros > 0 AND segments.date BETWEEN '2021-11-12' AND '2022-02-10' PARAMETERS omit_unselected_resource_names=true`
The costs are far to high for each date per line.  It seems like the grouping is somehow broken without the resource name. Each line returns the sum of all campaign costs for that day.

Here an example to make it more clear:
Result without parameter:
```
2022-02-10    10
2022-02-10    20
2022-02-10    15
```
Result with parameter
```
2022-02-10    45
2022-02-10    45
2022-02-10    45
```

example request ids: TLTjkx6_UiIPoN7y1xL-Cg (with `PARAMETERS omit_unselected_resource_names=true`), 7QMfkMwYyiQf9XSaDNeFtw (without parameter)

Best regards,

Christian

**Comment by jradcliff** [comment]
Hi Christian,

Thank you very much for pointing this out. I'm following up and will provide updates as soon as I have more info.

-Josh

**Comment by jradcliff** [comment]
We released a fix for this yesterday (Feb 14) afternoon and I've checked several queries to confirm their results are now correct. However, please re-open this issue if you still see issues.

Thanks again for highlighting this!

Thanks,
Josh

**Comment by schabe77** [comment]
I have been using the parameter for more than a week now and just wanted to let you know that everything is now working as expected. Thank you

**Comment by jradcliff** [comment]
Great! Thanks for confirming.
