### ISSUE TITLE
Expose Missing Required Union Field In Error Message

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#576]
com.google.api-ads:google-ads:17.0.1

Attempting to create a new ResponsiveDisplayAd, if one of the required fields of the ad_data is missing, the error message does not expose which field is the problem.

request-id=zKmpiwHTBsCVrlE8bqiZbg

```
Request
-------
MethodName: google.ads.googleads.v10.services.AdGroupAdService/MutateAdGroupAds
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=ABC, x-goog-api-client=gl-java/11.0.13 gccl/17.0.1 gapic/17.0.1 gax/2.6.1 grpc/1.41.0}
Body: customer_id: "XYZ"
operations {
  create {
    ad {
      responsive_display_ad {
```

```
Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,request-id=zKmpiwHTBsCVrlE8bqiZbg,date=Tue, 22 Feb 2022 15:15:06 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43")
Body: results {
}
partial_failure_error {
  code: 3
  message: "The required field was not present., at operations[0].create.ad.responsive_display_ad"
  details {
    type_url: "type.googleapis.com/google.ads.googleads.v10.errors.GoogleAdsFailure"
    value: "\ne\n\003\350\003\002\022#The required field was not present.\"9\022\016\n\noperations\030\000\022\b\n\006create\022\004\n\002ad\022\027\n\025responsive_display_ad"
  }
}
```

For this request it was the long_headline that was required and missing, but only through in depth debugging was that discovered as the error thrown does not indicate which required field was not present

Pete

**Comment by jradcliff** [comment]
Hi Pete,

For issues like this one that are a problem with the API and not specific to the library, please reach out to us on the forum at https://groups.google.com/g/adwords-api.

Thanks

**Comment by PeterLavetsky** [comment]
How to tell that it's not the library obfuscating the response error?

The forum is a blackhole, with poor response rate and juvenile official answers along the lines of "Did you try restarting it?"

A post like the above on the forum will garner no traction and be left by the wayside in an ongoing extremely bad look for Google.

**Comment by jradcliff** [comment]
Hi,

I'm suggesting this is an API issue because the response `message` shows the field path ends at `responsive_display_ad` instead of `responsive_display_ad.long_headline`, and the library doesn't modify that `message` field:

```
  message: "The required field was not present., at operations[0].create.ad.responsive_display_ad"
  details {
    type_url: "type.googleapis.com/google.ads.googleads.v10.errors.GoogleAdsFailure"
    value: "\ne\n\003\350\003\002\022#The required field was not present.\"9\022\016\n\noperations\030\000\022\b\n\006create\022\004\n\002ad\022\027\n\025responsive_display_ad"
  }
```

I'm sorry to hear you haven't had a good experience with the forum. However, if a bug like this is reported on the forum, it _will_ get forwarded on for further investigation.

Thanks,
Josh

**Comment by PeterLavetsky** [comment]
Thanks Josh. I posted it on the forum a couple hours ago: https://groups.google.com/g/adwords-api/c/J5iIPoktjWU

Pete

**Comment by jradcliff** [comment]
Thanks, Pete. There's a bug tracking this and we're following up. I'll close this from the library perspective since it's covered by the forum thread.

-Josh

Ref: b/221100720
