### ISSUE TITLE
Not getting Campaign Details in getAllAdgroup call

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/google-ads-java#587]
Hi Team,
   While doing getAllAdgroup API call we are not getting the campaignId as blank .We are using below code to fetch campaign details from adgroup:

com.google.ads.googleads.v9.resources.Campaign _c = campaigns.get(_ag.getCampaign()); 

Request :
google.ads.googleads.v9.services.GoogleAdsService/Search, Endpoint: [googleads.googleapis.com:443](http://googleads.googleapis.com:443/),  RequestID: qI5G7dPSjcnPoIMTkibCKQ, ResponseCode: OK, Fault: null.
query: "SELECT ad_group.type, ad_group.ad_rotation_mode, ad_group.base_ad_group, [bidding_strategy.id](http://bidding_strategy.id/), [bidding_strategy.name](http://bidding_strategy.name/), bidding_strategy.resource_name, bidding_strategy.type, ad_group.cpc_bid_micros, ad_group.cpm_bid_micros, bidding_strategy.enhanced_cpc, ad_group.final_url_suffix, [ad_group.id](http://ad_group.id/), [ad_group.name](http://ad_group.name/), ad_group.labels, ad_group.status, ad_group.effective_target_cpa_micros, ad_group.effective_target_cpa_source, bidding_strategy.target_cpa.target_cpa_micros, bidding_strategy.target_roas.target_roas, ad_group.effective_target_roas, ad_group.tracking_url_template, ad_group.url_custom_parameters, campaign.base_campaign, [campaign.id](http://campaign.id/), [campaign.name](http://campaign.name/) FROM ad_group WHERE [campaign.id](http://campaign.id/) IN (1537612735) AND ad_group.status IN (\'ENABLED\', \'PAUSED\', \'REMOVED\') ORDER BY [ad_group.id](http://ad_group.id/) ASC"
Response:
  ad_group {
    resource_name: "customers/******/adGroups/58986403656"
    status: ENABLED
    type: SEARCH_STANDARD
    ad_rotation_mode: OPTIMIZE
    id: 58986403656
    name: "One Law Group, S.C. BRANDING 1105141600"
    base_ad_group: "customers/*******/adGroups/58986403656"
    cpc_bid_micros: 5320000
    cpm_bid_micros: 10000
    effective_target_cpa_micros: 0
  }

**Comment by jradcliff** [comment]
Hi,

This appears to be an API issue that's not specific to this library. Please post to our forum at https://groups.google.com/g/adwords-api for assistance on this one.

Thanks,
Josh
