### ISSUE TITLE
Watchdog OutofMemoryError in  v17.0.1

### ISSUE THREAD

**Issue by hugochang8** [googleads/google-ads-java#588]
**Describe the bug:**

Hi team,

Since upgrading to version v17.0.1, my client has noticed the occurrence of the OutofMemoryError related to Watchdog. The error interrupted the API services and blocked responses.

My client is an agency and make hundreds of calls everyday, and they didn't have any issue before the library upgrade.  
FYI they are not using any thread on their end. 

We wonder 
1) if there is a way to turn off Watchdog, and my client will manage the API services on their end?
2) if there is any way to catch the error so that the API services are not interrupted? 

Thanks,
Hugo Chang
hugochang@

**Steps to Reproduce:**
Happens occasionally, mostly when getting customers. 

**Expected behavior:**

**Client library version and API version:**
Client library version: v17.0.1
Google Ads API version: v10.0
JDK version: 1.8

**Request/Response Logs:**
Error log:
https://drive.google.com/file/d/1eUydoMSfOSNRUlspZtlqta-sLPY6BRu3/view?usp=sharing&resourcekey=0-sNtBHxL3bW5eOierjiklhA

 
**Anything else we should know about your project / environment:**

**Comment by jradcliff** [comment]
Hi,

Could you share which version of the library they were using _previously_? Also, what are the [memory settings for the JVM](https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html) such as `-Xms` and `-Xmx`, and have they tried increasing `-Xmx`?

Thanks,
Josh

**Comment by PeterLavetsky** [comment]
We also just started seeing OOM on or after the 8th of March. Between the 8th of March and now we deployed no new code changes to the production servers and we are running into OOMs.

I've seen:

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "grpc-default-executor-49"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Gax-243"
```

Was there any backend code deployed overnight on the 10th of March and the 11th? That's when we really saw the escalation of OOM.

I don't have a lot of details at the moment as we're still trying to determine the scope of the problem. We do know that it's when fetching report data. We use search stream callable for all gets.

```
final ServerStream<SearchGoogleAdsStreamResponse> stream = googleAdsServiceClient
                        .searchStreamCallable()
                        .call( request, GrpcCallContext.createDefault().withTimeout( Duration.of( MAX_TIMEOUT_LENGTH, MAX_TIMEOUT_UNITS ) ) );
```

We have a 5m timeout on the call.

@jradcliff We issue requests for specific customerIds each request. Are you suggesting we may need to add some status to the search in order to not include inactive / test accounts in search calls that are for specific customerIds?

We give each JVM 12G. This hasn't changed.

```
-XX:+UseG1GC -Xms12G -Xmx12G
```

I'm available to test any changes if there's guidance from Google. This issue is causing us a bit of stress.

Thanks
Pete

**Comment by PeterLavetsky** [comment]
I can provide some more details on the types of queries that result in Out Of Memory exceptions.

To restate: these queries for the same customerIds worked fine a week ago.

We are able to mitigate this problem for the time being by reducing the fields requested in the queries, but it does seem that something related to the CustomerClient change has affected the amount of data returned. Or perhaps there is misconfigured join at the data retrieval level that is returning much more data than intended.

I'm not able to provide request-ids as the JVM OOMs before the the callable is complete. Lots of customerIds complete the queries fine, but many do not.

Here is an example of a query that, given a "bad" customerId, will cause an OOM on a 12G JVM:

```
select ad_group.ad_rotation_mode, ad_group.audience_setting.use_audience_grouped, ad_group.base_ad_group, ad_group.campaign, ad_group.cpc_bid_micros, ad_group.cpm_bid_micros, ad_group.cpv_bid_micros, ad_group.display_custom_bid_dimension, ad_group.effective_cpc_bid_micros, ad_group.effective_target_cpa_micros, ad_group.effective_target_cpa_source, ad_group.effective_target_roas, ad_group.effective_target_roas_source, ad_group.excluded_parent_asset_field_types, ad_group.explorer_auto_optimizer_setting.opt_in, ad_group.final_url_suffix, ad_group.id, ad_group.name, ad_group.percent_cpc_bid_micros, ad_group.resource_name, ad_group.status, ad_group.target_cpa_micros, ad_group.target_cpm_micros, ad_group.target_roas, ad_group.targeting_setting.target_restrictions, ad_group.tracking_url_template, ad_group.type, ad_group.url_custom_parameters, metrics.active_view_cpm, metrics.active_view_ctr, metrics.active_view_impressions, metrics.active_view_measurability, metrics.active_view_measurable_cost_micros, metrics.active_view_measurable_impressions, metrics.active_view_viewability, metrics.all_conversions, metrics.all_conversions_by_conversion_date, metrics.all_conversions_from_interactions_rate, metrics.all_conversions_value, metrics.all_conversions_value_by_conversion_date, metrics.average_cost, metrics.average_cpc, metrics.average_cpe, metrics.average_cpm, metrics.average_cpv, metrics.clicks, metrics.content_impression_share, metrics.content_rank_lost_impression_share, metrics.conversions, metrics.conversions_by_conversion_date, metrics.conversions_from_interactions_rate, metrics.conversions_value, metrics.conversions_value_by_conversion_date, metrics.cost_micros, metrics.cost_per_all_conversions, metrics.cost_per_conversion, metrics.cross_device_conversions, metrics.ctr, metrics.engagement_rate, metrics.engagements, metrics.impressions, metrics.interaction_event_types, metrics.interaction_rate, metrics.interactions, metrics.search_exact_match_impression_share, metrics.search_impression_share, metrics.search_rank_lost_impression_share, metrics.value_per_all_conversions, metrics.value_per_all_conversions_by_conversion_date, metrics.value_per_conversion, metrics.value_per_conversions_by_conversion_date, metrics.video_quartile_p100_rate, metrics.video_quartile_p25_rate, metrics.video_quartile_p50_rate, metrics.video_quartile_p75_rate, metrics.video_view_rate, metrics.video_views, metrics.view_through_conversions, segments.date from ad_group where segments.date   DURING   LAST_30_DAYS
```

When I change the request to below, and I keep all other values the same, I get the results back instantaneously, and I believe there were only 324 rows. 

```
select ad_group.id, metrics.conversions, metrics.cost_micros, metrics.interactions from ad_group where segments.date   DURING   LAST_30_DAYS 
```

So with 324 rows of data with the above full fields I get back many gigabytes of data.

Here is another query against a different resource that shows the same traits:

```
select keyword_view.resource_name, metrics.active_view_cpm, metrics.active_view_ctr, metrics.active_view_impressions, metrics.active_view_measurability, metrics.active_view_measurable_cost_micros, metrics.active_view_measurable_impressions, metrics.active_view_viewability, metrics.all_conversions, metrics.all_conversions_by_conversion_date, metrics.all_conversions_from_interactions_rate, metrics.all_conversions_value, metrics.all_conversions_value_by_conversion_date, metrics.average_cost, metrics.average_cpc, metrics.average_cpe, metrics.average_cpm, metrics.average_cpv, metrics.clicks, metrics.conversions, metrics.conversions_by_conversion_date, metrics.conversions_from_interactions_rate, metrics.conversions_value, metrics.conversions_value_by_conversion_date, metrics.cost_micros, metrics.cost_per_all_conversions, metrics.cost_per_conversion, metrics.cross_device_conversions, metrics.ctr, metrics.engagement_rate, metrics.engagements, metrics.impressions, metrics.interaction_event_types, metrics.interaction_rate, metrics.interactions, metrics.search_exact_match_impression_share, metrics.search_impression_share, metrics.search_rank_lost_impression_share, metrics.value_per_all_conversions, metrics.value_per_all_conversions_by_conversion_date, metrics.value_per_conversion, metrics.value_per_conversions_by_conversion_date, metrics.video_quartile_p100_rate, metrics.video_quartile_p25_rate, metrics.video_quartile_p50_rate, metrics.video_quartile_p75_rate, metrics.video_view_rate, metrics.video_views, metrics.view_through_conversions, segments.date from keyword_view where segments.date   DURING   LAST_7_DAYS 
```

To skip a hop, a customerId to try this against is 7284278505, but again, this customerId has been running the above "bad" queries for many months with no problems.

Pete

**Comment by PeterLavetsky** [comment]
One other data point ... across ALL report queries, not just those I mentioned in the last post, our historical average time for request + response was in the low 1 second range.

Starting 3/12 that time has ballooned to 3.2s and today we're seeing 2.06 so far.

I believe something has fundamentally changed in the way Google retrieves data, or to the amount of resources available to retrieve the data.

Pete

**Comment by jradcliff** [comment]
Hi Pete,

I confirmed the behavior you mentioned. Thanks for sending over the customer ID and queries -- that was incredibly helpful. In v10, I'm seeing a large number of rows where all of the `metrics.*` fields have a value of `0`, which is what is making the responses so large.

I'm following up as this may be an issue with the [zero metrics change in v10](https://developers.google.com/google-ads/api/docs/release-notes#reporting). In the meantime, as workarounds, you could do either of the following:

1. Add a condition such as `metrics.impressions > 0` to remove all the additional rows. Note that this will also remove any rows with `metrics.impressions = 0` but a non-zero value for some other metric. That should be a rare case, though.
2. Use v9 for those queries.

I'll provide an update as soon as I have more information.

Thanks,
Josh

**Comment by jradcliff** [comment]
This was fixed overnight last night, so I'll mark this closed. However, if you see any remaining issues related to this, feel free to reopen.

Thanks,
Josh
