### ISSUE TITLE
Please share the sample code for keywords containing non-alphabetic characters(-,/,",', etc.)

### ISSUE THREAD

**Issue by qiqingchao** [googleads/google-ads-java#589]
**What is your question?**
Hi,

During the process of migrating adwords to ads, I find keywords with non-alphabetic/special characters, such as built-in oven, 2-in-1 washer, 30"" cooktop, which will be set on KeywordPlanAdGroupKeyword.setText(),  - and " are removed when ads API return. (built-in oven -> built in oven, 2-in-1 washer-> 2 in 1 washer, 30"" cooktop -> 30 cooktop)
But adwords will not.
My question is, how to preserve these characters so that the input and output keywords are consistent?
I tried escape characters too.

Could you share me sample code for this? Thanks.

Br,
QC

**Comment by jradcliff** [comment]
Hi,

Could you clarify what you meant by "when Ads API return"? Are you referring to the response to the [MutateKeywordPlanAdGroupKeywords](https://developers.google.com/google-ads/api/reference/rpc/v10/KeywordPlanAdGroupKeywordService#mutatekeywordplanadgroupkeywords) request? If you could share a sample request/response with any sensitive information removed, that'd be helpful.

If the question is how to embed double quotes within the keyword text for a `KeywordPlanAdGroupKeyword`, escaping should work as shown in the `setText()` call below.

```
KeywordPlanAdGroupKeyword.newBuilder()
            .setKeywordPlanAdGroup(planAdGroupResource)
            .setCpcBidMicros(1_990_000L)
            .setMatchType(KeywordMatchType.EXACT)
            .setText("jupiter \"all day\" cruise 30\"\"");
```

The above would result in a `KeywordPlanAdGroupKeyword` with text of `jupiter "all day" cruise 30""`.

Thanks,
Josh

**Comment by jradcliff** [comment]
Hi QC,

Thanks for the examples. In the response tables that you shared, is the **keybrand** column coming from the [search_query](https://developers.google.com/google-ads/api/reference/rpc/v10/KeywordPlanKeywordHistoricalMetrics#search_query) field of each `KeywordPlanKeywordHistoricalMetrics` object returned in a [GenerateHistoricalMetricsResponse](https://developers.google.com/google-ads/api/reference/rpc/v10/GenerateHistoricalMetricsResponse)? If so, that is not guaranteed to exactly match the keywords in your plan, per the description for the `search_query` field:

> The text of the query associated with one or more ad_group_keywords in the plan.
>
> Note that we de-dupe your keywords list, eliminating close variants before returning the plan's keywords as text. For example, if your plan originally contained the keywords 'car' and 'cars', the returned search query will only contain 'cars'. Starting V5, the list of de-duped queries will be included in close_variants field.

Thanks,
Josh

**Comment by qiqingchao** [comment]
Hi Josh,

Yes. I got the keybrand column from getSearchQuery. Thanks for your answer.
So can I understand that this is the difference between ads and adwords API？
Because adwords will return the intact keywords.

Thanks,
QC

**Comment by qiqingchao** [comment]
Hi Josh,

This tip solved my issue. Thank you so much!

Br,
QC
