### ISSUE TITLE
alternative to field _productgroup_ Product Partition

### ISSUE THREAD

**Issue by garuna-m6** [googleads/google-ads-java#591]
**What is the alternative to field _productgroup_ in Product Partition**

Hi Team,
The documentation mentions column ProductGroup in Product Partition interface is deprecated 
https://developers.google.com/google-ads/api/docs/migration/mapping#product_partition
, however  I have some dependencies on this field, wanted to confirm if there is a way to fetch this property  ?

Thanks

**Comment by jradcliff** [comment]
Hi,

Since this is an API issue that's not specific to this library, please post to our API forum at https://groups.google.com/g/adwords-api instead.

Thanks,
Josh
