### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by Gracelinder85** [googleads/google-ads-java#598]
**Describe the bug:**

**Steps to Reproduce:**

**Expected behavior:**

**Client library version and API version:**
Client library version:
Google Ads API version:
JDK version:

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by jradcliff** [comment]
Hi,

I'm closing this issue since no details were provided, but feel free to reopen and add more info if you're still encountering a problem.

Thanks,
Josh
