### ISSUE TITLE
Reports: Exception when requesting keyword_view: CANCELLED: Failed to read message

### ISSUE THREAD

**Issue by sijisara-indeed** [googleads/google-ads-java#602]
Hi,
While performing a query like the following, we notice an exception like ` java.lang.OutOfMemoryError: GC overhead limit exceeded` from API side

`SELECT campaign.id,ad_group.id,ad_group_criterion.criterion_id,campaign.name,ad_group_criterion.keyword.text,ad_group_criterion.keyword.match_type,ad_group_criterion.effective_cpc_bid_micros,ad_group_criterion.final_urls FROM keyword_view WHERE ad_group.status = 'ENABLED' AND ad_group_criterion.status = 'ENABLED' AND segments.date DURING YESTERDAY AND ad_group_criterion.negative = FALSE AND campaign.id IN (<some_id>) PARAMETERS omit_unselected_resource_names=true`

We have encountered this while fetching keyword data for large accounts (containing >2M keywords). We query keyword data for 1 campaign at a time using `SearchGoogleAdsStreamRequest()` as suggested.
Stack trace: attached in file [OOM_stacktrace.txt](https://github.com/googleads/google-ads-java/files/8424153/OOM_stacktrace.txt)

**Steps to Reproduce:**
This is how we create GoogleAdsClient and GoogleAdsServiceClient -

```
    protected GoogleAdsServiceManager(final Properties properties) {
        googleAdsClient = GoogleAdsClient.newBuilder()
                .fromProperties(properties)
                .build();
    }

    protected GoogleAdsClient getGoogleAdsClient() {
        return googleAdsClient;
    }

    protected GoogleAdsServiceClient getGoogleAdsServiceClient() {
        return googleAdsClient.getVersion10().createGoogleAdsServiceClient();
    } 
```
Code snippet for querying the data:
 ```
        final List<T> reportData = new ArrayList<>();
        try (final GoogleAdsServiceClient googleAdsServiceClient = getGoogleAdsServiceClient()) {
            final String searchQuery = report.generateSearchQuery(); // this is the query string shared above

            LOG.info(String.format("Executing query: '%s' for clientId=%d", searchQuery, client.getClientId()));

            final ServerStream<SearchGoogleAdsStreamResponse> stream = googleAdsServiceClient.searchStreamCallable().call(
                SearchGoogleAdsStreamRequest.newBuilder()
                        .setQuery(searchQuery)
                        .setCustomerId(Long.toString(client.getClientId()))
                        .build());
            try {
                for (final SearchGoogleAdsStreamResponse response : stream) {
                    for (final GoogleAdsRow googleAdsRow : response.getResultsList()) {
                        final T data = report.processRow(googleAdsRow);
                        if (data != null) {
                            reportData.add(data);
                        }
                    }
                }
            } catch (final Exception e) {
                LOG.info(String.format("API exception occurred while fetching data for clientId=%d", client.getClientId()));
                LOG.info(String.format("Exception=%s", e.getMessage()));
                e.printStackTrace();
            }
        }
```

**Expected behavior:**
The query runs successfully returning the rows matching the query

**Client library version and API version:**
Client library version: google-ads-java 17.0.1
Google Ads API version: v10
JDK version: 1.8.0_302

**Request/Response Logs:**

There is no request ID in the logs. It is of the form-
`[ 2022-03-30 15:05:51,977 WARN  ] [summary] FAILURE REQUEST SUMMARY. Method: google.ads.googleads.v10.services.GoogleAdsService/SearchStream, Endpoint: googleads.googleapis.com:443, CustomerID: 2171459886, RequestID: null, ResponseCode: CANCELLED, Fault: Failed to read message..`
 
**Anything else we should know about your project / environment:**
We use Standard access developer token. Our tool runs similar queries for multiple customers in parallel. We encountered this while we are migrating from Adwords API to Google Ads API

**Comment by jradcliff** [comment]
Hi,

How much heap space are you allocating to your JVM? I see in your code sample that you are adding every row to your `reportData` collection:

```
               for (final SearchGoogleAdsStreamResponse response : stream) {
                   for (final GoogleAdsRow googleAdsRow : response.getResultsList()) {
                       final T data = report.processRow(googleAdsRow);
                       if (data != null) {
                           reportData.add(data);
                       }
                   }
               }
```

If you're fetching millions of rows, it's likely that the JVM is running out of memory because that `reportData` list is so large. The rows in the Google Ads API are larger in terms of memory vs. the AdWords API, so to handle this please try one of the following:

1. Increase the heap space you are allocating to your JVM via the `-Xmx` argument.
2. Instead of putting all of the rows in a list in memory, process the rows as they come back from the streaming response.

Thanks,
Josh, Google Ads API Team

**Comment by sijisara-indeed** [comment]
Hi Josh,
Thanks for the suggestion. This has been resolved by increasing the heap space. Went through the discussion in https://github.com/googleads/google-ads-java/issues/588 as recommended in Google Ads API forum. Was unable to comment here earlier. This query can now be closed.
