### ISSUE TITLE
firstPageCPC   issue  in Google Ads API response

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/google-ads-java#605]
We are using CampaignBidding strategy and want to set the firstPageCPC value for AdgroupCriterion using the attribute ad_group_criterion.position_estimates.first_page_cpc_micros but we have below observations:

1.first_page_cpc value is coming as 0 for adgroupVID=33258975329 and keywordId(286829866) in Ads API but in Adwords API we are getting the value as 1.2.
2.position_estimates value is null for adgroupVID=33258975329  and keywordId(13468522271) in Ads API but in Adwords API same value comes as 7.68

**Comment by jradcliff** [comment]
Hi,

I'm seeing all of the values you mentioned in responses from the Google Ads API when I run the following query:

```
SELECT 
  ad_group_criterion.keyword.text, 
  ad_group_criterion.position_estimates.first_page_cpc_micros, 
  ad_group_criterion.position_estimates.first_position_cpc_micros, 
  ad_group_criterion.criterion_id 
FROM ad_group_criterion WHERE ad_group.id = 33258975329 
  AND ad_group_criterion.criterion_id IN (286829866,13468522271)
```

If you're using a different query with the Google Ads API, please share it so I can help investigate further.

Thanks,
Josh

P.S. Going forward, for questions like this that are not specific to this particular library and are instead questions about the API, please reach out to us via the forum at https://groups.google.com/g/adwords-api.

**Comment by jradcliff** [comment]
Hi,

I'll close this issue since I haven't heard back and I think my previous reply answers your question, but please reopen with a new comment if you still have questions.

Thanks,
Josh, Google Ads API Team
