### ISSUE TITLE
 Failed ALPN negotiation

### ISSUE THREAD

**Issue by tulaycaglayan** [googleads/google-ads-java#608]
When I want to call service, I get error : 

UNAVAILABLE: Failed ALPN negotiation: Unable to find compatible protocol Channel Pipeline: [HttpProxyHandler$HttpClientCodecWrapper#0, HttpProxyHandler#0, SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]

**Comment by jradcliff** [comment]
Hi,

This is the same issue as #577 and is due to your proxy not supporting ALPN. For more information, please see [my response on #577](https://github.com/googleads/google-ads-java/issues/577#issuecomment-1049139659).

Thanks,
Josh, Google Ads API Team
