### ISSUE TITLE
Getting error "Status{code=UNAVAILABLE, description=io exception failed: Connection reset"

### ISSUE THREAD

**Issue by thanajpa** [googleads/google-ads-java#609]
We got the error for a week and Google Support API escalate to this channel. 
could you please help to investigate?

"Status{code=UNAVAILABLE, description=io exception, cause=io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset"

[v10 request logs - REDACTED.txt](https://github.com/googleads/google-ads-java/files/8476234/v10.request.logs.-.REDACTED.txt)

**Comment by jradcliff** [comment]
Hi,

The result set for that request is going to contain over 750,000 rows, so it will be extremely large. A few questions I have are:

1. I see that you get _some_ results back but then the request fails before all results are returned. How long does it take for the request to fail? Are you setting any custom timeouts when making the request?
1. Do you need to retrieve _all_ of the ads in the account? If not, please try filtering to only the ads you need. If you do need the entire set of ads, try breaking up the request into multiple requests. For example, you could batch requests by `campaign.id` by adding `campaign.id IN (a,b,c)` to the `WHERE` clause in one request, then `campaign.id IN (d,e,f)` in the next request, and so on.
1. Do you need to retrieve all of those fields for all 750,000+ ads? Reducing the list of requested fields would reduce the size of the responses, so you should only request the fields you need.

Thanks,
Josh, Google Ads API Team

**Comment by thanajpa** [comment]
We want to download all those and the fields are mandatory to download.
so please share an example of setting customer timeout.

**Comment by jradcliff** [comment]
Hi,

Could you provide an answer to my first question of how long it takes for requests to fail?

Thanks

**Comment by thanajpa** [comment]
> Hi,
> 
> Could you provide an answer to my first question of how long it takes for requests to fail?
> 
> Thanks

around 10-12 mins

**Comment by thanajpa** [comment]
> > Hi,
> > Could you provide an answer to my first question of how long it takes for requests to fail?
> > Thanks
> 
> around 10-12 mins

**Comment by jradcliff** [comment]
Hi,

We're looking into reducing these `UNAVAILABLE` errors, but in the meantime I recommend retrying with an exponential backoff policy when you encounter `UNAVAILABLE`.

You can adjust the timeout settings for your requests using the approach in our [Advanced usage guide](https://developers.google.com/google-ads/api/docs/client-libs/java/advanced-usage#timeout).

Thanks

**Comment by thanajpa** [comment]
> retrying with an exponential backoff

We're adding the retry and timeout code but didn't work. so we're trying to reduce fields and downloads per each ad type.
We still got the problem with the responsive ad.

`val context = GrpcCallContext
      .createDefault()
      .withTimeout(Duration.of(60, ChronoUnit.MINUTES))
      .withRetrySettings(
        RetrySettings
          .newBuilder()
          .setInitialRetryDelay(Duration.ofMillis(10L))
          .setMaxRetryDelay(Duration.ofSeconds(10L))
          .setRetryDelayMultiplier(1.4)
          .setMaxAttempts(10)
          .setLogicalTimeout(Duration.ofMinutes(30L))
          .build()
      )`

22/04/20 03:10:05 WARN summary: FAILURE REQUEST SUMMARY. Method: google.ads.googleads.v10.services.GoogleAdsService/SearchStream, Endpoint: googleads.googleapis.com:443, CustomerID: 8844604793, RequestID: null, ResponseCode: UNAVAILABLE, Fault: Network closed for unknown reason.
22/04/20 03:10:07 INFO detail: FAILURE REQUEST DETAIL.
Request
-------
MethodName: google.ads.googleads.v10.services.GoogleAdsService/SearchStream
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=REDACTED, x-goog-api-client=gl-java/1.8.0_281 gccl/17.0.1 gapic/17.0.1 gax/2.6.1 grpc/1.41.0}
Body: customer_id: "8844604793"
query: "\r\nSELECT\r\n  customer.id,\r\n  ad_group_ad.ad.id,\r\n  ad_group_ad.ad.type,\r\n\r\n  ad_group_ad.ad.responsive_search_ad.headlines,\r\n  ad_group_ad.ad.responsive_search_ad.descriptions,\r\n  ad_group_ad.ad.responsive_search_ad.path1,\r\n  ad_group_ad.ad.responsive_search_ad.path2,\r\n\r\n  ad_group_ad.ad.image_ad.name,\r\n  ad_group_ad.ad.image_ad.image_url,\r\n  ad_group_ad.ad.display_url,\r\n  ad_group_ad.ad.final_urls,\r\n  ad_group_ad.ad.url_custom_parameters,\r\n\r\n  ad_group.id,\r\n  campaign.id,\r\n  campaign.name,\r\n  customer.id,\r\n\r\n  ad_group_ad.status,\r\n\r\n  ad_group_ad.policy_summary.approval_status,\r\n  ad_group_ad.policy_summary.policy_topic_entries,\r\n\r\n  ad_group_ad.labels\r\nFROM ad_group_ad\r\nWHERE\r\n  campaign.status != REMOVED\r\n  AND ad_group.status != REMOVED\r\n  AND ad_group_ad.status != REMOVED\r\n  AND ad_group_ad.ad.type = RESPONSIVE_SEARCH_AD\r\nPARAMETERS omit_unselected_resource_names = true\r\n      "


Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,date=Tue, 19 Apr 2022 19:56:33 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43")
Body: results {
  customer {
    id: 8844604793
  }
  campaign {
    name: "VNM|EN|EN|Brand_026"
    id: 16634252084
  }
  ad_group {
    id: 134516265533
  }
  ad_group_ad {
    status: ENABLED
    ad {
      type: RESPONSIVE_SEARCH_AD
      responsive_search_ad {
        headlines {
          text: "{KeyWord:Agoda\302\256 Official Website}"
          asset_performance_label: PENDING
          policy_summary_info {
            review_status: REVIEWED
            approval_status: APPROVED
          }
        }
        headlines {
          text: "Online Hotel Booking"
          asset_performance_label: PENDING
          policy_summary_info {
            review_status: REVIEWED
            approval_status: APPROVED
          }
        }
        headlines {
          text: "Exclusive Hotel Deals"
          asset_performance_label: PENDING
          policy_summary_info {
            review_status: REVIEWED
            approval_status: APPROVED
          }
        }
        headlines {
         
... TRUNCATED. See README.md to configure/disable log truncation.
Failure message: null
Status: Status{code=UNAVAILABLE, description=Network closed for unknown reason, cause=null}.

**Comment by thanajpa** [comment]
I've tried to request with REST, so it's seems processing stuck and didn't throw the exception
![image](https://user-images.githubusercontent.com/11495758/164396139-d6e56533-c4ef-4606-ae23-47920ac0ae84.png)

**Comment by devchas** [comment]
@thanajpa that makes sense because this issue seems to be specifically related to grpc. In doing some research, it seems like this is most likely a network connection issue (e.g. the connection was dropped mid-stream). Per the [grpc doc](https://grpc.github.io/grpc/core/md_doc_statuscodes.html), status code `UNAVAILABLE` means that it is a retryable error, so I agree with Josh's suggestion of using exponential backoff. 

While it would be slower, especially considering the size of the result set, you could also consider using paged `search` instead of `searchStream`. While I wouldn't necessarily recommend this approach for large requests in general, it could function as a workaround if this issue persists because you can pick up your search request even with a dropped network connection using page tokens like in [this example](https://github.com/googleads/google-ads-java/blob/main/google-ads-examples/src/main/java/com/google/ads/googleads/examples/misc/NavigateSearchResultPagesCachingTokens.java).

**Comment by jradcliff** [comment]
We made several improvements to the API since this was last reported, so I'll close this issue, but please reopen with new details if you're still encountering this problem.

Thanks,
Josh, Google Ads API Team
