### ISSUE TITLE
Regarding Keyword Level  CPC BID   issue

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/google-ads-java#610]
For keywordVID=12278651 and adgroupVID =58340251814  we are  getting different values of Keyword level CPC Bid in Adwords and Ads API. 

Adwords API- **null**
code:  entry.setKeywordBid(toMoney(((CpcBid)x.getBiddingStrategyConfiguration().getBids(0)).getBid()));

Ads API -**10**
code: entry.setKeywordBid(toMoney(adGroup.getCpcBidMicros()));

**Comment by jradcliff** [comment]
Hi,

As I mentioned in your other issue #605 , for questions like this that are not specific to this particular library and are instead questions about the API, please reach out to us via the forum at https://groups.google.com/g/adwords-api.

Thanks,
Josh, Google Ads API Team
