### ISSUE TITLE
Grpc Error :  io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.

### ISSUE THREAD

**Issue by Ashirkhan857** [googleads/google-ads-java#614]
Hey, I faced the StatusRuntimeException error frequently when I ran multiple instances.I downloads campaigns against all the account_heirarchy and it failed after some times:
	at com.google.ads.googleads.v9.errors.GoogleAdsException$Factory.createException(GoogleAdsException.java:42)
 com.google.ads.googleads.v9.errors.GoogleAdsException$Factory.createException(GoogleAdsException.java:34)
 com.google.ads.googleads.lib.stubs.exceptions.BaseGoogleAdsException$Factory.createGoogleAdsException(BaseGoogleAdsException.java:105)
 com.google.ads.googleads.lib.callables.GoogleAdsExceptionTransformation.transform(GoogleAdsExceptionTransformation.java:39)
 com.google.ads.googleads.lib.stubs.callables.ExceptionTransformingServerStreamingCallable$ExceptionTransformingStreamObserver.onError(ExceptionTransformingServerStreamingCallable.java:71)
 com.google.api.gax.tracing.TracedResponseObserver.onError(TracedResponseObserver.java:103)
 com.google.api.gax.rpc.RetryingServerStreamingCallable$1.onFailure(RetryingServerStreamingCallable.java:99)
 com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
 com.google.common.util.concurrent.Futures$4.run(Futures.java:1126)
 com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
 com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
 com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
 com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:677)
 com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:200)
 com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
 com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
 com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
 com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
 com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
 com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:677)
 com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
 com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
 com.google.api.core.SettableApiFuture.setException(SettableApiFuture.java:52)
 com.google.api.gax.rpc.ServerStreamingAttemptCallable.onAttemptError(ServerStreamingAttemptCallable.java:378)
 com.google.api.gax.rpc.ServerStreamingAttemptCallable.access$600(ServerStreamingAttemptCallable.java:97)
 com.google.api.gax.rpc.ServerStreamingAttemptCallable$2.onErrorImpl(ServerStreamingAttemptCallable.java:249)
 com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
 com.google.api.gax.rpc.Watchdog$WatchdogStream.onErrorImpl(Watchdog.java:284)
 com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
 com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:84)
 com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
 com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
 io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
 io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
 io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
 com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:113)
 io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
 io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
 io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
 io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
 io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
 io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
 io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
 io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
 io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
2022/04/15 12:22:49 - User Defined Java Class.0 - 	Suppressed: java.lang.RuntimeException: Asynchronous task failed
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.

**Comment by jradcliff** [comment]
Hi,

That error is from the API, not an issue with this particular library. Please reach out to Google Ads API support on our forum at https://groups.google.com/g/adwords-api.

Thanks,
Josh
