### ISSUE TITLE
Hanging on a unary call using a custom client timeout

### ISSUE THREAD

**Issue by legiondean** [googleads/google-ads-java#616]
**The call hangs forever regardless the timeout duration setting:
                    GoogleAdsServiceClient.SearchPagedResponse response;
                        try ( GoogleAdsServiceClient googleAdsServiceClient = googleAdsClient.getLatestVersion().createGoogleAdsServiceClient() ){
                    String query = "SELECT customer_client.client_customer, customer_client.level, "
                    + "customer_client.manager, customer_client.descriptive_name, "
                    + "customer_client.currency_code, customer_client.time_zone, "
                    + "customer_client.id "
                    + "FROM customer_client "
                    + "WHERE customer_client.level <= 1 AND customer_client.status IN ('ENABLED')";

                    GoogleAdsServiceClient.SearchPagedResponse response = googleAdsServiceClient.searchPagedCallable()
                            .call(SearchGoogleAdsRequest.newBuilder()
                                    .setQuery( query )
                                    .setCustomerId( Long.toString( customerIdToSearchFrom ) )
                                    .build(),
                                    GrpcCallContext.createDefault()
                                            .withTimeout(Duration.ofMinutes(1)));
I also tried the alternative search func:
                    .search(
                            SearchGoogleAdsRequest.newBuilder()
                                    .setQuery( query )
                                    .setCustomerId( Long.toString( customerIdToSearchFrom ) )
                                    .build() );

This one timeout after an hour with:
                    _io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata_

What's interesting is that among multiple accounts we have, this timeout issue only happen on a specific one. Other accounts all look fine.
**

**Steps to Reproduce:**

**Expected behavior:**

**Client library version and API version:
**
Client library version:
Google Ads API version:
V10
JDK version:
1.8 and 11

**Request/Response Logs:
io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata

**

 
**Anything else we should know about your project / environment:**

**Comment by jradcliff** [comment]
Hi,

This is due to invalid credentials (client ID, client secret, refresh token). Please see issue #169 .

Thanks,
Josh
