### ISSUE TITLE
A GoogleAds API Call is taking long time time execute when creating a custom audience using MutateUserListsResponse in Java

### ISSUE THREAD

**Issue by dmozeli** [googleads/google-ads-java#625]
Hi,

I'm trying to create an audience based on our company CRM data (email addresses and mobile phones). The system takes forever to execute this command in Java:

Everytime I try to run the method below, it takes ~60 minutes to complete .

// Adds the user list.      MutateUserListsResponse response =          userListServiceClient.mutateUserLists(              Long.toString(customerId), ImmutableList.of(operation));  

Line 198

Note: the attached file contains the entire java class file that I'm using.

API Version: Google Ads API v18 (Java)

Thanks,

Danilo

**Comment by devchas** [comment]
Hi @dmozeli - it looks like the file you referenced wasn't attached. 

```
Note: the attached file contains the entire java class file that I'm using.
```

Would you mind providing the contents so that I can help troubleshoot?
