### ISSUE TITLE
Proxy doesn't work on docker

### ISSUE THREAD

**Issue by BrunoWood** [googleads/google-ads-java#634]
When I run locally and defend proxy with user and password:

	System.setProperty("jdk.http.auth.tunneling.disabledSchemes", "");
	System.setProperty("jdk.http.auth.proxying.disabledSchemes", "");

	System.setProperty("https.proxyHost", "<Proxy Host>");
	System.setProperty("https.proxyPort", "<Proxy port"); 
		
	and 
	
	Authenticator.setDefault(new Authenticator() {
			@Override
			protected PasswordAuthentication getPasswordAuthentication() {
				if (getRequestorType().equals(RequestorType.PROXY)) {
					return new PasswordAuthentication("<username>", "<password>".toCharArray());
				}
				return super.getPasswordAuthentication();
			}
		});
			
			
		and run 	CreateOfflineUserDataJobResponse createOfflineUserDataJobResponse =
					offlineUserDataJobServiceClient
							.createOfflineUserDataJobCallable().call(CreateOfflineUserDataJobRequest.newBuilder().setCustomerId(customerId).setJob(offlineUserDataJob)
										.build(), grpc);
										
										
	everything work fine, but when I run it with docker I am getting an error:
	Proxy returns "HTTP/1.0 407 Proxy Authentication Required"
					
	it looks like when using docker, the library ignore the Authenticator, how can I define proxy with username and password on docker and to work with the library?

**Comment by BrunoWood** [comment]
anyone?

**Comment by jradcliff** [comment]
From the stack trace, are you getting that error when the library is making a request to the OAuth endpoint or to the Google Ads API endpoint?

**Comment by BrunoWood** [comment]
Found the problem, needed to define jdk.http.auth.tunneling.disabledSchemes in the docker
thanks
