### ISSUE TITLE
loading headlines & descriptions for RSAs times out

### ISSUE THREAD

**Issue by schabe77** [googleads/google-ads-java#642]
**Describe the bug:**
See the discussion [here](https://groups.google.com/g/adwords-api/c/w4ERrRobUeA).
A short summary: When loading RSAs using searchstream in some accounts the request times out when I request headlines & descriptions within the same query. When requesting the same data with separate requests for headlines and descriptions the response is returned in an appropriate time. e.g. for my example files 
- rsa-separate-requests-loads.txt request j4ZGb13uWU3WB_rU5HJbPQ returned the headlines after 2:46min, request kLgMeHoN8vewPHSAnceT7w returned the descriptions after 0:33min.
- rsa-same-request-loads.txt timed out after 20 min
The account has quite a lot of RSAs (about 1,2 million) but the problem also occurs in some accounts that "only" have 600K RSAs.

The strange thing is that loading headline and description separately seems to absolutely no problem.

**Steps to Reproduce:**
This is difficult - I have accounts where the problem occurs, other accounts with the same structure / ad amount are not affected.

**Expected behavior:**
RSA details should be reported within a reasonable amount of time.

**Client library version and API version:**
Client library version: 19.0.0 (but also with previous versions)
Google Ads API version: v11 (but also with previous versions)
JDK version: 11

**Request/Response Logs:**

[rsa-separate-requests-loads.txt](https://github.com/googleads/google-ads-java/files/8978705/rsa-separate-requests-loads.txt)
[rsa-same-request-loads.txt](https://github.com/googleads/google-ads-java/files/8978720/rsa-same-request-loads.txt)

 
**Anything else we should know about your project / environment:**
Some context: I  would have expected it to be a backend problem. That's why I participated in the discussion at 
https://groups.google.com/g/adwords-api/c/w4ERrRobUeA After I sent my logs I got the response "It seems that this is probably a client library issue. Can you please try reaching out to the client library owners and provide the logs on your client library forum post?"

**Comment by jradcliff** [comment]
Hi,

I saw from our logs that all of your `searchStream` requests using this library have a timeout of 1,200,000 milliseconds (20 minutes), and a significant % of them are failing because the request takes longer than that. Are you [reducing the timeout](https://developers.google.com/google-ads/api/docs/client-libs/java/advanced-usage#timeout) to lower than the default?

Thanks,
Josh

**Comment by schabe77** [comment]
Hi Josh,

short answer: yes, I set the timeout to 20 minutes: 
`serviceClient.searchStreamCallable().call(request, GrpcCallContext.createDefault().withTimeout(READ_TIMEOUT))`

An explanation: I use the adwords/ads API for almost 12 years now and (apart from obvious server problems) I _never_ had problems with the default timeouts. But after switching to the new ads API some things took longer than before, e.g. the Keyword Parameters sometimes just got stuck. That blocked all my processes - so I decided to set a timeout a normal operation should never reach: 20 minutes. I can't remember any request taking longer than 3-5minutes in the past, so 20 was a real huge step. And even for the RSA requests I got responses within 3 minutes - when using the old API or when using the the new API and splitting the request to load headlines/descriptions separately.

This massive increase of loading time made me suspect that it was a bug. I thought of exponential running time e.g. because of doing a lookup on a List instead of a Set. And after I saw someone having the same problem at google groups I thought this should be something someone should have a look on.

**Comment by jradcliff** [comment]
Hi @schabe77 ,

Have you already reported this on our API product support channel via the [forum](https://groups.google.com/g/adwords-api) or the API support email address? If so, could you share the subject line of that post so we can follow up over there? If not, please send it to the forum or the support email address and share the subject line. That way, either I or one of my teammates can follow up with you over email and get more details.

This issues list should be used for issues with the library, and what you've described is a concern about a change in API behavior, not a change in the library.

Thanks,
Josh

**Comment by schabe77** [comment]
Hi @jradcliff ,

as I wrote in the initial comment of the issue I already posted it (or took part in the discussion) at [google groups](https://groups.google.com/g/adwords-api/c/w4ERrRobUeA), Subject "Deadline Exceeded when fetching ads since 4/6", "ref:_00D1U1174p._5004Q2ZLKsd:ref". From there I was redirected here. As I already wrote: "After I sent my logs I got the response 'It seems that this is probably a client library issue. Can you please try reaching out to the client library owners and provide the logs on your client library forum post?'"

**Comment by jradcliff** [comment]
Apologies for missing those details, @schabe77 . I'll close this since it's not library-specific, but I'll follow up today with you on that support email thread.

Thanks,
Josh, Google Ads API Team
