### ISSUE TITLE
request-specific errors as partial failure.

### ISSUE THREAD

**Issue by schabe77** [googleads/google-ads-java#644]
Hi!

I have noticed that lately request-specific errors are often returned as partial failures.

For instance request: ZfwbD3blgeloMzlf3lk_6w - I tried to delete 2000 adgroups. instead of returning an ApiExceptions with Code RESOURCE_EXHAUSTED, I get 2000 partial failures, all containing "Too many requests. Retry in 30 seconds". 
I also recognized this behaviour with another error that (in my opinion) should not be task, but request-specific: "OperationAccessDeniedError.UPDATE_OPERATION_NOT_PERMITTED: Unauthorized".

I wanted to ask if this is intentional. As far as I remember these kind of errors have been request specific in the past - and this is how my software currently handles this errors.

**Comment by jradcliff** [comment]
Hi,

Please post questions like this that are not specific to this library on the [forum](https://groups.google.com/g/adwords-api). The library's issues list should be used for issues with this library.

Thanks,
Josh
