### ISSUE TITLE
How to set a file name when adding members to customer list

### ISSUE THREAD

**Issue by BrunoWood** [googleads/google-ads-java#646]
Hi,
I am following the link:
 https://developers.google.com/google-ads/api/docs/samples/add-customer-match-user-list
For creating a customer list and adding members to this customer list.
The default name that is set for this file in the Segment members of the list in the ui is:"uploaded_using_api", 
Can I set a different name when adding audience members to customer list  via the java api?

**Comment by jradcliff** [comment]
Hi,

The API doesn't currently support setting that *Segment members* value. Instead, you can query the jobs that uploaded to a user list with a query such as this:

```
SELECT 
  customer.id, 
  user_list.id, 
  user_list.name, 
  offline_user_data_job.id, 
  offline_user_data_job.status 
FROM offline_user_data_job 
WHERE 
  user_list.id = <insert user list ID here>
```

Thanks,
Josh, Google Ads API Team
