### ISSUE TITLE
collection_size_error: TOO_MANY

### ISSUE THREAD

**Issue by mrnastik** [googleads/google-ads-java#648]
On trying to upload a user to google ads API I am getting the error as collection_size_error: TOO_MANY. I am using the following code snippet to upload users to the audience created in google ads API.

Set<String> userList;  //userList contains the hashed email of the user that i want to upload to the audience

    List<UserDataOperation> userDataOperations = new ArrayList<>(userList.size());

    for (String user : userList) {
      UserDataOperation userDataOperationEmail = UserDataOperation.newBuilder().setCreate(
          UserData.newBuilder()
              .addUserIdentifiers(UserIdentifier.newBuilder().setHashedEmail(user).build())
              .build()).build();
      userDataOperations.add(userDataOperationEmail);
    }
    
    UploadUserDataRequest.Builder uploadUserDataRequest =
        UploadUserDataRequest.newBuilder().setCustomerId(clientCustomerId)
            .setCustomerMatchUserListMetadata(
                CustomerMatchUserListMetadata.newBuilder().setUserList(resourceName).build());
    
    uploadUserDataRequest.addAllOperations(userDataOperations);
    
    try (UserDataServiceClient userDataServiceClient = googleAdsClient.getLatestVersion()
        .createUserDataServiceClient()) {
      response = userDataServiceClient.uploadUserData(uploadUserDataRequest.build());
    }

**Comment by jradcliff** [comment]
Hi,

There's a limit of 100,000 total `user_identifiers` per request, across all `UserData` objects in the request.

https://developers.google.com/google-ads/api/docs/remarketing/audience-types/customer-match#customer_match_considerations

If your `userList` collection has more than 100,000 identifiers, you'll need to send multiple requests.

Going forward, for API questions like this that aren't specific to this library, please post them to the forum at https://groups.google.com/g/adwords-api.

Thanks,
Josh, Google Ads API Team

**Comment by mrnastik** [comment]
Hi,
What I have observed is that if my userList contain more then 10 values than I get this error.

**Comment by mrnastik** [comment]
Hi, this is the request-id WyC08rFa2ZA54ttSHfENGQ

**Comment by jradcliff** [comment]
Thanks. I took a look at that request, and it contained over 11,000 operations in the [`operations[]`](https://developers.google.com/google-ads/api/reference/rpc/v11/AddOfflineUserDataJobOperationsRequest#operations[]) collection. Mutate requests in the API have a limit of 10,000 operations per request unless otherwise noted in our [API Limits and Quotas guide](https://developers.google.com/google-ads/api/docs/best-practices/quotas). This applies to the `AddOfflineUserDataJobOperationsRequest`, along with the limit I mentioned previously.

**Comment by mrnastik** [comment]
Hi,
 Thanks for clarifying this. However, I am using the UserDataServiceClient
service to upload users to the audience, and as per documentation(
https://developers.google.com/google-ads/api/docs/migration/user-data-service
),The UserDataService
<https://developers.google.com/google-ads/api/reference/rpc/v11/UserDataService>
has
a limit of 10 operations and 100 user IDs per request.
1)then how does the request contain over 11000 operations?
2) When you say that the request contained over 11,000 operations, does
that mean the request contained more than 11000  user identifiers?

please find the code snippet below that I am using

Set<String> userList; //userList contains the hashed email of the user that
i want to upload to the audience
List<UserDataOperation> userDataOperations = new
ArrayList<>(userList.size());

for (String user : userList) {
  UserDataOperation userDataOperationEmail =
UserDataOperation.newBuilder().setCreate(
      UserData.newBuilder()

.addUserIdentifiers(UserIdentifier.newBuilder().setHashedEmail(user).build())
          .build()).build();
  userDataOperations.add(userDataOperationEmail);
}

UploadUserDataRequest.Builder uploadUserDataRequest =
    UploadUserDataRequest.newBuilder().setCustomerId(clientCustomerId)
        .setCustomerMatchUserListMetadata(

CustomerMatchUserListMetadata.newBuilder().setUserList(resourceName).build());

uploadUserDataRequest.addAllOperations(userDataOperations);

try (UserDataServiceClient userDataServiceClient =
googleAdsClient.getLatestVersion()
    .createUserDataServiceClient()) {
  response =
userDataServiceClient.uploadUserData(uploadUserDataRequest.build());
}
Thanks

**Comment by mrnastik** [comment]
Thanks Josh

**Comment by mrnastik** [comment]
Understood, thanks Josh

**Comment by mrnastik** [comment]
Hi, 
Even if there are only 11 user IDs(hashed mobile numbers) in the request that I make, still I am getting the same error.
request_id: "eCfoQ7U3KmWaVn559u5Kyw"

**Comment by mrnastik** [comment]
logs
uploadUserDataRequest customer_id: "<customerid>"
customer_match_user_list_metadata {
  user_list: "customers/<customerid>/userLists/<userList>"
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "00c1ffa2c444c8a50d1e2b3fa85da987215ea93504307bf274fc359ffeef1d"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "00ab8a90f64a7831480dd2b1bd8fa6d533f6c65bd29489d5c19ce6840eedac"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "0038c2d4c6d138f0971fa0abdcb9dc36e888bd41455b4c1d76908233224ae4"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "006d436b75e7427335692acd682ed41c3a155e759bf1dbbc460e8b96c1043"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "00182ff0d1d58dd6aa5bb582fd9451241249f32df089c37ceeb7a2f26ef92"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "008dfcb859cf201bbcf9506e34793fd6f826fa11a688c7e13e81aeef55d41"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "fff53759f1963c6537cf0b127ef72a6ec41abc137b5e360a13b1220cc443"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "000a4fbdac73ee09787d0e51795c32ae6b2f6e977040680f046330a2748aa0"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "00a7b26ac46b5936cfbadb5a39a65e3747163bf58fc8a54756a7d36ef1c107"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "01285fbddaf01ed394ab82b33927e81a6c077bffea2f63e308be4f4bdcf8ba"
    }
  }
}
operations {
  create {
    user_identifiers {
      hashed_phone_number: "014174b4840651407d79d0989dced5b0a309dd55b0069d0fe55bb9a2ff9905"
    }
  }
}

 errors {
  error_code {
    collection_size_error: TOO_MANY
  }
  message: "Too many."
  location {
    field_path_elements {
      field_name: "operations"
    }
  }
}
request_id: "fxFRqgy0SjqEkbhFpRTVzw"

Result errors {  error_code {    collection_size_error: TOO_MANY  }  message: "Too many."  location {    field_path_elements {      field_name: "operations"    }  }}request_id: "fxFRqgy0SjqEkbhFpRTVzw"
0

**Comment by jradcliff** [comment]
Hi,

The `uploadUserData` method supports at most `10` items in the [`operations` field](https://developers.google.com/google-ads/api/reference/rpc/v11/UploadUserDataRequest#operations[]), as it is meant for small, incremental changes to your user list. If you need to upload larger amounts of data, you can either:

1. Use an `OfflineUserDataJob` as shown in our [guide](https://developers.google.com/google-ads/api/docs/remarketing/audience-types/customer-match) and [code example](https://developers.google.com/google-ads/api/docs/samples/add-customer-match-user-list). This is the recommended approach if you have a large number of operations.
2. Break up your request into multiple requests containing at most 10 operations each. However, if you're uploading thousands of operations, this would not be efficient.

Thanks,
Josh, Google Ads API Team

**Comment by mrnastik** [comment]
Hi,
How many calls can we make in one minute to google ads api if we are using "uploadUserData"  method to upload data?
Thanks

**Comment by jradcliff** [comment]
Hi,

We don't have specific request/minute limits I can share, but the [API Limits and Quotas page](https://developers.google.com/google-ads/api/docs/best-practices/quotas) explains how limits work in the API, and the [Rate Limits guide](https://developers.google.com/google-ads/api/docs/best-practices/rate-limits) contains information on how you can mitigate and handle rate limits.

Thanks,
Josh
