### ISSUE TITLE
The document page cannot be opened

### ISSUE THREAD

**Issue by wuconggg** [googleads/google-ads-java#652]
The document page cannot be opened

**Comment by jradcliff** [comment]
Hi,

Could you clarify which page you're referring to? Is it the documentation page https://developers.google.com/google-ads/api/docs/client-libs/java, linked from https://github.com/googleads/google-ads-java#documentation? That one is accessible when I tried it, even in an incognito window.

Thanks,
Josh

**Comment by wuconggg** [comment]
![image](https://user-images.githubusercontent.com/22870974/180114062-f0ad1921-b23e-46a0-8c94-5f15f5112c0b.png)
I couldn't open it yesterday, but suddenly it works again today
