### ISSUE TITLE
Example on Smart Shopping ads issue

### ISSUE THREAD

**Issue by agustinscigliano** [googleads/google-ads-java#66]
I am having a problem with the example shown in the smart shopping ads. In the doc it says that "[Bidding Strategy must be set directly on the campaign](https://github.com/googleads/google-ads-java/blob/master/google-ads-examples/src/main/java/com/google/ads/googleads/examples/shoppingads/AddShoppingSmartAd.java#L246)" , but it is not set there. 

When I try to run this example I am having this errors:

```
Request ID tAGY_PKNVPO_HqD2q2ZOgg failed due to GoogleAdsException. Underlying errors:
  Error 0: error_code {
  field_error: REQUIRED
}
message: "The required field was not present in the resource."
trigger {
  string_value: ""
}
location {
  field_path_elements {
    field_name: "operations"
    index {
    }
  }
  field_path_elements {
    field_name: "create"
  }
  field_path_elements {
    field_name: "campaign_bidding_strategy"
  }
}

  Error 1: error_code {
  mutate_error: RESOURCE_NOT_FOUND
}
message: "Resource was not found."
trigger {
  string_value: "131646244"
}
location {
  field_path_elements {
    field_name: "operations"
    index {
    }
  }
  field_path_elements {
    field_name: "create"
  }
  field_path_elements {
    field_name: "shopping_setting"
  }
  field_path_elements {
    field_name: "merchant_id"
  }
}

```
I tried setting the biddingStrategyType, but it did not work and looking in the source code, it seems to be something different than biddingStrategy. 

I am not sure what the other error is btw.

Thanks for the help!

**Comment by nwbirnie** [comment]
The error message shows you have two errors. 

The first is that a bidding strategy must be set on the campaign. The bidding_strategy_type field is read-only ([docs](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.resources#google.ads.googleads.v1.resources.Campaign)). To set campaign_bidding_strategy refer to the ([docs](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.resources#google.ads.googleads.v1.resources.Campaign), same link as above, scroll down to campaign_bidding_strategy) which shows that campaign_bidding_strategy is a union field, and one of the the available options should be set. The example uses maximise conversion value.

Additionally, the merchant center ID you have specified is not found. Please link the merchant center account to Google Ads and try again. You can view the linked account IDs in the Google Ads UI under tools -> linked accounts.
