### ISSUE TITLE
Futures 

### ISSUE THREAD

**Issue by Azii643** [googleads/google-ads-java#661]
https://github.com/googleads/google-ads-java/blob/4816ddcef5a697e1df4afc5b1e1da8c55d6c7cef/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/AddLogicalUserList.java#L108-L154

**Comment by jradcliff** [comment]
Hi,

Could you add some more info to this issue so we can help out?

Thanks,
Josh, Google Ads API Team

**Comment by jradcliff** [comment]
Hi,

I'm closing this since it's unclear what the issue is, but feel free to add more details and then reopen it.

Thanks
