### ISSUE TITLE
com.google.api-ads:google-ads:21.0.0 is not available on Maven Central

### ISSUE THREAD

**Issue by quangkevin** [googleads/google-ads-java#670]
Could you confirm the latest library 21.0.0  is uploaded to Maven Central?

The latest file I can find there is 20.0.0.

Source: https://search.maven.org/artifact/com.google.api-ads/google-ads

**Comment by quangkevin** [comment]
Found the library: https://repo.maven.apache.org/maven2/com/google/api-ads/google-ads/

**Comment by jradcliff** [comment]
Hi,

Yep, we published the library a little over an hour ago, but it looks like there's a slight delay to the results in that search page you mentioned.

Thanks,
Josh, Google Ads API Team
