### ISSUE TITLE
Monitoring SearhStreamCallable response time

### ISSUE THREAD

**Issue by SarahBender** [googleads/google-ads-java#672]
Hi,

I use `serviceClient.searchStreamCallable.call(request, apiCallContext)` to fetch large sets of data.
I'm wondering if there's any way to measure the time spent on each iteration step especially google API response time (for initial stream and for each additional call) 

I saw docs regarding customizing gRPC interceptors and I found this particular one: MetricCollectingClientInterceptor - not even sure it's what I need but the name sounds right.

Could you please help direct me how to implement such functionality in my code that uses the following service, perhaps setting the context \ service client etc.
Or let me know if there's another way to time the calls.

Thanks,
Sarah

**Comment by jradcliff** [comment]
Hi Sarah,

Are you looking to do this on an ongoing basis or just for a one-off analysis? If the latter, you could add your timing calls within  the canonical streaming call below in the step I commented with `// TIMING_HERE`:

```
      // Creates and issues a search Google Ads stream request that will retrieve all of the
      // requested field values for the keyword.
      ServerStream<SearchGoogleAdsStreamResponse> stream =
          googleAdsServiceClient.searchStreamCallable().call(request);

      // Iterates through the results in the stream response and prints all of the requested
      // field values for the keyword in each row.
      long rows = 0;
      for (SearchGoogleAdsStreamResponse response : stream) {
        //
        // TIMING_HERE
        //
        for (GoogleAdsRow googleAdsRow : response.getResultsList()) {
           // ...process rows from response
```

The `TIMING_HERE` code will be executed each time the streaming call returns a batch of rows. Usually the API returns a separate `SearchGoogleAdsStreamResponse` for every 10,000 `GoogleAdsRow` objects, although that is an implementation detail that's subject to change.

If you're looking for a more systemic way to add this timing, I'd caution against implementing your own `ClientInterceptor`, as that would require you implementing a large portion of what's covered by `GoogleAdsClient.createGoogleAdsServiceClient()`.

However, you could wrap the iterator returned by the search stream callable to add some timing calls as follows.

```
      // Creates and issues a search Google Ads stream request that will retrieve all of the
      // requested field values for the keyword.
      ServerStream<SearchGoogleAdsStreamResponse> stream =
          googleAdsServiceClient.searchStreamCallable().call(request);

      // Gets the iterator from the ServerStream.
      Iterator<SearchGoogleAdsStreamResponse> responseIterator = stream.iterator();

      // Wraps the iterator from the ServerStream in an iterator that adds timing, then delegates
      // to the iterator from the ServerStream.
      Iterator<SearchGoogleAdsStreamResponse> wrapperIterator = new Iterator<SearchGoogleAdsStreamResponse>() {
        @Override
        public boolean hasNext() {
          return responseIterator.hasNext();
        }

        @Override
        public SearchGoogleAdsStreamResponse next() {
          // TIMING_HERE
          System.out.printf("Response at: %s%n", System.currentTimeMillis());
          return responseIterator.next();
        }
      };

      // Iterates through the results in the stream response and prints all of the requested
      // field values for the keyword in each row.
      long rows = 0;
      while (wrapperIterator.hasNext()) {
        SearchGoogleAdsStreamResponse response = wrapperIterator.next();
        for (GoogleAdsRow googleAdsRow : response.getResultsList()) {
            // process rows as usual
        }
      }
```

The code above defines the `wrapperIterator` inline, but you could move this to a class for easier reuse.

Please let me know if the above addresses what you need for your use case.

Thanks,
Josh, Google Ads API Team

**Comment by SarahBender** [comment]
I'll try wrapping the iterator suggestion.
Thanks!!
