### ISSUE TITLE
Our JVM crashes when running google-ads-java v22 in alpine linux 3.15 in docker

### ISSUE THREAD

**Issue by lanhungpham** [googleads/google-ads-java#681]
We were running the previous google-ads-java v17.0.1 without issue, but got this issue after upgraded to v22.0.0 

Below is the output we got from the crash.

Command Line: -Xms512m -Xmx1536m -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=256m -XX:MaxHeapFreeRatio=50 -XX:ErrorFile=/webreach/data/operations/coredump/hs_err1 -agentlib:jdwp=transport=dt_socket,address=6006,server=y,suspend=n -DAPPENV=dev -DCONTEXT_PATH=/cbt-estimator-api -DCBT_RETRIEVE_ESTIMATE_QUEUE=cbt-retrieve-estimate-queue-dev -DINGRESS_PATH= -DDATA_SOURCE=jdbc:postgresql://samidevdb.hibu.int:5432/samidev?autoReconnect=true /srv/apps_dir/estimatorapi/latest/package/cbt-estimator-api.jar

Host: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz, 16 cores, 3G, Alpine Linux v3.15
Time: Wed Dec 28 13:35:39 2022 EST elapsed time: 225.023858 seconds (0d 0h 3m 45s)

---------------  T H R E A D  ---------------

Current thread (0x00007f2fb7808800):  JavaThread "pool-2-thread-1" [_thread_in_native, id=93, stack(0x00007f2fb107b000,0x00007f2fb117baa8)]

Stack: [0x00007f2fb107b000,0x00007f2fb117baa8],  sp=0x00007f2fb1176598,  free space=1005k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x0000000000003fd6
C  [libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6416580247434147138861.so+0xbd07]  netty_jni_util_JNI_OnLoad+0x67
C  [libjava.so+0xfc8d]  Java_java_lang_ClassLoader_00024NativeLibrary_load0+0xbd
j  java.lang.ClassLoader$NativeLibrary.load0(Ljava/lang/String;ZZ)Z+0 java.base@11.0.15
j  java.lang.ClassLoader$NativeLibrary.load()Z+56 java.base@11.0.15
j  java.lang.ClassLoader$NativeLibrary.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)Z+216 java.base@11.0.15
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+46 java.base@11.0.15
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+70 java.base@11.0.15
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57 java.base@11.0.15
j  java.lang.System.load(Ljava/lang/String;)V+7 java.base@11.0.15
j  io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(Ljava/lang/String;Z)V+5
v  ~StubRoutines::call_stub
V  [libjvm.so+0x830aae]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.lang.ClassLoader$NativeLibrary.load0(Ljava/lang/String;ZZ)Z+0 java.base@11.0.15
j  java.lang.ClassLoader$NativeLibrary.load()Z+56 java.base@11.0.15
j  java.lang.ClassLoader$NativeLibrary.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)Z+216 java.base@11.0.15
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+46 java.base@11.0.15
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+70 java.base@11.0.15
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57 java.base@11.0.15
j  java.lang.System.load(Ljava/lang/String;)V+7 java.base@11.0.15
j  io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(Ljava/lang/String;Z)V+5
v  ~StubRoutines::call_stub
J 2787  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.15 (0 bytes) @ 0x00007f2fc8f407b7 [0x00007f2fc8f40740+0x0000000000000077]
J 2786 c1 jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.15 (104 bytes) @ 0x00007f2fc1dd3364 [0x00007f2fc1dd2fc0+0x00000000000003a4]
J 3405 c2 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.15 (10 bytes) @ 0x00007f2fc8fa0370 [0x00007f2fc8fa0320+0x0000000000000050]
J 8818 c1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.15 (65 bytes) @ 0x00007f2fc285de64 [0x00007f2fc285db20+0x0000000000000344]
j  io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run()Ljava/lang/Object;+53
v  ~StubRoutines::call_stub
J 1994  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object; java.base@11.0.15 (0 bytes) @ 0x00007f2fc8ee668f [0x00007f2fc8ee6640+0x000000000000004f]
j  io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(Ljava/lang/Class;Ljava/lang/String;Z)V+10
j  io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(Ljava/lang/ClassLoader;Ljava/lang/String;Z)V+15
j  io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(Ljava/lang/String;Ljava/lang/ClassLoader;)V+359
j  io.grpc.netty.shaded.io.netty.channel.epoll.Native.loadNativeLibrary()V+60
j  io.grpc.netty.shaded.io.netty.channel.epoll.Native.<clinit>()V+76
v  ~StubRoutines::call_stub
j  io.grpc.netty.shaded.io.netty.channel.epoll.Epoll.<clinit>()V+28
v  ~StubRoutines::call_stub
J 1184  java.lang.Class.forName0(Ljava/lang/String;ZLjava/lang/ClassLoader;Ljava/lang/Class;)Ljava/lang/Class; java.base@11.0.15 (0 bytes) @ 0x00007f2fc8e9bbba [0x00007f2fc8e9bb40+0x000000000000007a]
J 2473 c1 java.lang.Class.forName(Ljava/lang/String;)Ljava/lang/Class; java.base@11.0.15 (15 bytes) @ 0x00007f2fc1d4065c [0x00007f2fc1d405e0+0x000000000000007c]
j  io.grpc.netty.shaded.io.grpc.netty.Utils.isEpollAvailable()Z+3
j  io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>()V+144
v  ~StubRoutines::call_stub
j  io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>()V+16
v  ~StubRoutines::call_stub
j  io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(Ljava/lang/String;I)Lio/grpc/netty/shaded/io/grpc/netty/NettyChannelBuilder;+2
j  io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(Ljava/lang/String;I)Lio/grpc/ManagedChannelBuilder;+3
j  io.grpc.ManagedChannelBuilder.forAddress(Ljava/lang/String;I)Lio/grpc/ManagedChannelBuilder;+5
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel()Lio/grpc/ManagedChannel;+270
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1900(Lcom/google/api/gax/grpc/InstantiatingGrpcChannelProvider;)Lio/grpc/ManagedChannel;+1
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel()Lio/grpc/ManagedChannel;+4
j  com.google.api.gax.grpc.ChannelPool.<init>(Lcom/google/api/gax/grpc/ChannelFactory;ILjava/util/concurrent/ScheduledExecutorService;)V+68
j  com.google.api.gax.grpc.ChannelPool.create(ILcom/google/api/gax/grpc/ChannelFactory;)Lcom/google/api/gax/grpc/ChannelPool;+7
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel()Lcom/google/api/gax/rpc/TransportChannel;+45
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel()Lcom/google/api/gax/rpc/TransportChannel;+35
j  com.google.api.gax.rpc.ClientContext.create(Lcom/google/api/gax/rpc/StubSettings;)Lcom/google/api/gax/rpc/ClientContext;+179
j  com.google.ads.googleads.v12.services.stub.GrpcGoogleAdsServiceStub.create(Lcom/google/ads/googleads/v12/services/stub/GoogleAdsServiceStubSettings;)Lcom/google/ads/googleads/v12/services/stub/GrpcGoogleAdsServiceStub;+6
j  com.google.ads.googleads.v12.services.stub.GoogleAdsServiceStubSettings.createStub()Lcom/google/ads/googleads/v12/services/stub/GoogleAdsServiceStub;+19
j  com.google.ads.googleads.v12.services.GoogleAdsServiceClient.<init>(Lcom/google/ads/googleads/v12/services/GoogleAdsServiceSettings;)V+17
j  com.google.ads.googleads.v12.services.GoogleAdsServiceClient.create(Lcom/google/ads/googleads/v12/services/GoogleAdsServiceSettings;)Lcom/google/ads/googleads/v12/services/GoogleAdsServiceClient;+5
j  com.google.ads.googleads.lib.catalog.GeneratedCatalog$V12Client.createGoogleAdsServiceClient()Lcom/google/ads/googleads/v12/services/GoogleAdsServiceClient;+31
j  com.hibu.tpe.estimator.service.googleads.KeywordPlanServiceProxy.generateForecastMetrics(Ljava/lang/Long;Ljava/lang/Long;Ljava/util/List;Ljava/util/List;Ljava/util/List;)Ljava/util/Map;+12
j  com.hibu.tpe.estimator.service.googleads.TrafficEstimatorDelegate.getGoogleKeywordPlanEstimate([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Ljava/math/BigDecimal;Ljava/lang/Integer;)Ljava/util/Map;+215
j  com.hibu.tpe.estimator.service.googleads.TrafficEstimatorDelegate.getGoogleAdsKeywordPlanEstimate([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Ljava/math/BigDecimal;Ljava/lang/Integer;)[Lcom/hibu/tpe/estimator/common/KeywordEstimate;+8
j  com.hibu.tpe.estimator.service.googleads.TrafficEstimatorDelegate.lambda$calculate$1([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Ljava/math/BigDecimal;Ljava/lang/Integer;)[Lcom/hibu/tpe/estimator/common/KeywordEstimate;+8
j  com.hibu.tpe.estimator.service.googleads.TrafficEstimatorDelegate$$Lambda$1525.get()Ljava/lang/Object;+24
j  java.util.concurrent.CompletableFuture$AsyncSupply.run()V+37 java.base@11.0.15
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+92 java.base@11.0.15
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@11.0.15
j  java.lang.Thread.run()V+11 java.base@11.0.15
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000003fd6

**Comment by jradcliff** [comment]
Hi,

Have you tried increasing your memory allocation settings? It appears that failure is occurring during class loading.

Thanks,
Josh, Google Ads API Team

**Comment by AQS-DTheuke** [comment]
I don't know whether this is related, but I ran into a very similar issue: https://github.com/grpc/grpc-java/issues/10096

Workaround: Downgrade grpc-java to 1.53.0 (below 1.54.0)
The issue will likely be fixed in 1.56.0 https://github.com/grpc/grpc-java/issues/10096#issuecomment-1521958350

For me the google-cloud dependency management caused the gax-grpc dependency to be bumped to 2.25.0 which uses the affected grpc-java version.
