### ISSUE TITLE
java.lang.NoSuchFieldError: EPOLL_DOMAIN_CLIENT_CHANNEL_TYPE

### ISSUE THREAD

**Issue by huan-ds** [googleads/google-ads-java#683]
**Describe the bug:**
We are currently deploying Google Ads v12 and facing an issue. The error msg looks like this:

 ```
    [junit] EPOLL_DOMAIN_CLIENT_CHANNEL_TYPE
    [junit] java.lang.NoSuchFieldError: EPOLL_DOMAIN_CLIENT_CHANNEL_TYPE
    [junit]     at io.grpc.netty.shaded.io.grpc.netty.UdsNettyChannelProvider.isAvailable(UdsNettyChannelProvider.java:34)
    [junit]     at io.grpc.ManagedChannelRegistry$ManagedChannelPriorityAccessor.isAvailable(ManagedChannelRegistry.java:172)
    [junit]     at io.grpc.ManagedChannelRegistry$ManagedChannelPriorityAccessor.isAvailable(ManagedChannelRegistry.java:168)
    [junit]     at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:68)
    [junit]     at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:96)
    [junit]     at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41)
    [junit]     at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
    [junit]     at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:366)
    [junit]     at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1900(InstantiatingGrpcChannelProvider.java:85)
    [junit]     at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:246)
    [junit]     at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:149)
    [junit]     at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:96)
    [junit]     at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:256)
    [junit]     at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:234)
    [junit]     at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:205)
    [junit]     at com.google.ads.googleads.v12.services.stub.GrpcGoogleAdsServiceStub.create(GrpcGoogleAdsServiceStub.java:96)
    [junit]     at com.google.ads.googleads.v12.services.stub.GoogleAdsServiceStubSettings.createStub(GoogleAdsServiceStubSettings.java:186)
    [junit]     at com.google.ads.googleads.v12.services.GoogleAdsServiceClient.<init>(GoogleAdsServiceClient.java:150)
    [junit]     at com.google.ads.googleads.v12.services.GoogleAdsServiceClient.create(GoogleAdsServiceClient.java:132)
    [junit]     at com.google.ads.googleads.lib.catalog.GeneratedCatalog$V12Client.createGoogleAdsServiceClient(GeneratedCatalog.java:4458)
```

The error is throw by grpc-netty-shaded(1.50.x):
https://github.com/grpc/grpc-java/blob/v1.50.x/netty/src/main/java/io/grpc/netty/UdsNettyChannelProvider.java#L33

 

The code did not pick up the Utils class in the same package grpc-netty-shaded(1.50.x): https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/Utils.java#L108.

 
Instead, it is using the Utils class in google-ads-shadowjar-22.x package, where the code is missing EPOLL_DOMAIN_CLIENT_CHANNEL_TYPE variable. It might be a defect in google-ads-shadowjar-22.x.

**Client library version and API version:**
- Google Ads maven library version 22.0.0 (com.google.api-ads:google-ads)
- Google Ads API v12
- grpc-netty-shaded 1.50.x

**Comment by huan-ds** [comment]
Hi, we don't use Maven or Gradle so we are not able to run the Maven or Gradle command. 

I downloaded the dependencies from our project. Please check the attached file:

[DependecyFile.zip](https://github.com/googleads/google-ads-java/files/10347084/DependecyFile.zip)


Thank you,
Huan

**Comment by jradcliff** [comment]
Hi,

Thanks for sharing that info. I see there are a number of `1.x` grpc dependencies in addition to the `1.50.x` dependencies. Do you know which versions those represent?

```
Maven-io-grpc_grpc-context-1.x
Maven-io-grpc_grpc-core-1.x
Maven-io-grpc_grpc-netty-shaded-1.x
```

If those duplicate the dependencies in the Google Ads API library but point to older versions, that could cause issues.

Thanks,
Josh

**Comment by huan-ds** [comment]
Hi, 

The grpc dependencies version represent:
```
Maven-io-grpc_grpc-context-1.x (1.28.0)
Maven-io-grpc_grpc-core-1.x(1.10.0)
Maven-io-grpc_grpc-netty-shaded(1.21.0)
```
Please let me know if those dependencies would cause the issue.

Thanks, 
Huan

**Comment by jradcliff** [comment]
I may be misinterpreting that file you sent me, but it looks like you are depending on *both* the `shadowjar` (shaded) version of our library *and* the non-shaded version:

```
$ sort DependecyFile | grep google-api-ads_google-ads
Maven-com-google-api-ads_google-ads-22.x
Maven-com-google-api-ads_google-ads-codegen-22.x
Maven-com-google-api-ads_google-ads-shadowjar-22.x <-- Shaded version
Maven-com-google-api-ads_google-ads-stubs-lib-22.x
Maven-com-google-api-ads_google-ads-stubs-v10-22.x
Maven-com-google-api-ads_google-ads-stubs-v11-22.x
Maven-com-google-api-ads_google-ads-stubs-v12-22.x
```

The `shadowjar` version for release 22.0.0 [depends on grpc 1.44.1](https://github.com/googleads/google-ads-java/tree/22.0.0/third_party). If your intention is to use grpc 1.50.x with the library, then I would remove the dependency on `Maven-com-google-api-ads_google-ads-shadowjar-22.x` so you won't have both 1.44.1 and 1.50.x classes in the classpath.

Re: your question of

> Please let me know if those dependencies would cause the issue.
> ```
> Maven-io-grpc_grpc-context-1.x (1.28.0)
> Maven-io-grpc_grpc-core-1.x(1.10.0)
> Maven-io-grpc_grpc-netty-shaded(1.21.0)
> ```

those are older versions than the ones you have specified (1.50.x) and the ones in the Google Ads lib dependencies, so I would remove those old versions to avoid conflicts as well.

Thanks,
Josh

**Comment by huan-ds** [comment]
Hi,

We have removed the dependency on `Maven-com-google-api-ads_google-ads-shadowjar-22.x` and use `Maven-com-google-api-ads_google-ads-22.x` now. 

The `grpc-netty-shaded` issue is gone, but we are still facing a error when creating Google Batch Job Service:
```
io.grpc.NameResolver$Args$Builder.setOverrideAuthority(Ljava/lang/String;)Lio/grpc/NameResolver$Args$Builder;
```
I attached the error stack trace: 

[GoogleBulkJob_errorlog.zip](https://github.com/googleads/google-ads-java/files/10348348/GoogleBulkJob_errorlog.zip)

Please kindly advice what could cause this issue.

Thanks, 
Huan

**Comment by jradcliff** [comment]
Hi,

Have you also removed the following dependencies?

```
Maven-io-grpc_grpc-context-1.x (1.28.0)
Maven-io-grpc_grpc-core-1.x(1.10.0)
Maven-io-grpc_grpc-netty-shaded(1.21.0)
```

The `setOverrideAuthority` method [has been around for quite some time](https://github.com/grpc/grpc-java/commit/027d36eee7cb595a17e1a35706f6987f78322973#diff-9947539200d59d75ca83e3b6b1212c99e8a1cfd91513692fe06e300f265f6f98), but it's possible that with the above dependencies on older grpc versions, your app is loading classes from those older versions where this method is missing.

Thanks,
Josh

**Comment by huan-ds** [comment]
Hi
I removed the dependencies and getting another error: [GoogleApiV12_CheckActivityLog.zip](https://github.com/googleads/google-ads-java/files/10349016/GoogleApiV12_CheckActivityLog.zip)
```
Maven-io-grpc_grpc-context-1.x
Maven-io-grpc_grpc-core-1.x
Maven-io-grpc_grpc-netty-shaded-1.x
```

Thanks, 
Huan

**Comment by jradcliff** [comment]
Hi,

Could you send the updated list of dependencies now that you've made changes?

Also, if this is in a test environment where you can modify settings and experiment, you could enable verbose class loading with the `-verbose:class` option so you can see the JAR or local `.class` file from which every class is being loaded. If your JVM is picking up the wrong version of any classes, that information could be helpful.

Thanks,
Josh

**Comment by huan-ds** [comment]
Hi,

This is the updated list of dependencies: [dependencies.zip](https://github.com/googleads/google-ads-java/files/10376690/dependencies.zip) 

I am trying to figure out if we can use verbose in the environment. 

Please let me know if the updated dependencies misused any version.

Thanks,
Huan

**Comment by huan-ds** [comment]
Hi,

We enabled verbose mode. Please check the log from verbose: [PackageList_From_Verbose.txt](https://github.com/googleads/google-ads-java/files/10377829/PackageList_From_Verbose.txt)

And we are getting an updated error:
[GoogleUpgrade_CheckActivityLog.zip](https://github.com/googleads/google-ads-java/files/10377827/GoogleUpgrade_CheckActivityLog.zip)

Please let me know if you find anything.

Thanks,
Huan

**Comment by jradcliff** [comment]
Hi,

I recommend going through that file and looking for places where you are loading classes in related packages from different versions of components of the dependency.

For example, the verbose output shows that you are loading `FieldMask` and `AbstractMessage` (the superclass of `FieldMask`) from different versions of the protobuf library:

1. Loading `com.google.protobuf.FieldMask` from `protobuf-javalite-3.21.9.jar`
2. Loading `com.google.protobuf.AbstractMessage` from `protobuf-java-3.21.4.jar`

This is likely the cause of the error in the activity log of `com.google.protobuf.FieldMask cannot be cast to com.google.protobuf.AbstractMessage`.

Thanks,
Josh

**Comment by jradcliff** [comment]
Hi Huan,

That's great news! Glad to hear it's fixed for you now. I'll mark the issue closed.

Cheers,
Josh
