### ISSUE TITLE
upload list of email addesses to a user list

### ISSUE THREAD

**Issue by d3r3ktm** [googleads/google-ads-java#684]
**What is your question?**
Hi

I am trying to migrate from Google Adwords API to Google Ads API to upload a list / file of email addresses to a customer user list.

I have referred and followed this example [add customer match user list ](https://github.com/googleads/google-ads-java/blob/50a65751c0b714cadcdd7c3ff1f3eebc65090f6d/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/AddCustomerMatchUserList.java).
The code example only shows the creation and uploading of 1 email address record.

    // Creates the first user data based on an email address.
    UserData userDataWithEmailAddress =
        UserData.newBuilder()
            .addUserIdentifiers(
                UserIdentifier.newBuilder()
                    .setHashedEmail(normalizeAndHash(sha256Digest, "customer@example.com")))
            .build();

May I know how should I modify it to support the uploading of more than 1 email address record?
I am planning to retrieved each email address from the file using a loop.

I have asked google ads api support and was directed to seek help in github.

Derek

**Comment by jradcliff** [comment]
Hi Derek,

You should create a new `UserData` object for each distinct _user_ (member of the list). This will look similar to the lines you highlighted, but you'd want to add each distinct `UserData` to the list of operations.

For example, let's say you have a `List<String>` named `emails` that you've read from your file. Then you'd want something like this:

```
// Creates a list of operations for the request.
List<OfflineUserDataJobOperation> operations = new ArrayList<>();
for (String email : emails) {
   // Creates a UserData containing the hashed email UserIdentifier.
   UserData userDataWithEmailAddress =
        UserData.newBuilder()
            .addUserIdentifiers(
                UserIdentifier.newBuilder()
                    .setHashedEmail(normalizeAndHash(sha256Digest, email)))
            .build();
  // Adds an operation for creating the UserData.
  operations.add(OfflineUserDataJobOperation.newBuilder().setCreate(userData).build());
}
// Creates a request with all of the operations above.
AddOfflineUserDataJobOperationsRequest.newBuilder()
  .setResourceName(offlineUserDataJobResourceName)
  .setEnablePartialFailure(true)
  // Adds the operations to the request's "operations" list.
  .addAllOperations(userDataJobOperations)
  .build();
...
```

If you have more than 100,000 `UserIdentifiers` in total (across all of your `UserData` objects), then you should send multiple `AddOfflineUserDataJobOperations` calls for the same job. Please refer to the [documentation](https://developers.google.com/google-ads/api/docs/remarketing/audience-types/customer-match#customer_match_considerations) for more details and other considerations.

One key point: It is *far* more efficient to create and run a single job with a large number of operations than create  multiple jobs with a small number of operations, as Customer Match processing is optimized for the former approach.

Hope that helps! Let me know if anything above is unclear.

Cheers,
Josh, Google Ads API Team

**Comment by d3r3ktm** [comment]
Hi Josh

Thank you for your advice. Will try it out and update you.
