### ISSUE TITLE
V12 to V13 Migration : Type of the UserList does not match

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#694]
```
implementation "com.google.api-ads:google-ads:23.0.0"
```

Hi all. I've already posted this issue to googleadsapi-support@google.com but the solution there is:

```
So, it appears that on your end, you didn’t create it using AddFlexibleRuleUserList.java but you tried to update it with V13. I recommend you to use AddFlexibleRuleUserList.java to both create and update it.
```

Obviously we need the ability ( and I'm sure it exists  ) to mutate RULE_BASED UserLists that were created before V13 or were created without utilizing FlexibleRuleUserListInfo

Below is my original post to the email list. I will also add that I've tried manually massaging FieldMask from what is generated by FieldMasks.allSetFieldsOf( userList ). I haven't been able to get a pre-existing RULE_BASED UserList to push through when it contains a FlexibleRuleUserListInfo

Email contents:

We're on the last mile of migrating from v12 to v13 using v23.0.0 of the Google Ads API Client Library for Java : https://github.com/googleads/google-ads-java

The request-id for the transaction outlined in this message is : Tnn2qCuaZGjkdUx13DCe0A

As noted here https://developers.google.com/google-ads/api/docs/release-notes#audiences :

"Removed CombinedRuleUserListInfo and ExpressionRuleUserListInfo and their references from RuleBasedUserListInfo. Use FlexibleUserListInfo instead."

When testing the mutation of an existing Rule Based UserList we are running into the error:

```
partial_failure_error {
  code: 3
  message: "Type of the UserList does not match., at operations[0]"
  details {
    type_url: "[type.googleapis.com/google.ads.googleads.v13.errors.GoogleAdsFailure](http://type.googleapis.com/google.ads.googleads.v13.errors.GoogleAdsFailure)"
    value: "\n=\n\003\360\004\t\022$Type of the UserList does not match.\"\020\022\016\n\noperations\030\000"
  }
}
```

We are not changing the type on the UserList, and if we don't send type in the mutation we get the same error.

The Google Ads API represents the existing live object as such:

```
resource_name: "customers/redacted224/userLists/redacted484"
type: RULE_BASED
rule_based_user_list {
  prepopulation_status: UNKNOWN
  flexible_rule_user_list {
    inclusive_rule_operator: OR
    inclusive_operands {
      rule {
        rule_item_groups {
          rule_items {
            string_rule_item {
              operator: CONTAINS
              value: "stop-redacted"
            }
            name: "url__"
          }
        }
      }
      lookback_window_days: 365
    }
  }
}
id: redacted484
read_only: false
name: "Prospects Franchise redacted"
description: "Email and PPC traffic directed at redacted prospects"
integration_code: "tp=VISITORS_RULE"
membership_life_span: 365
```

This is our mutate attempt ( we're not actually changing anything )

```
Request
-------
MethodName: google.ads.googleads.v13.services.UserListService/MutateUserLists
Endpoint: [googleads.googleapis.com:443](http://googleads.googleapis.com:443/)
Headers: {developer-token=REDACTED, login-customer-id=redacted165, x-goog-api-client=gl-java/11.0.15 gccl/23.0.0 gapic/23.0.0 gax/2.22.0 grpc/1.52.1 pb/3.21.12}
Body: customer_id: "redacted224"
operations {
  update {
    resource_name: "customers/redacted224/userLists/redacted484"
    membership_status: OPEN
    type: RULE_BASED
    rule_based_user_list {
      flexible_rule_user_list {
        inclusive_rule_operator: OR
        inclusive_operands {
          rule {
            rule_item_groups {
              rule_items {
                string_rule_item {
                  operator: CONTAINS
                  value: "stop-redacted"
                }
                name: "url__"
              }
            }
          }
          lookback_window_days: 365
        }
      }
    }
    id: redacted484
    name: "Prospects Franchise redacted"
    description: "Email and PPC traffic directed at redacted prospects"
    integration_code: "tp=VISITORS_RULE"
    membership_life_span: 365
  }
  update_mask {
    paths: "resource_name"
    paths: "id"
    paths: "name"
    paths: "description"
    paths: "membership_status"
    paths: "integration_code"
    paths: "membership_life_span"
    paths: "type"
    paths: "rule_based_user_list.flexible_rule_user_list.inclusive_rule_operator"
    paths: "rule_based_user_list.flexible_rule_user_list.inclusive_operands"
  }
}
partial_failure: true
```

```
Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,request-id=Tnn2qCuaZGjkdUx13DCe0A,date=Wed, 01 Mar 2023 16:47:57 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000)
Body: results {
}
partial_failure_error {
  code: 3
  message: "Type of the UserList does not match., at operations[0]"
  details {
    type_url: "[type.googleapis.com/google.ads.googleads.v13.errors.GoogleAdsFailure](http://type.googleapis.com/google.ads.googleads.v13.errors.GoogleAdsFailure)"
    value: "\n=\n\003\360\004\t\022$Type of the UserList does not match.\"\020\022\016\n\noperations\030\000"
  }
}

Failure message: null
Status: Status{code=OK, description=null, cause=null}
```

As can be seen, we are not changing the type of the UserList

I've double checked the FlexibleRuleUserList example writen by @jradcliff at https://github.com/googleads/google-ads-java/blob/main/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/AddFlexibleRuleUserList.java and I don't think I've missed anything.

Thanks
Pete

**Comment by jradcliff** [comment]
Hi @PeterLavetsky ,

I was able to reproduce the behavior you're seeing using an older user list in my account. I've reported this issue and we're looking into it. I'll reply back here once I have an update.

Thanks,
Josh

ref: b/272808205

**Comment by jradcliff** [comment]
Hi @PeterLavetsky ,

We have a fix for this and I'm just waiting for it to reach production. I'll provide an update when that happens.

In the meantime, a colleague of mine reminded me that [our v12 to v13 upgrade guide has some useful information](https://developers.google.com/google-ads/api/docs/upgrade#:~:text=We%20have%20built%20in%20a%20shortcut%20to%20upgrade%20to%20the%20new%20FlexibleRuleUserListInfo%20easily.) about upgrading existing lists with `ExpressionRuleUserListInfo` to use `FlexibleRuleUserListInfo`. I'm guessing you already saw that and that's how you ran into this issue, but including that link in case others are following this issue.

Thanks,
Josh, Google Ads API Team

**Comment by PeterLavetsky** [comment]
@jradcliff That is great news!

I didn't see that upgrade page before but I'll make sure to add it to our migration checklist in the future.

Thanks
Pete
