### ISSUE TITLE
Unable to Initialize the GoogleAdsClient Object using Google Ads API Client Library v1.0

### ISSUE THREAD

**Issue by icedhacker** [googleads/google-ads-java#70]
While using the Google Ads API v1.0 with the client library v1.0, the following GoogleAdsClient object is being created :
![image](https://user-images.githubusercontent.com/1696817/54342883-88674580-4678-11e9-903d-b1e1b0b5043d.png)

As you can notice in this debug screen, The value for “googleAdsAllVersions” is being initialized to null.  All the other fields including credentials & loginCustomerId seems to be initialized properly. This results in the call failing with the following error. 
**Stacktrace :**
```
Caused by: java.lang.NullPointerException: null
	at com.sun.proxy.$Proxy124.hashCode(Unknown Source)
	at com.google.ads.googleads.lib.AutoValue_GoogleAdsClient.hashCode(AutoValue_GoogleAdsClient.java:98)
	at jp.co.rakuten.adplats.sem.mediasync.config.GoogleAdsConfiguration.hashCode(GoogleAdsConfiguration.java:7)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
```

**Code :** 
```
GoogleAdsClient
    .newBuilder().fromPropertiesFile(new ClassPathResource(fileName).getFile()).build();
```

**Ads Properties :** 
```
# Configuration for Google Ads API
api.googleads.refreshToken=<REFRESH_TOKEN>
api.googleads.clientId=<CLIENT_ID>
api.googleads.developerToken=<DEVELOPER_TOKEN>
api.googleads.clientSecret=<CLIENT_SECRET>
api.googleads.loginCustomerId=<LOGIN_CUSTOMER_ID>
```

**Maven Dependency :** 
```
<dependency>
  <groupId>com.google.api-ads</groupId>
  <artifactId>google-ads</artifactId>
  <version>1.0.0</version>
</dependency>
```

It seems like we are missing some new configuration to generate the “googleAdsAllVersions” object. Please confirm and let us know if there are any fixes for such an issue. Also, let us know if you have any suggestion on improving this implementation.

**Comment by nwbirnie** [comment]
Hey, this should be fixed in 1.0.1. Please update to the latest version.
