### ISSUE TITLE
How to get Google Tag ID or snippet code from a ConversionAction?

### ISSUE THREAD

**Issue by madc0w** [googleads/google-ads-java#723]
I'm basing my development on [this code example,](https://developers.google.com/google-ads/api/docs/conversions/create-conversion-actions) but I'm having some trouble creating and configuring ConversionActions.

The docs [here](https://developers.google.com/google-ads/api/docs/conversions/overview) say this:

> Website and Phone number clicks conversions require the event_snippet (which should be placed on web pages that indicate a conversion action such as a checkout confirmation or lead submission page) and global_site_tag (which must be installed on every page of your website). You can retrieve both of these attributes with [ConversionActionService](https://developers.google.com/google-ads/api/reference/rpc/v14/ConversionActionService).

Unfortunately, the linked ConversionActionService docs make no mention of either of these fields. I did find a getTagSnippetsList() method which I can call on my newly created ConversionAction, but this returns an empty list.

How can I get the Google Tag ID, or the complete snippet code to be inserted into the web page?

**Comment by jradcliff** [comment]
Hi,

This question is about API behavior and is not specific to the Java client library. Please reach out to our support team using the form at https://developers.google.com/google-ads/api/support for assistance.

Thanks,
Josh
