### ISSUE TITLE
Google Ads API v14 java.lang.NoClassDefFoundError: Could not initialize class com.google.api.gax.rpc.RequestUrlParamsEncoder

### ISSUE THREAD

**Issue by osib-c** [googleads/google-ads-java#737]
**Describe the bug:**

After update of google-api-ads library to version 27.0.0 we started getting errors similar to what was reported by several users already:
java.lang.NoClassDefFoundError: Could not initialize class com.google.api.gax.rpc.RequestUrlParamsEncoder
and
java.lang.NoSuchMethodError: com.google.api.client.util.escape.PercentEscaper.<init>(Ljava/lang/String;)V

Using the shaded version of the library didn't help, and we didn't manage to find what could be wrong with the dependencies.

What could be the cause of the errors?

Thanks!

**Client library version and API version:**
Client library version: 27.0.0
Google Ads API version: v14
JDK version: 8

**Maven dependency tree:**

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ xy ---
[WARNING] The artifact xml-apis:xml-apis:jar:2.0.2 has been relocated to xml-apis:xml-apis:jar:1.0.b2
[INFO] com.x.y:xy:jar:0.17.1-SNAPSHOT
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.5:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.5:compile
[INFO] +- com.google.api-ads:google-ads:jar:27.0.0:compile
[INFO] |  +- com.google.api:gax:jar:2.32.0:compile
[INFO] |  |  +- com.google.api:api-common:jar:2.15.0:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:2.23.0:compile
[INFO] |  |  +- org.threeten:threetenbp:jar:1.6.8:compile
[INFO] |  |  \- io.opencensus:opencensus-api:jar:0.31.1:compile
[INFO] |  |     \- io.grpc:grpc-context:jar:1.27.2:compile
[INFO] |  +- com.google.api:gax-grpc:jar:2.32.0:compile
[INFO] |  |  +- io.grpc:grpc-api:jar:1.56.1:compile
[INFO] |  |  +- io.grpc:grpc-alts:jar:1.56.1:compile
[INFO] |  |  |  +- io.grpc:grpc-grpclb:jar:1.56.1:compile
[INFO] |  |  |  \- org.conscrypt:conscrypt-openjdk-uber:jar:2.5.2:compile
[INFO] |  |  +- io.grpc:grpc-auth:jar:1.56.1:compile
[INFO] |  |  +- io.grpc:grpc-netty-shaded:jar:1.56.1:compile
[INFO] |  |  |  +- io.perfmark:perfmark-api:jar:0.26.0:runtime
[INFO] |  |  |  \- io.grpc:grpc-core:jar:1.56.1:compile
[INFO] |  |  |     +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |  |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.23:runtime
[INFO] |  |  \- io.grpc:grpc-googleapis:jar:1.56.1:runtime
[INFO] |  |     \- io.grpc:grpc-xds:jar:1.56.1:runtime
[INFO] |  |        +- io.opencensus:opencensus-proto:jar:0.2.0:runtime
[INFO] |  |        +- io.grpc:grpc-services:jar:1.56.1:runtime
[INFO] |  |        \- com.google.re2j:re2j:jar:1.7:runtime
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.23.2:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.56.1:compile
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.56.1:compile
[INFO] |  |  \- io.grpc:grpc-protobuf-lite:jar:1.56.1:compile
[INFO] |  +- com.google.auth:google-auth-library-oauth2-http:jar:1.19.0:compile
[INFO] |  |  +- com.google.http-client:google-http-client:jar:1.42.3:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  |  |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.15:compile
[INFO] |  |  |  \- io.opencensus:opencensus-contrib-http-util:jar:0.31.1:compile
[INFO] |  |  \- com.google.http-client:google-http-client-gson:jar:1.42.3:compile
[INFO] |  +- com.google.auth:google-auth-library-credentials:jar:1.19.0:compile
[INFO] |  +- com.google.api-ads:google-ads-codegen:jar:27.0.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-lib:jar:27.0.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-v13:jar:27.0.0:compile
[INFO] |  |  +- com.google.api-ads:google-ads-stubs-v14:jar:27.0.0:compile
[INFO] |  |  \- com.squareup:javapoet:jar:1.11.1:runtime
[INFO] |  +- com.google.guava:guava:jar:32.1.2-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  \- org.checkerframework:checker-qual:jar:3.33.0:compile
[INFO] |  +- com.google.auto.service:auto-service:jar:1.0.1:runtime
[INFO] |  |  +- com.google.auto.service:auto-service-annotations:jar:1.0.1:runtime
[INFO] |  |  \- com.google.auto:auto-common:jar:1.2:runtime
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  \- com.google.auto.value:auto-value-annotations:jar:1.10.2:compile
[INFO] +- com.google.api-ads:ads-lib:jar:5.2.0:compile
[INFO] |  +- com.google.inject:guice:jar:5.0.1:compile
[INFO] |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- com.google.inject.extensions:guice-assistedinject:jar:5.0.1:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- commons-configuration:commons-configuration:jar:1.10:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- com.opencsv:opencsv:jar:4.6:compile
[INFO] |  |  +- org.apache.commons:commons-text:jar:1.3:compile
[INFO] |  |  \- org.apache.commons:commons-collections4:jar:4.2:compile
[INFO] |  +- joda-time:joda-time:jar:2.8.2:compile
[INFO] |  +- com.google.api-client:google-api-client:jar:1.26.1:compile
[INFO] |  |  +- com.google.oauth-client:google-oauth-client:jar:1.26.0:compile
[INFO] |  |  \- com.google.http-client:google-http-client-jackson2:jar:1.26.0:compile
[INFO] |  +- com.google.api-client:google-api-client-gson:jar:1.26.0:compile
[INFO] |  +- com.beust:jcommander:jar:1.48:compile
[INFO] |  +- com.sun.xml.bind:jaxb-ri:pom:2.3.2:compile
[INFO] |  |  \- org.glassfish.jaxb:txw2:jar:2.3.2:compile
[INFO] |  +- com.sun.xml.ws:jaxws-ri:pom:2.3.2:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.4:compile
[INFO] |  |  +- com.sun.xml.ws:jaxws-rt:jar:2.3.2:compile
[INFO] |  |  |  +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.2:compile
[INFO] |  |  |  |  \- com.sun.istack:istack-commons-runtime:jar:3.0.8:compile
[INFO] |  |  |  +- com.sun.xml.ws:policy:jar:2.7.6:compile
[INFO] |  |  |  +- org.glassfish.gmbal:gmbal:jar:4.0.0:compile
[INFO] |  |  |  |  +- org.glassfish.external:management-api:jar:3.2.1:compile
[INFO] |  |  |  |  +- org.glassfish.pfl:pfl-basic:jar:4.0.1:compile
[INFO] |  |  |  |  +- org.glassfish.pfl:pfl-tf:jar:4.0.1:compile
[INFO] |  |  |  |  |  +- org.glassfish.pfl:pfl-asm:jar:4.0.1:compile
[INFO] |  |  |  |  |  \- org.glassfish.pfl:pfl-dynamic:jar:4.0.1:compile
[INFO] |  |  |  |  +- org.glassfish.pfl:pfl-basic-tools:jar:4.0.1:compile
[INFO] |  |  |  |  \- org.glassfish.pfl:pfl-tf-tools:jar:4.0.1:compile
[INFO] |  |  |  +- org.jvnet.staxex:stax-ex:jar:1.8.1:compile
[INFO] |  |  |  +- com.sun.xml.stream.buffer:streambuffer:jar:1.5.7:compile
[INFO] |  |  |  +- org.jvnet.mimepull:mimepull:jar:1.9.11:compile
[INFO] |  |  |  +- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.16:compile
[INFO] |  |  |  +- org.glassfish.ha:ha-api:jar:3.1.12:compile
[INFO] |  |  |  +- com.sun.xml.messaging.saaj:saaj-impl:jar:1.5.1:compile
[INFO] |  |  |  +- com.fasterxml.woodstox:woodstox-core:jar:5.1.0:runtime
[INFO] |  |  |  +- org.codehaus.woodstox:stax2-api:jar:4.1:compile
[INFO] |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  +- com.sun.xml.ws:jaxws-tools:jar:2.3.2:compile
[INFO] |  |  |  +- com.sun.xml.bind:jaxb-xjc:jar:2.3.2:compile
[INFO] |  |  |  \- com.sun.xml.bind:jaxb-jxc:jar:2.3.2:compile
[INFO] |  |  +- com.sun.xml.ws:jaxws-eclipselink-plugin:jar:2.3.2:compile
[INFO] |  |  |  +- jakarta.mail:jakarta.mail-api:jar:1.6.3:compile
[INFO] |  |  |  +- jakarta.persistence:jakarta.persistence-api:jar:2.2.2:compile
[INFO] |  |  |  \- org.eclipse.persistence:org.eclipse.persistence.moxy:jar:2.7.4:compile
[INFO] |  |  |     \- org.eclipse.persistence:org.eclipse.persistence.core:jar:2.7.4:compile
[INFO] |  |  |        \- org.eclipse.persistence:org.eclipse.persistence.asm:jar:2.7.4:compile
[INFO] |  |  +- com.sun.xml.ws:sdo-eclipselink-plugin:jar:2.3.2:compile
[INFO] |  |  |  +- org.eclipse.persistence:org.eclipse.persistence.sdo:jar:2.7.4:compile
[INFO] |  |  |  \- org.eclipse.persistence:commonj.sdo:jar:2.1.1:compile
[INFO] |  |  +- jakarta.xml.ws:jakarta.xml.ws-api:jar:2.3.2:compile
[INFO] |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  |  +- jakarta.xml.soap:jakarta.xml.soap-api:jar:1.4.1:compile
[INFO] |  |  \- jakarta.jws:jakarta.jws-api:jar:1.1.1:compile
[INFO] |  \- com.sun.activation:javax.activation:jar:1.2.0:compile
[INFO] +- com.google.protobuf:protobuf-java-util:jar:3.24.4:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.9:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.18.0:compile
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:2.8:compile
[INFO] +- com.x.y:xy:jar:0.22.3:compile
[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.16.0:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.16.0:compile
[INFO] |  +- org.apache.logging.log4j:log4j-jcl:jar:2.16.0:compile
[INFO] |  +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.16.0:compile
[INFO] |  +- com.x.y:xy:jar:0.4.4:compile
[INFO] |  |  +- org.mule:mule-core:jar:3.6.1:compile
[INFO] |  |  |  +- com.github.stephenc.eaio-uuid:uuid:jar:3.4.0:compile
[INFO] |  |  |  |  \- com.github.stephenc.eaio-grabbag:grabbag:jar:1.8.1:compile
[INFO] |  |  |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  |  |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  |  |  +- commons-pool:commons-pool:jar:1.6:compile
[INFO] |  |  |  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:compile
[INFO] |  |  |  +- org.apache.geronimo.specs:geronimo-j2ee-connector_1.5_spec:jar:1.1:compile
[INFO] |  |  |  +- com.lmax:disruptor:jar:3.3.0:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-1.2-api:jar:2.1:compile
[INFO] |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.7:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-jul:jar:2.1:compile
[INFO] |  |  |  +- asm:asm:jar:3.1:compile
[INFO] |  |  |  +- asm:asm-commons:jar:3.1:compile
[INFO] |  |  |  |  \- asm:asm-tree:jar:3.1:compile
[INFO] |  |  |  +- org.mule.mvel:mule-mvel2:jar:2.1.9-MULE-005:compile
[INFO] |  |  |  +- org.jgrapht:jgrapht-jdk1.5:jar:0.7.3:compile
[INFO] |  |  |  \- org.mule.common:mule-common:jar:3.6.1:compile
[INFO] |  |  |     +- org.apache.xmlbeans:xmlbeans:jar:2.3.0:compile
[INFO] |  |  |     +- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  |  |     +- org.json:json:jar:20140107:compile
[INFO] |  |  |     \- org.antlr:antlr-runtime:jar:3.5:compile
[INFO] |  |  |        \- org.antlr:stringtemplate:jar:3.2.1:compile
[INFO] |  |  +- org.reflections:reflections:jar:0.9.10:compile
[INFO] |  |  |  +- org.javassist:javassist:jar:3.19.0-GA:compile
[INFO] |  |  |  \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-frontend-jaxws:jar:3.1.0:compile
[INFO] |  |  |  +- xml-resolver:xml-resolver:jar:1.2:compile
[INFO] |  |  |  +- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-core:jar:3.1.0:compile
[INFO] |  |  |  |  +- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:compile
[INFO] |  |  |  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.1:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-bindings-soap:jar:3.1.0:compile
[INFO] |  |  |  |  +- org.apache.cxf:cxf-rt-wsdl:jar:3.1.0:compile
[INFO] |  |  |  |  |  \- wsdl4j:wsdl4j:jar:1.6.3:compile
[INFO] |  |  |  |  \- org.apache.cxf:cxf-rt-databinding-jaxb:jar:3.1.0:compile
[INFO] |  |  |  |     +- com.sun.xml.bind:jaxb-impl:jar:2.2.11:compile
[INFO] |  |  |  |     \- com.sun.xml.bind:jaxb-core:jar:2.2.11:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-bindings-xml:jar:3.1.0:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-frontend-simple:jar:3.1.0:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-ws-addr:jar:3.1.0:compile
[INFO] |  |  |     \- org.apache.cxf:cxf-rt-ws-policy:jar:3.1.0:compile
[INFO] |  |  |        \- org.apache.neethi:neethi:jar:3.0.3:compile
[INFO] |  |  \- org.apache.cxf:cxf-rt-transports-http:jar:3.1.0:compile
[INFO] |  +- net.jodah:failsafe:jar:1.1.1:compile
[INFO] |  +- com.rabbitmq:amqp-client:jar:3.6.6:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO] |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  \- org.redisson:redisson:jar:3.23.4:compile
[INFO] |     +- io.netty:netty-common:jar:4.1.96.Final:compile
[INFO] |     +- io.netty:netty-codec:jar:4.1.96.Final:compile
[INFO] |     +- io.netty:netty-buffer:jar:4.1.96.Final:compile
[INFO] |     +- io.netty:netty-transport:jar:4.1.96.Final:compile
[INFO] |     +- io.netty:netty-resolver:jar:4.1.96.Final:compile
[INFO] |     +- io.netty:netty-resolver-dns:jar:4.1.96.Final:compile
[INFO] |     |  \- io.netty:netty-codec-dns:jar:4.1.96.Final:compile
[INFO] |     +- io.netty:netty-handler:jar:4.1.96.Final:compile
[INFO] |     |  \- io.netty:netty-transport-native-unix-common:jar:4.1.96.Final:compile
[INFO] |     +- javax.cache:cache-api:jar:1.1.1:compile
[INFO] |     +- io.projectreactor:reactor-core:jar:3.5.3:compile
[INFO] |     +- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |     +- io.reactivex.rxjava3:rxjava:jar:3.1.6:compile
[INFO] |     +- org.jboss.marshalling:jboss-marshalling:jar:2.0.11.Final:compile
[INFO] |     +- org.jboss.marshalling:jboss-marshalling-river:jar:2.0.11.Final:compile
[INFO] |     +- com.esotericsoftware:kryo:jar:5.5.0:compile
[INFO] |     |  +- com.esotericsoftware:reflectasm:jar:1.11.9:compile
[INFO] |     |  +- org.objenesis:objenesis:jar:3.3:compile
[INFO] |     |  \- com.esotericsoftware:minlog:jar:1.3.1:compile
[INFO] |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.15.2:compile
[INFO] |     |  \- org.yaml:snakeyaml:jar:2.0:compile
[INFO] |     +- net.bytebuddy:byte-buddy:jar:1.14.5:compile
[INFO] |     \- org.jodd:jodd-bean:jar:5.1.6:compile
[INFO] |        \- org.jodd:jodd-core:jar:5.1.6:compile
[INFO] +- com.x.y:xy:jar:0.1.8:compile
[INFO] |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.52:compile
[INFO] |  |  \- org.bouncycastle:bcprov-jdk15on:jar:1.52:compile
[INFO] |  \- org.springframework:spring-web:jar:4.2.1.RELEASE:compile
[INFO] +- org.springframework:spring-context:jar:4.3.30.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.3.30.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.3.30.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:4.3.30.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.3.30.RELEASE:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.springframework:spring-test:jar:4.3.30.RELEASE:test
[INFO] \- org.mockito:mockito-all:jar:1.10.19:test
[INFO] ------------------------------------------------------------------------

**Comment by jradcliff** [comment]
Similar to the user on [issue 736](https://github.com/googleads/google-ads-java/issues/736#issuecomment-1731680918), I see you have a dependency on a component of the library for the old, sunset API:

`com.google.api-ads:ads-lib:jar:5.2.0:compile`

Please remove that dependency from your project and let me know if you still see issues.

Thanks,
Josh, Google Ads API Team
