### ISSUE TITLE
UNKNOWN: Uncaught exception in the SynchronizationContext. Re-thrown.

### ISSUE THREAD

**Issue by rotemzluf123** [googleads/google-ads-java#741]
Hi,

While attempting to use addOfflineUserDataJobOperations from the library com.google.ads.googleads.v14.services, I sometimes get this exception: UNKNOWN: Uncaught exception in the SynchronizationContext. Re-thrown.

Are you familiar with this issue and do you know how to fix it? I believe this problem started when I upgraded the library version from v12 to v14.

Thanks.

**Comment by rotemzluf123** [comment]
full error: io.grpc.StatusRuntimeException: UNKNOWN: Uncaught exception in the SynchronizationContext. Re-thrown.

**Comment by jradcliff** [comment]
@rotemzluf123 , could you let me know if you're still encountering this problem?

Thanks

**Comment by rotemzluf123** [comment]
I checked option 1, and it was indeed the problem. In some cases, my client was closed. Thank you for your help.
