### ISSUE TITLE
Using shadow jar with exclusion and relocation

### ISSUE THREAD

**Issue by adithya-1** [googleads/google-ads-java#744]
**What is your question?**

Hello, 
While upgrading to google ads API v15, facing issues as mentioned in https://github.com/googleads/google-ads-java/issues/737, https://github.com/googleads/google-ads-java/issues/743 and with our current code base its not straight forward to remove these dependencies. 

So I was exploring the possibility of using a shadow jar, however the size of shadow jar is coming upto 122 MB which is heavy. I wanted to take only ads-v15, grpc, guava from the shadow jar and rename these usages to different name like com.google.shaded.v28. How may I achieve this?

**Comment by jradcliff** [comment]
We don't publish version-specific shadow jars, but if you want to build a shadow jar that only contains v15 yourself, you could:

1. Clone this repo.
2. Remove the following lines from [settings.gradle](https://github.com/googleads/google-ads-java/blob/main/settings.gradle):
    ```
    include ':google-ads-stubs-v13'
    include ':google-ads-stubs-v14'
    ```
3. (Optional, but recommended): Update the `version` in [gradle.properties](https://github.com/googleads/google-ads-java/blob/main/gradle.properties) to a custom version label so you can differentiate between your custom JAR and other artifacts from the repo/Maven central.
4. Run the Gradle task `google-ads-shadowjar:publishToMavenLocal` to produce the JAR and publish it to your local Maven repo.

**Comment by adithya-1** [comment]
Thank you for the response, Is it possible if I can exclude dependencies of com.google.cloud, com.google.geo  while building the shaded jars? 
I have other dependencies which pull the same so while run time this won't cause any issues.  So was wondering if I can exclude them in the jar?

**Comment by adithya-1** [comment]
Also note: I am adding relocate in the shadowJar task for example: 
relocate 'com.google.protobuf', 'com.google.shaded.v28.protobuf' in order to differentiate between protobuf that is currently in my repo to the one google-ads needs. Using jdk-8 hence maven is taking the lowest version which is causing issues in runtime. Do you recommend and other way to fix this problem?

**Comment by jradcliff** [comment]
Stepping back a moment, could you elaborate on what you meant when you mentioned that removing the dependencies would not be straightforward? I ask because creating this custom shadow jar is going to be far from straightforward as well.

If, for example, your application was depending on libraries that the old AdWords API library (e.g., `com.google.api-ads:adwords-axis`, `com.google.api-ads.ads-lib`, or `com.google.api-ads.adwords-appengine`) happened to include in the classpath, it would be far easier to just explicitly declare those dependencies in your project + remove the dependency on the old AdWords API library vs. trying to construct a shadow jar.

**Comment by adithya-1** [comment]
Major problem for me is to upgrade guava from 29.0 to 32.0, gax and gax-grpc  from 2.3.0 to 2.36.0, 
protobuff from 3.20.0 to 3.22.0 since its being used through out the product and I cannot release version 15 without testing all these dependencies. 

Hence a safer way was to use a shadowed jar. With your suggestion of dropping v14 and using relocate 'com.google' to 'com.google.shaded.v28' I was able to bring down to 95 MB which has solved my use-case.  I was wondering if I can still reduce the size by not pulling in dependencies that are already present from  pre-existing maven dependencies  in my project such as  com.google.auth: google-auth-library-credentials. 

However if I do the above mentioned steps I believe I have to carefully 'relocate' with appropriate names such that the files are used properly during runtime.

**Comment by jradcliff** [comment]
Thanks, that helps me understand why all of this effort on your part may be worth it. :grin: 

I can't attest to how this would go at runtime, but you _could_ experiment with doing the following in the various `build.gradle` files as well as the files in [`buildSrc/src/main/groovy`](https://github.com/googleads/google-ads-java/tree/main/buildSrc/src/main/groovy):

a) Changing the various `api` dependencies you want to remove to `implementation` dependencies

b) Removing those dependencies altogether

**Comment by adithya-1** [comment]
Got it, thanks for your assistance! Will try out if its possible for me to further reduce from 90 mb.
