### ISSUE TITLE
Get Refresh Token failed 

### ISSUE THREAD

**Issue by zhuqinghong** [googleads/google-ads-java#747]
**What is your question?**
I have oauth client_id and client_secret, I want to get refresh_token 

execute fellow command: 
oauth2l fetch --credentials credentials.json --scope adwords \
    --output_format refresh_token

return msg: 
missing 'type' field in credentials

**Comment by jradcliff** [comment]
Hi,

Please see the instructions for downloading the JSON file in https://developers.google.com/google-ads/api/docs/get-started/oauth-cloud-project#id-secret.

Thanks

**Comment by zhuqinghong** [comment]
I have  already downloaded the JSON file, but 
execute command failed

oauth2l fetch --credentials credentials.json --scope adwords
--output_format refresh_token

**Comment by jradcliff** [comment]
Hi,

Since this is not specific to this library, please reach out to API support using the form at https://developers.google.com/google-ads/api/support.

Thanks,
Josh, Google Ads API Team
