### ISSUE TITLE
USER_PERMISSION_DENIED error when user has granted permissions

### ISSUE THREAD

**Issue by madc0w** [googleads/google-ads-java#751]
Using the Java googleads.v14 API, we are seeing an unexpected error. The end user has granted all permissions, and we have his refresh token, which is usable in other queries. However, we get an "authorization_error: USER_PERMISSION_DENIED" error when attempting to read the "customer" data.

Here is the request:

```
 Headers: {developer-token=REDACTED, login-customer-id=5839428813, x-goog-api-client=gl-java/1.8.0_392 gccl/26.0.0 gapic/26.0.0 gax/2.29.0 grpc/1.27.2}
 Body: customer_id: "2797882929"
   query: "SELECT customer.currency_code, customer.manager FROM customer LIMIT 1"


Failure message: errors {
    error_code {
        authorization_error: USER_PERMISSION_DENIED
    }
    message: "User doesn\'t have permission to access customer. Note: If you\'re accessing a client customer, the manager\'s customer id must be set in the \'login-customer-id\' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid"
}
request_id: "c9ugRp4PtwqWRcea9Gd9Cw" 

```

**Comment by jradcliff** [comment]
Have you checked if the `login-customer-id` of `5839428813` is a manager of account `2797882929`?

**Comment by madc0w** [comment]
No, our business user (5839428813) is not the manager of this client account (2797882929). We do (or should), however, have the ability to read data, such as the currency, from it, as the user granted this permission when he connected his Google account. Hence the confusion.

**Comment by jradcliff** [comment]
The `login-customer-id` defines the access path to the customer specified in the `customer_id` of the request. If `583...` is not a manager of the client, it's expected that the request will fail. The `login-customer-id` should be set to one of the accounts the user has _direct_ access to, and that account must either be a manager of the `customer_id` or the `customer_id` itself.

Please read the description at https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid for more information.

**Comment by hyuxi** [comment]
@jradcliff  hi 2024-04-19 07:19:28.869  INFO 2083716 --- [ult-executor-36] c.g.ads.googleads.lib.request.detail     : FAILURE REQUEST DETAIL.
Request
-------
MethodName: google.ads.googleads.v16.services.GoogleAdsService/Search
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=4677582490, x-goog-api-client=gl-java/1.8.0_322__Red-Hat--Inc. gccl/30.0.0 gapic/30.0.0 gax/2.43.0 grpc/1.30.2}
Body: customer_id: "5024862505"
query: "SELECT user_location_view.targeting_location, user_location_view.resource_name, metrics.impressions, metrics.cost_micros, campaign.id, campaign.name, ad_group.id, ad_group.name, segments.date, metrics.clicks, metrics.conversions_value,user_location_view.country_criterion_id FROM user_location_view WHERE customer.id = 5024862505 AND segments.date = \'2024-04-18\'"


Response
--------
Headers: Metadata(content-type=application/grpc,request-id=BQLRTZiQo87pTs3kGRk9mg,date=Fri, 19 Apr 2024 07:19:28 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000)
Body: null
Failure message: errors {
  error_code {
    authorization_error: USER_PERMISSION_DENIED
  }
  message: "User doesn\'t have permission to access customer. Note: If you\'re accessing a client customer, the manager\'s customer id must be set in the \'login-customer-id\' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid"
}
request_id: "BQLRTZiQo87pTs3kGRk9mg"

Status: Status{code=PERMISSION_DENIED, description=The caller does not have permission, cause=null}.
2024-04-19 07:19:28.871 ERROR 2083716 --- [      Thread-75] c.d.d.j.g.SyncGoogleAdsetDataTestJob     : 测试

com.google.ads.googleads.v16.errors.GoogleAdsException: errors {
  error_code {
    authorization_error: USER_PERMISSION_DENIED
  }
  message: "User doesn\'t have permission to access customer. Note: If you\'re accessing a client customer, the manager\'s customer id must be set in the \'login-customer-id\' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid"
}
request_id: "BQLRTZiQo87pTs3kGRk9mg"

**Comment by jradcliff** [comment]
@hyuxi , please reach out to Google Ads API support via https://developers.google.com/google-ads/api/support/api-issues.
