### ISSUE TITLE
How to differentiate between = "--" or -100% when adjusting the Google Ads UI Bid.

### ISSUE THREAD

**Issue by pocaaaaa** [googleads/google-ads-java#752]
Hi.

The same issue as #261 arises in relation to 'bidModifier'.

I'm currently using the java v13 version, is there any way to distinguish between "--" and -100% by any other method other than hasBidMofire()?

Thank you.

**Comment by jradcliff** [comment]
Hi,

Using `hasBidModifier()` is the standard way to detect if an `optional` protocol buffer 3 field has a value:

https://protobuf.dev/programming-guides/field_presence/#presence-in-proto3-apis

If there's a reason why this isn't working for your use case, could you please elaborate?

Thanks,
Josh, Google Ads API Team

**Comment by jradcliff** [comment]
Correct. The `hasBidModifier()` method will return `true` if the UI shows any value *other than* `--`.

Here's a table that shows some examples:

| Bid adj. (UI)  | hasBidModifier() | getBidModifier() |
| ------------- | ------------- | ------------- |
| -100% | `true` | `0` |
| 20% | `true` | `1.2` |
| `--` | `false` | `0` |

Note that:
1. The value returned by the API is a *multiplier* and is always positive, whereas the value shown in the UI is a *signed* percentage.
2. The value returned by `getBidModifier()` is `0` whether the UI value is `--` or `-100%`, so you must use `hasBidModifier()` to differentiate between those two cases.

I think that covers everything, but feel free to reopen this issue if you have further questions.

Cheers,
Josh
