### ISSUE TITLE
how to upload multiple records using UploadEnhancedConversionsForWeb

### ISSUE THREAD

**Issue by d3r3ktm** [googleads/google-ads-java#753]
**What is your question?**

I am trying to upload multiple records using UploadEnhancedConversionsForWeb. 
I am getting this "Partial error encountered: 'Too many., at conversion_adjustments[0].user_identifiers'."

May I know how should I go about uploading multiple records?

For example this is the list of records to upload
<email, order id>
abc@gmail.com,1234567890123
def@gmail.com,1234567890124
ghi@gmail.com,1234567890125
jkl@gmail.com,1234567890126
mno@gmail.com,1234567890127 

Attached is the codes that upload the data.

[uploadEnhancedConversions.txt](https://github.com/googleads/google-ads-java/files/13747827/uploadEnhancedConversions.txt)

**Comment by jradcliff** [comment]
Hi,

You should have a separate entry in the request's [`conversion_adjustments`](https://developers.google.com/google-ads/api/reference/rpc/v15/UploadConversionAdjustmentsRequest#conversion_adjustments[]) for each order ID. So for the example you gave:

```
abc@gmail.com,1234567890123
def@gmail.com,1234567890124
ghi@gmail.com,1234567890125
jkl@gmail.com,1234567890126
mno@gmail.com,1234567890127
```

Your request should have one `ConversionAdjustment` with `order_id` set to `1234567890123` and one `UserIdentifier` for `abc@gmail.com`, then another `ConversionAdjustment` with `order_id` set to `1234567890124` and one `UserIdentifier` for `def@gmail.com`, and so on.

Hope that helps!

Josh, Google Ads API Team

**Comment by d3r3ktm** [comment]
Hi Josh

Please pardon my ignorance.
I have tried to create multiple ConversionAdjustment for the request but keep getting compilation errors with the changes I made.
My codes is based on UploadEnhancedConversionsForWeb.java.

Could you help to point out to me how I should create the multiple ConversionAdjustment per request in my code.

Attached is my code that read the data from the file and upload them.
[uploadEnhancedConversions.txt](https://github.com/googleads/google-ads-java/files/13768683/uploadEnhancedConversions.txt)

**Comment by d3r3ktm** [comment]
I think I have managed to create multiple ConversionAdjustment objects per request. Will need to check if the correct data is send in the request.

**Comment by jradcliff** [comment]
Could you let me know if this issue is resolved?

Thanks,
Josh, Google Ads API Team

**Comment by d3r3ktm** [comment]
Yes it is resolved. Thank you.

By the way, would you know how can i get the full logging of the API request and response into the logs?
It is for another issue related to enhanced conversions upload that i have asked in the forum.
I have added the dependency on the log library into xml file (maven).

**Comment by jradcliff** [comment]
Glad to hear the issue is resolved! You can get logging of requests and responses (including successful requests) if you enable the `DEBUG` level of logging for the detail logger named `com.google.ads.googleads.lib.request.detail`. Please refer to the logging guide at https://developers.google.com/google-ads/api/docs/client-libs/java/logging for more information.
