### ISSUE TITLE
Multiple request attempt to modify same resource error when creating  a new RSA Ads

### ISSUE THREAD

**Issue by eliasgrullon** [googleads/google-ads-java#762]
**Describe the bug:**

At a random time when I make a request to create a new RSA ad I get the error multiple request attempt to modify same resource. Which does not make sense because you can't modify concurrently a non existent resource. 

**Steps to Reproduce:**
It's has been hard for me to know what are the exactly steps to reproduce it.  When it happens to me is doing the following: 
1- Create a campaign  with all the necessary to create an ad(campaign, ad groups, keywords, asset, etc.)
2-Send a request to create a RSA Ad.

**Expected behavior:**

Create a RSA Ad without any issue.

**Client library version and API version:**
Client library version: 2.2.0
Google Ads API version: 28.0.0
JDK version:1.8

**Request/Response Logs:**

December 22nd 2023, 13:15:30.033
SUCCESS REQUEST DETAIL.
Request
-------
MethodName: google.ads.googleads.v15.services.AdGroupAdService/MutateAdGroupAds
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=xxxxxx, x-goog-api-client=gl-java/1.8.0_102 gccl/28.0.0 gapic/28.0.0 gax/2.32.0 grpc/1.27.2}
Body: customer_id: "XXXXXX"
operations {
  create {
    status: ENABLED
    ad {
      responsive_search_ad {
        headlines {
          text: "Mold Remediation Services"
        }
        headlines {
          text: "Get Rid Of Toxic Mold"
        }
        headlines {
          text: "Using Plant-Based Products"
        }
        headlines {
          text: "Say Goodbye To Mold"
        }
        headlines {
          text: "Remove Mold For Good"
        }
        descriptions {
          text: "Have peace of mind knowing you live in a healthy home. Learn about the hazards of mold."
        }
        descriptions {
          text: "The most trusted name in the industry. Let our experts screen your home today."
        }
        descriptions {
          text: "Our professional mold remediation services guarantee a safe and healthy home. Book now."
        }
        path1: "mold"
        path2: "remediation"
      }
      final_urls: "http://www.myurl.com"
    }
    ad_group: "customers/XXXXXXX/adGroups/157158297036"
  }
}
partial_failure: true
response_content_type: MUTABLE_RESOURCE

Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,request-id=0B_E1m0y1n1Zs3yFlu9hiQ,date=Fri, 22 Dec 2023 18:15:29 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000)
Body: results {
}
partial_failure_error {
  code: 3
  message: "Multiple requests were attempting to modify the same resource at once. Retry the request., at operations[0]"
  details {
    type_url: "type.googleapis.com/google.ads.googleads.v15.errors.GoogleAdsFailure"
    value: "\nr\n\003\230\004\002\022YMultiple requests were attempting to modify the same resource at once. Retry the request.\"\020\022\016\n\noperations\030\000\022\0260B_E1m0y1n1Zs3yFlu9hiQ"
  }
}

Failure message: null
Status: Status{code=OK, description=null, cause=null}.
 
**Anything else we should know about your project / environment:**

**Comment by jradcliff** [comment]
Hi,

This is an API issue rather than something specific to this client library. Please follow up with our support team using the links at https://developers.google.com/google-ads/api/support.

Thanks,
Josh
