### ISSUE TITLE
Partial Error handling for click conversion uploads

### ISSUE THREAD

**Issue by qhaoran** [googleads/google-ads-java#770]
**What is your question?**
Does `UploadClickConversionsResponse` has the complete errors of one click conversion? If so, how to properly retrieve all the errors? 

Below is my debugging example:
Say we upload 2 click conversions in one `UploadClickConversionsRequest`, and one of them have 2 errors: wrong conversion date time format, unparsable GCLID. I observed the partial failure returned only contains one error. And I always get a empty list of errors by the following code snippet which follows the [partial failure best practice](https://developers.google.com/google-ads/api/docs/best-practices/partial-failures#handle_succeeded_and_failed_operations):

```java
    public List<String> handleResponse(final UploadClickConversionsResponse response) {
        if (response.hasPartialFailureError()) {
            final List<String> partialFailures = new LinkedList<>();
            final int resultSize = response.getResultsCount();
            for (int i = 0; i < resultSize; i++) {
                if (ErrorUtils.getInstance().isPartialFailureResult(response.getResults(i))) {
                    final GoogleAdsFailure googleAdsFailure = ErrorUtils.getInstance()
                            .getGoogleAdsFailure(response.getPartialFailureError());
                    partialFailures.add(parseError(googleAdsFailure, i));
                }
            }
            return partialFailures;
        }
        return Collections.emptyList();
    }

    private String parseError(final GoogleAdsFailure googleAdsFailure,
                                     final int operationIndex) {
        final List<String> errorMessages = new LinkedList<>();
        final List<GoogleAdsError> errors = ErrorUtils.getInstance().getGoogleAdsErrors(operationIndex, googleAdsFailure);
        for (GoogleAdsError error : errors) {
            errorMessages.add(error.getMessage());
        }
        return String.join(",", errorMessages);
    }
```

I debugged locally and found out the problem is at `ErrorUtils.getInstance().getGoogleAdsErrors(operationIndex, googleAdsFailure)`.  The method ([code pointer](https://github.com/googleads/google-ads-java/blob/9b81f3d1a89d66f5600503355cef07435611400a/google-ads-stubs-lib/src/main/java/com/google/ads/googleads/lib/utils/AbstractErrorUtils.java#L113)) checks whether the ErrorPath `isOperationIndex`. For conversion upload response, it's always false as the field name of the error path is `conversion`, see [this method](https://github.com/googleads/google-ads-java/blob/9b81f3d1a89d66f5600503355cef07435611400a/google-ads-stubs-lib/src/main/java/com/google/ads/googleads/lib/utils/AbstractErrorUtils.java#L248-L250).

And then I came across this [code example](https://developers.google.com/google-ads/api/docs/conversions/upload-clicks#code_example) dedicated to click conversion upload, and saw it doesn't try to get list of errors related to on click conversion. So I'm guessing Google doesn't return full errors but any one of them.

```java
// Prints any partial errors returned.
    if (response.hasPartialFailureError()) {
      GoogleAdsFailure googleAdsFailure =
          ErrorUtils.getInstance().getGoogleAdsFailure(response.getPartialFailureError());
      googleAdsFailure
          .getErrorsList()
          .forEach(e -> System.out.println("Partial failure occurred: " + e.getMessage()));
    }
```

But the API support (case # `ref:!00D1U01174p.!5004Q02rXHK6:ref`) replied me: *Kindly note that Google Ads API returns all the errors related to the click conversions in case multiple errors too.*

I'm confusing whether Google returns list of errors for one click conversion, or only one of errors? And what's the correct approach to handle the partial failure of click conversion uploading.

**Comment by jradcliff** [comment]
Hi,

Thanks for providing such a detailed issue report! I'm fairly confident this is a bug in the code you highlighted. I'm looking into this further and will also check if there are any other methods that could run into this issue.

Cheers,
Josh, Google Ads API Team

**Comment by qhaoran** [comment]
Thanks for looking into this, do we have any update?

**Comment by jradcliff** [comment]
Your assessment was correct. We'll fix the utility in the next release of the library.

In the meantime, here's a modified version of the [UploadOfflineConversion](https://github.com/googleads/google-ads-java/blob/main/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/UploadOfflineConversion.java) sample that properly finds the errors for each conversion:

```
      UploadClickConversionsResponse response =
          conversionUploadServiceClient.uploadClickConversions(
              UploadClickConversionsRequest.newBuilder()
                  .setCustomerId(Long.toString(customerId))
                  .addConversions(clickConversion)
                  // Enables partial failure (must be true).
                  .setPartialFailure(true)
                  .build());

      // Prints any partial errors returned.
      if (response.hasPartialFailureError()) {
        GoogleAdsFailure googleAdsFailure =
            ErrorUtils.getInstance().getGoogleAdsFailure(response.getPartialFailureError());

        // WORKAROUND: Builds a map from conversion/operation index to list of GoogleAdsErrors.
        SortedMap<Integer, List<GoogleAdsError>> errorsByIndex = new TreeMap<>();
        for (GoogleAdsError googleAdsError : googleAdsFailure.getErrorsList()) {
          // Checks if the GoogleAdsError has a FieldPathElement that identifies a conversion index.
          Optional<FieldPathElement> conversionIndexElement =
              googleAdsError.getLocation().getFieldPathElementsList().stream()
                  .filter(elm -> "conversions".equals(elm.getFieldName()) && elm.hasIndex())
                  .findAny();
          if (conversionIndexElement.isPresent()) {
            // Adds the GoogleAdsError to the list of errors for the conversion index found in the
            // FieldPathElement.
            Integer conversionIndex = conversionIndexElement.get().getIndex();
            errorsByIndex
                .computeIfAbsent(conversionIndex, k -> new ArrayList<>())
                .add(googleAdsError);
          }
        }

        // Constructs a protocol buffer printer that will print error details in a concise format.
        Printer errorPrinter = JsonFormat.printer().omittingInsignificantWhitespace();

        for (int operationIndex = 0;
            operationIndex < response.getResultsCount();
            operationIndex++) {
          ClickConversionResult conversionResult = response.getResults(operationIndex);

          if (ErrorUtils.getInstance().isPartialFailureResult(conversionResult)) {
            // Prints the errors for the failed operation.
            System.out.printf("Operation %d failed with the following errors:%n", operationIndex);
            // WORKAROUND: Uses the map constructed above instead of the error utility.
            for (GoogleAdsError resultError :
                errorsByIndex.getOrDefault(operationIndex, Collections.emptyList())) {
              // Prints the error with newlines and extra spaces removed.
              System.out.printf("  %s%n", errorPrinter.print(resultError));
            }
          } else {
            System.out.printf("Operation %d succeeded.%n", operationIndex);
          }
        }
      }
    }
```

Thanks again for highlighting this problem!

Cheers,
Josh, Google Ads API Team

**Comment by qhaoran** [comment]
Thanks for the fix!

**Comment by qhaoran** [comment]
Hi @jradcliff 

When is the next release? I saw the [history release](https://github.com/googleads/google-ads-java/releases) is not by some fix schedule. It would be great to have an ETA of next release. Thanks.

**Comment by jradcliff** [comment]
I'm planning on cutting a release in about 2 weeks.

**Comment by qhaoran** [comment]
Hi @jradcliff 

Thanks for the fix release. I can get the error returned by the utility class of `30.0.0` version. Just want to clarify one question. I'm using this click conversion for testing:

```java
                ClickConversion.newBuilder()
                        // random GCLID, not recognized by google
                        .setGclid("985342159875")
                        .setConversionAction("customers/5203322718/conversionActions/5203322718")
                        // wrong timestamp format
                        .setConversionDateTime("2024-01-01")
                        .setCurrencyCode("USD")
                        .setConversionValue(12.45676).build());
```

And I expect two partial failures returned `UNPARSEABLE_GCLID` and `INVALID_STRING_DATE_TIME_SECONDS_WITH_OFFSET`. But the utility method `ErrorUtils.getInstance().getGoogleAdsErrors(index, googleAdsFailure)` only returns one. My partial failure handling code is (which is basically the same as the [example](https://github.com/googleads/google-ads-java/blob/1dd328c884b6d06ba606082e06a28d457b4ea14d/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/UploadOfflineConversion.java#L293-L309) you shared):

```java
public static List<String> handleResponse(final UploadClickConversionsResponse response) {
        if (response.hasPartialFailureError()) {
            final GoogleAdsFailure googleAdsFailure = ErrorUtils.getInstance()
                    .getGoogleAdsFailure(response.getPartialFailureError());
            final List<String> partialFailures = new LinkedList<>();
            for (int index = 0; index < response.getResultsCount(); index++) {
                final ClickConversionResult clickConversionResult = response.getResults(index);
                if (ErrorUtils.getInstance().isPartialFailureResult(clickConversionResult)) {
                   // Expect this `ErrorUtils.getInstance().getGoogleAdsErrors(index, googleAdsFailure)` method call 
                   // returns both UNPARSEABLE_GCLID and INVALID_STRING_DATE_TIME_SECONDS_WITH_OFFSET, 
                   // but only returns the timestamp error
                    for (GoogleAdsError error : ErrorUtils.getInstance().getGoogleAdsErrors(index, googleAdsFailure)) {
                        partialFailures.add(error.getMessage());
                    }
                }
            }
            return partialFailures;
        }
        return Collections.emptyList();
    }
```
For this specific case, does google ads lib return both errors? and can you share a test case that the lib returns multiple errors? 

BTW, I was using a test account for above test. 

Thanks!

**Comment by jradcliff** [comment]
Hi @qhaoran ,

So far, I have not been able to get the *API* to report more than one error per `ClickConversion`. Whether you get multiples or not depends on the underlying implementation of each API service.

However, if the API *did* report multiple errors for the same `ClickConversion`, the library would work as expected, and you'd get multiple iterations in the loop you highlighted:

```
for (GoogleAdsError error : ErrorUtils.getInstance().getGoogleAdsErrors(index, googleAdsFailure)) {
  partialFailures.add(error.getMessage());
}
```

We test for this in [`AbstractErrorUtilsTest.getGoogleAdsErrors_duplicates_whenErrorsDiffer()`](https://github.com/googleads/google-ads-java/blob/1dd328c884b6d06ba606082e06a28d457b4ea14d/google-ads/src/test/java/com/google/ads/googleads/lib/utils/AbstractErrorUtilsTest.java#L155). In that test, there are multiple errors for the same operation index but with distinct paths after the `conversions` portion, and the test verifies that those errors are all returned.

Cheers,
Josh

**Comment by qhaoran** [comment]
Got it, thanks for the explanation.
