### ISSUE TITLE
Cannot get started with Java (Mayven) 

### ISSUE THREAD

**Issue by riotechnologies** [googleads/google-ads-java#772]
Hello 
We had no problem getting all the relevant credentials. 
- The getting started documents usually contains "credentials" in the top - and "coding" as the fourth step: 

https://developers.google.com/google-ads/api/docs/get-started/introduction
![Screenshot at Jan 31 12-06-56](https://github.com/googleads/google-ads-java/assets/133634757/25852256-5a51-4dc5-a865-0132e444033c)

However when approaching the last step - to start coding - we were not able to get started. 
Our problem is when approaching the client libraries (coding) part  
The first few steps of setting up a project and getting credentials seems to go well - 
As we selected Java, we set up a new Maven project (as we understand this is Google's recommendation for Java). 
It is currently a very clean "hello world" .

However when trying to interact with Google Ads Api examples - Specifically in this part : 
https://developers.google.com/google-ads/api/docs/client-libs/java/getting-started

![Screenshot at Jan 31 12-09-18](https://github.com/googleads/google-ads-java/assets/133634757/8d461f2b-dd31-43bd-9c7b-39c6b47ff5c3)

We cannot run the getCampaigns initial example. 
When I try running the first example (of getCampaigns) - I get several errors in my IDE, so I am not able to run the example .

![image (3)](https://github.com/googleads/google-ads-java/assets/133634757/137d9ab6-4c00-4e70-a4a5-ec688fd73b54)

So at this point I think that I am missing something with the project initial installation-
I guess this is probably a simple fix of dependencies - but it would be great if you can help us with it. 

Thanks and cheers!

**Comment by jradcliff** [comment]
Hi,

I noticed that you created your own project and copied the sample into it, but that's causing issues because the classes you're missing are utility classes in the `google-ads-examples` module. I recommend cloning this repository, then creating a project in your IDE based on the root `google-ads-java` directory. The IDE should recognize it's a Gradle project and build it properly, and then you can run the samples in the project's `google-ads-examples` module as outlined in [the guide](https://developers.google.com/google-ads/api/docs/client-libs/java/getting-started#explore_other_examples).

If instead you want to run the samples from your own project that has a dependency on `google-ads`, you'll need to remove the references to `com.google.ads.examples.*` classes, as well as `com.beust.jcommander.Parameter`. The easiest way to do this is to just copy the `runExample` method into your own class. You'll need to copy the portion of `main` that builds a `GoogleAdsClient` as well.

Thanks,
Josh, Google Ads API Team

**Comment by riotechnologies** [comment]
Hi Josh and thanks for the response! 

I actually thought that its Maven's job to include all the required dependencies. Ideally it would be great to run it in my own project, however If starting from fresh is the recommended way I can also do that. 

When trying to clone the repository - I encountered an error, I would really appreciate if you can help me find what I'm doing wrong in order to get started. 

Attaching the steps I have taken : 

![Screenshot at Feb 13 20-07-07](https://github.com/googleads/google-ads-java/assets/133634757/7c3a6798-9d9a-4570-bb27-a889cb0bbeed)

![Screenshot at Feb 13 20-06-27](https://github.com/googleads/google-ads-java/assets/133634757/fec51674-58ff-43d0-b642-027bd9c1dd11)
![Screenshot at Feb 13 20-05-39](https://github.com/googleads/google-ads-java/assets/133634757/b1a3bf8d-c294-49c9-b9e7-f11556127e63)

![Screenshot at Feb 13 20-05-09](https://github.com/googleads/google-ads-java/assets/133634757/4e809760-ef04-4a90-bcea-8ae50c085a61)


Thanks and best regards!

**Comment by jradcliff** [comment]
Hmmm...I'm not sure why the tool you're using is producing errors. Perhaps a more straightforward approach would be to copy the snippets at https://developers.google.com/google-ads/api/docs/get-started/make-first-call#make_an_api_call_2 into a new file in your own project, similar to what you started with.

For example, here's a version of the `GetCampaigns` example that does not rely on the `google-ads-examples` project. To run this, you'll need to set up your `ads.properties` file as described in the guide, and replace `INSERT_CUSTOMER_ID_HERE` with your customer ID (without dashes).

```
import com.google.ads.googleads.lib.GoogleAdsClient;
import com.google.ads.googleads.v15.services.GoogleAdsRow;
import com.google.ads.googleads.v15.services.GoogleAdsServiceClient;
import com.google.ads.googleads.v15.services.SearchGoogleAdsStreamRequest;
import com.google.ads.googleads.v15.services.SearchGoogleAdsStreamResponse;
import com.google.api.gax.rpc.ServerStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class GetCampaigns {
  public static void main(String[] args) throws Exception {
    GoogleAdsClient googleAdsClient;
    try {
      googleAdsClient = GoogleAdsClient.newBuilder().fromPropertiesFile().build();
      new GetCampaigns().runExample(googleAdsClient, Long.parseLong("INSERT_CUSTOMER_ID_HERE"));
    } catch (FileNotFoundException fnfe) {
      System.err.printf(
          "Failed to load GoogleAdsClient configuration from file. Exception: %s%n", fnfe);
      System.exit(1);
    } catch (IOException ioe) {
      System.err.printf("Failed to create GoogleAdsClient. Exception: %s%n", ioe);
      System.exit(1);
    }
  }

  private void runExample(GoogleAdsClient googleAdsClient, long customerId) {
    try (GoogleAdsServiceClient googleAdsServiceClient =
        googleAdsClient.getLatestVersion().createGoogleAdsServiceClient()) {
      String query = "SELECT campaign.id, campaign.name FROM campaign ORDER BY campaign.id";
      // Constructs the SearchGoogleAdsStreamRequest.
      SearchGoogleAdsStreamRequest request =
          SearchGoogleAdsStreamRequest.newBuilder()
              .setCustomerId(Long.toString(customerId))
              .setQuery(query)
              .build();

      // Creates and issues a search Google Ads stream request that will retrieve all campaigns.
      ServerStream<SearchGoogleAdsStreamResponse> stream =
          googleAdsServiceClient.searchStreamCallable().call(request);

      // Iterates through and prints all of the results in the stream response.
      for (SearchGoogleAdsStreamResponse response : stream) {
        for (GoogleAdsRow googleAdsRow : response.getResultsList()) {
          System.out.printf(
              "Campaign with ID %d and name '%s' was found.%n",
              googleAdsRow.getCampaign().getId(), googleAdsRow.getCampaign().getName());
        }
      }
    }
  }
}
```

**Comment by jradcliff** [comment]
Glad to hear that worked. When copying any example to your own project, I'd recommend copying everything _except_ the `main` method and the `Params` class declaration. Equivalently, you could copy the `runExample` method and any methods that method calls. Either approach will limit the types referenced to only those in `google-ads`, and exclude those in `google-ads-examples`.
