### ISSUE TITLE
How to use GenerateKeywordIdeas? 

### ISSUE THREAD

**Issue by z0mg** [googleads/google-ads-java#776]
**What is your question?**

I'm trying to use the GenerateKeywordIdeas runExample method, but I get this error:

```
Request ID _YO5i_Hgq8sD4h7DVEGTGg failed due to GoogleAdsException. Underlying errors:
  Error 0: error_code {
  authorization_error: DEVELOPER_TOKEN_NOT_APPROVED
}
message: "The developer token is only approved for use with test accounts. To access non-test accounts, apply for Basic or Standard access."
```

I have a gmail account with an Ads campaign on it, I made an MCC account for the same name and I listed that same account as a test user for my application.  I used GenerateUserCredentials, saved the file in home\ads.properties, it gets loaded properly. 

![image](https://github.com/googleads/google-ads-java/assets/4804054/b9b19162-510e-42f2-8206-c224faa42bb9)

![image](https://github.com/googleads/google-ads-java/assets/4804054/0697e31d-9910-472c-a7f7-06c77da1986e)

What am I doing wrong?

**Comment by jradcliff** [comment]
Hi,

Your developer token's **Access level** is **Test Account**, so you can only use it right now for API requests to test accounts, as described in the [getting started guide]. Please read through that guide for details on how to complete the token application process.

Also, please avoid sharing your developer token publicly. Although your screenshot doesn't have the *complete* developer token, I would generate a new one using **Reset token** on that page.

Thanks,
Josh, Google Ads API Team

[getting started guide]: https://developers.google.com/google-ads/api/docs/get-started/dev-token#:~:text=After%20you%27ve%20completed%20the%20application%20process%2C%20the%20developer%20token%20shows%20up%20in%20your%20API%20Center%20with%20a%20Pending%20Approval%20status.%20Your%20developer%20token%20now%20has%20Test%20Access%20level%20and%20you%20can%20start%20making%20API%20calls%20against%20test%20accounts.

**Comment by z0mg** [comment]
Hi Josh,

Thanks for the link, but it doesn't help - I followed all those steps and ended up here. I have a test Developer token that I'm trying to use with a Test account. 

The OAuth lists the email address as a test user and I have an Ads test account for that address as well: 

![image](https://github.com/googleads/google-ads-java/assets/4804054/b6aca24d-edb2-43b9-88e0-4fc84be3f813)

**Comment by jradcliff** [comment]
Ah, I see. It seems something's wrong with either your `login-customer-id` or `customer_id` in your request because that error indicates that the request is attempting to act up on a *non*-test account. Could you check if you're setting them as follows?

* `customer_id` should be the Test account from your last screenshot.
* `login-customer-id` should be either the Test account or its manager. This should match the customer ID to which the user has *direct* access.

Thanks,
Josh

**Comment by z0mg** [comment]
Hi again Josh,

Thanks for taking the time to help me out. Long story short, the customerId was hardcoded to the main one, not the test manager. Using the ID of a test manager worked, no need for a test user under the test manager and no need to specify this: 

`# api.googleads.loginCustomerId=INSERT_LOGIN_CUSTOMER_ID`

I was getting this error: 

```
Request ID eOghnbEXou058QtpRJde2g failed due to GoogleAdsException. Underlying errors:
  Error 0: error_code {
  authorization_error: USER_PERMISSION_DENIED
}
message: "User doesn\'t have permission to access customer. Note: If you\'re accessing a client customer, the manager\'s customer id must be set in the \'login-customer-id\' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid"
```


BTW in case anyone else is reading, this helped clear things up a lot: https://developers.google.com/google-ads/api/docs/best-practices/test-accounts

I was getting this

**Comment by jradcliff** [comment]
Glad to hear that it's working now and that the guide was helpful!

Regarding `loginCustomerId`, if you don't specify that then it defaults to using the `customer_id` of the request. This will work as long as the user whose credentials you're using has _direct_ access to the `customer_id`, so I'm guessing that was the case for your setup.

Cheers,
Josh
