### ISSUE TITLE
Specifying or detecting the average CPC currency used by KeywordPlanHistoricalMetrics / getAverageCpcMicros

### ISSUE THREAD

**Issue by z0mg** [googleads/google-ads-java#780]
I'm using this snippet to get the average CPC for a keyword. The problem is that the currency isn't specified. Is it AUD since the target location is Australia? can I ask for it to be returned in a specific currency for any target location, let's say USD? 

```
    HistoricalMetricsOptions options = HistoricalMetricsOptions.newBuilder().setIncludeAverageCpc(true).build();

    GenerateKeywordHistoricalMetricsRequest request = GenerateKeywordHistoricalMetricsRequest.newBuilder()
        .setCustomerId(String.valueOf(customerId))
        .addAllKeywords(Arrays.asList("tennis racquets"))
        .addGeoTargetConstants(ResourceNames.geoTargetConstant(2036)) // australia
        .setKeywordPlanNetwork(KeywordPlanNetwork.GOOGLE_SEARCH)
        .setHistoricalMetricsOptions(options)
        .build();

    try (KeywordPlanIdeaServiceClient keywordPlanIdeaServiceClient = googleAdsClient.getLatestVersion().createKeywordPlanIdeaServiceClient())
    {
      GenerateKeywordHistoricalMetricsResponse response = keywordPlanIdeaServiceClient.generateKeywordHistoricalMetrics(request);

      for (GenerateKeywordHistoricalMetricsResult result : response.getResultsList())
      {
        KeywordPlanHistoricalMetrics metrics = result.getKeywordMetrics();
        System.out.println("cpc: " + metrics.getAverageCpcMicros() / 1000000f);
```

**Comment by jradcliff** [comment]
The currency should be the currency of the Google Ads account, which you can retrieve from the [`Customer.currency_code`](https://developers.google.com/google-ads/api/reference/rpc/v16/Customer#currency_code) field. The API does not support overriding the currency for that request.

If you have additional questions about API functionality that is not specifically related to the library for Java, please reach out to our API support using the form at https://developers.google.com/google-ads/api/support/contact.

Thanks,
Josh
