### ISSUE TITLE
Assistance Needed: Configuration Issue with Google Ads Java Library in IntelliJ IDEA

### ISSUE THREAD

**Issue by OICUSERICX** [googleads/google-ads-java#787]
We are facing challenges with adding campaigns while configuring the Google Ads Java Library in Intellij IDEA using the Gradle builder. Despite trying different methods, such as verifying the presence of the ads.properties file in the home directory and importing all dependencies, we have been unable to resolve the issue.

The following error persists:
examples
beust
joda
params
DateTime

Even after attempting to import the necessary classes using commands like:
These lines appear in red, indicating that the imports are unsuccessful.

import static com.google.ads.googleads.examples.utils.CodeSampleHelper.getPrintableDateTime;
import com.beust.jcommander.Parameter;
import com.google.ads.googleads.examples.utils.ArgumentNames;
import com.google.ads.googleads.examples.utils.CodeSampleParams;
import org.joda.time.DateTime;

Versions:
Client library version: google-ads-examples
JDK version: 11.0.18

Please find the attached file for the request code.
[Googleads_request_1.txt](https://github.com/googleads/google-ads-java/files/14788287/Googleads_request_1.txt)
also find dependencies here:
dependencies {
    implementation ("com.google.api-ads:google-ads:30.0.0")
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

Please prioritize your attention to resolving this issue promptly. Your assistance in addressing this matter is greatly appreciated.

**Comment by jradcliff** [comment]
Looking at your source code, you can just remove the following imports since they aren't used:

```
import com.beust.jcommander.Parameter;
import com.google.ads.googleads.examples.utils.ArgumentNames;
import com.google.ads.googleads.examples.utils.CodeSampleParams;
```

To resolve the dependency for:

```
import org.joda.time.DateTime;
```

add the following to your `dependencies` list:

```
  implementation("joda-time:joda-time:2.8.2")
```

Thanks,
Josh, Google Ads API Team

**Comment by OICUSERICX** [comment]
Hi Team,

Thanks for the support, As suggested added dependencies but we are still encountering additional issues with
examples.utils.CodeSampleHelper.getPrintableDateTime
params.customerId
getPrintableDateTime()


Attaching the code for your reference.
[Googleads_request_2.txt](https://github.com/googleads/google-ads-java/files/14800706/Googleads_request_2.txt)

Regards,
OIC Team

**Comment by jradcliff** [comment]
Hi,

You still have the following static import at the top:

`import static com.google.ads.googleads.examples.utils.CodeSampleHelper.getPrintableDateTime;`

If you remove that, you'll also need to adjust line 95 and replace the call to `getPrintableDateTime` with something that makes each campaign's name unique if you run the sample multiple times:

`.setName("Interplanetary Cruise Budget #" + getPrintableDateTime())`

Thanks,
Josh

**Comment by OICUSERICX** [comment]
Hi Josh,

Thanks for the clarification now i am getting another error please find the in attached document.
[Googleads_request_3.txt](https://github.com/googleads/google-ads-java/files/14812752/Googleads_request_3.txt)



**ERROR:**
Files\JetBrains\IntelliJ IDEA Community Edition 2023.3.5\lib\idea_rt.jar" org.example.AddCampaigns 9715597582
Connected to the target VM, address: '127.0.0.1:52076', transport: 'socket'
Error: Unable to initialize main class org.example.AddCampaigns
Caused by: java.lang.NoClassDefFoundError: com/google/ads/googleads/v16/errors/GoogleAdsException
Disconnected from the target VM, address: '127.0.0.1:52076', transport: 'socket'

Process finished with exit code 1

**Comment by OICUSERICX** [comment]
Hi Josh,

Below are the dependencies we are currently using:
We are utilizing IntelliJ IDEA with Java version 11.0.18 and employing the Gradle builder.

**Dependencies**
plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation ("com.google.api-ads:google-ads:30.0.0")
    implementation("joda-time:joda-time:2.8.2")
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

**Comment by jradcliff** [comment]
Hi,

I just used your `Googleads_request_3.txt` [source file](https://github.com/googleads/google-ads-java/issues/787#issuecomment-2028315102) to create a Gradle project with a `build.gradle` matching your previous comment, and I ran the `AddCampaigns` example without issue in IntelliJ IDEA.

What happens if you run `./gradlew build` from your project's root directory? Does it succeed?

Also, could you try running your sample from the command line? To do this, please add the following line in your `plugins` section:

```
  id: 'application'
```

and add the following section:

```
application {
    mainClass = 'org.example.AddCampaigns'
}
```

Then you can run the example from your project directory using:

```
./gradlew run --args=YOUR_CUSTOMER_ID
```

Thanks,
Josh

**Comment by OICUSERICX** [comment]
Hi Josh,

Please find the outcomes here:

When I ran ./gradlew build from the project's root directory, it
succeeded. Below are the logs for your reference

8:58:11 PM: Executing 'build'...

> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :jar UP-TO-DATE
> Task :startScripts
> Task :distTar
> Task :distZip
> Task :assemble
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build

BUILD SUCCESSFUL in 12s
5 actionable tasks: 4 executed, 1 up-to-date
8:58:24 PM: Execution finished 'build'.

--------------------
gradlew run --args=9715597582

> Task :run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for
further details.
<=========----> 75% EXECUTING [3m 37s]
> :run

**Comment by jradcliff** [comment]
Hi,

What was the end result of running `./gradlew run...`? The output from your last reply only shows it reached 75% progress:

```
gradlew run --args=xxxxx

> Task :run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for
further details.
<=========----> 75% EXECUTING [3m 37s]
```

FWIW, if you expand your project in IntelliJ it should look something like this:

![image](https://github.com/googleads/google-ads-java/assets/6033175/b6bb6682-e660-49cb-af53-6c0ba0e2ed39)

Thanks,
Josh

**Comment by OICUSERICX** [comment]
Hi Josh,

After executing the command gradlew run --args=xxxxx, the process
seems to be stuck as it has been more than 5 minutes without any
progress.

> Task :run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for
further details.
<=========----> 75% EXECUTING [6m 22s]
> :run

**Comment by OICUSERICX** [comment]
Hello Josh,

The above mentioned all the external libraries have been configured in our project, although it's throwing errors. Kindly review and update accordingly.

<img width="360" alt="Screenshot_36" src="https://github.com/googleads/google-ads-java/assets/151531163/fba226f0-6285-487b-b291-65ca039dda26">

**Comment by jradcliff** [comment]
Hi,

> After executing the command gradlew run --args=xxxxx, the process
seems to be stuck as it has been more than 5 minutes without any
progress.

Have you confirmed that you have valid credentials set in your `ads.properties` file in your home directory as described in https://developers.google.com/google-ads/api/docs/client-libs/java/getting-started#configure_the_client_library_with_your_credentials? If the refresh token is invalid, the Google Auth library will keep retrying.

You can check if this is the cause by adding the `--info` argument as follows:

```
./gradlew --info run --args=xxx
```

If you see the following message printed to the console, then your `ads.properties` is not configured correctly.

```
Status: Status{code=UNAVAILABLE, description=Credentials failed to obtain metadata, 
  cause=com.google.auth.oauth2.GoogleAuthException: 
  com.google.api.client.http.HttpResponseException: 400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```

You can create valid credentials by following our [OAuth guide](https://developers.google.com/google-ads/api/docs/client-libs/java/oauth-web) or [using the OAuth Playground](https://developers.google.com/google-ads/api/docs/oauth/playground).

Thanks,
Josh

**Comment by OICUSERICX** [comment]
Hello Team,

We are awaiting the resolution. Please provide an update.

**Comment by jradcliff** [comment]
Please add the following to your dependencies and issue the `gradlew --info run --args=XXX` command again.

```
runtimeOnly 'org.apache.logging.log4j:log4j-slf4j-impl:2.16.0'
```

This will provide additional logging to help debug the problem.

Thanks,
Josh

**Comment by OICUSERICX** [comment]
Hi,

We came to know that customer match implementation will suites our requirement. So we are currently working on integrating customer relationship management (CRM) data in bulk to create a user list.

while using the below git library: https://github.com/googleads/google-ads-java/blob/main/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/AddCustomerMatchUserList.java

we are facing the below errors:

Request
-------
MethodName: google.ads.googleads.v16.services.UserListService/MutateUserLists
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=9715597582, x-goog-api-client=gl-java/11.0.18__Oracle-Corporation__18.9 gccl/30.0.0 gapic/30.0.0 gax/2.43.0 grpc/1.61.1}
Body: customer_id: "9715597582"
operations {
  create {
    crm_based_user_list {
      upload_key_type: CONTACT_INFO
    }
    name: "Customer Match list #85e9d235-95e6-400b-aa6b-f3cd591a02d3"
    description: "A list of customers that originated from email addresses"
    membership_life_span: 30
  }
}


Response
--------
Headers: null
Body: null
Failure message: null
Status: Status{code=UNAVAILABLE, description=Credentials failed to obtain metadata, cause=com.google.auth.oauth2.GoogleAuthException: com.google.api.client.http.HttpResponseException: 401 Unauthorized
POST https://oauth2.googleapis.com/token
	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:127)
	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:143)
	at com.google.auth.oauth2.UserCredentials.doRefreshAccessToken(UserCredentials.java:273)
	at com.google.auth.oauth2.UserCredentials.refreshAccessToken(UserCredentials.java:178)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:270)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:267)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:635)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.api.client.http.HttpResponseException: 401 Unauthorized
POST https://oauth2.googleapis.com/token
	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
	at com.google.auth.oauth2.UserCredentials.doRefreshAccessToken(UserCredentials.java:271)
	... 9 more
}.
Disconnected from the target VM, address: '127.0.0.1:56563', transport: 'socket'

Process finished with exit code 130


Please find 
[AddCustomerMatchUserList_request2.txt](https://github.com/googleads/google-ads-java/files/14885215/AddCustomerMatchUserList_request2.txt)
the attached file for the request code.

**Comment by jradcliff** [comment]
That error means that the OAuth credentials you are using are not valid. A few possible causes of this are:

1. The values for `api.googleads.clientId`, `api.googleads.clientSecret`, and `api.googleads.refreshToken` in your `~/ads.properties` file are not set correctly. Please make sure that you're setting these to the same client ID, client secret, and *refresh* token you used and got back in the OAuth Playground.
1. The refresh token you have in your `~/ads.properties` file for `api.googleads.refreshToken` has been [revoked](https://developers.google.com/identity/protocols/oauth2#expiration). This seems unlikely, but worth checking.

Thanks,
Josh

**Comment by OICUSERICX** [comment]
Hi,

I tried again to generate new OAuth refresh token, Is there any document for crosschecking the way iam doing is correct or not for generating access token/ refresh token for Java clint librarys.

Thankyou.

**Comment by jradcliff** [comment]
Hi,

We have a YouTube playlist
https://youtube.com/playlist?list=PLKByxjzUC-N9gWKMqpi5S0WIVc4o_Ukdj&si=YhCIool7Qu0Kpbi1
that walks through generating credentials and seeing up the configuration
file. In particular, https://youtu.be/NaBfgDZDOEs?si=2_4wbiGPBe8sHV6k
covers the latter.

Thanks

**Comment by OICUSERICX** [comment]
Hi Team,

While we have succeeded in creating a CRM-based user list, we're currently facing difficulties in passing CRM user IDs or any third-party user IDs to the created user list. We need assistance on how to add users to CRM based user list with CRM IDs. Your help would be much appreciated.

**Comment by jradcliff** [comment]
Please reach out to Google Ads API support by filling out the form at https://developers.google.com/google-ads/api/support/contact.
