### ISSUE TITLE
Assistance Needed: Using OfflineUserDataJobService in Local Java IDEA

### ISSUE THREAD

**Issue by OICUSERICX** [googleads/google-ads-java#789]
Dear Team,

I hope this email finds you well. We are reaching out to seek guidance on utilizing the OfflineUserDataJobService within our local Java Integrated Development Environment (IDEA) using Intellij with the Gradle builder.

Our team is eager to integrate the OfflineUserDataJobService functionality into our project, but we are facing some challenges in setting up and implementing the necessary components within our development environment.

Could you please assist us by providing detailed instructions or guidance on how to set up and use the OfflineUserDataJobService in a local Java IDEA environment, specifically using Intellij with the Gradle builder? Any resources, documentation, or steps you can provide would be greatly appreciated.

We believe that with your assistance, we can effectively integrate this service into our project and leverage its capabilities to enhance the application.

Thank you very much for your attention to this matter. We look forward to your prompt response and support.

Best regards,
OIC Team

**Comment by jradcliff** [comment]
Hi,

Please refer to our detailed, [step-by-step guide with code samples](https://developers.google.com/google-ads/api/docs/remarketing/audience-segments/customer-match/get-started).

The full Java code sample for that guide is in this library at [google-ads-java/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/AddCustomerMatchUserList.java](https://github.com/googleads/google-ads-java/blob/main/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/AddCustomerMatchUserList.java).

Thanks,
Josh, Google Ads API Team
