### ISSUE TITLE
How to log more details about requests?

### ISSUE THREAD

**Issue by z0mg** [googleads/google-ads-java#796]
The folks at Google Ads API Support have asked for more details in order to handle my issue. The problem is I can't get the Ads library to log everything, this is all I have: 

> INFO   | jvm 1    | 2024/05/08 10:14:20 | INFO: May 8, 2024 10:14:20 AM com.google.ads.googleads.lib.logging.RequestLogger logAtLevel
> INFO   | jvm 1    | 2024/05/08 10:14:20 | SUCCESS REQUEST SUMMARY. Method: google.ads.googleads.v15.services.KeywordPlanIdeaService/GenerateKeywordHistoricalMetrics, Endpoint: googleads.googleapis.com:443, CustomerID: xxxxxx, RequestID: yyyyy, ResponseCode: OK, Fault: null.

I followed the steps from [Java Util Logging](https://developers.google.com/google-ads/api/docs/client-libs/java/logging?hl=en), so I start java with -Djava.util.logging.config.file=/xxx/jdk-logger.properties

The jdk-logger.properties contains: 

> handlers=java.util.logging.ConsoleHandler
> com.google.ads.googleads.lib.logging.request.level=FINE
> com.google.ads.googleads.lib.logging.request.level=FINE
> java.util.logging.ConsoleHandler.level=FINE
> java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

How can I log the complete details about requests?

**Comment by jradcliff** [comment]
Hi,

The loggers need to match the **Log name** from [the guide](https://developers.google.com/google-ads/api/docs/client-libs/java/logging#logging_layout_and_functionality) you mentioned.

Could you try changing the 2nd and 3rd lines to the following?

```
com.google.ads.googleads.lib.request.summary.level=INFO
com.google.ads.googleads.lib.request.detail.level=FINE
```

Thanks,
Josh, Google Ads API Team

**Comment by jradcliff** [comment]
Hi,

I'm closing this under the assumption that my last suggestion fixed the issue, but feel free to reopen the issue if you're still having trouble with the logging config.

Thanks,
Josh

**Comment by z0mg** [comment]
Hi Josh, 

Thanks for your suggestion. It didn't work, the culprit being a service wrapper (tanuki) that I couldn't get to play nice and had to bypass.

I eventually fixed the issue by using log4j with this log4j.properties file: 

```
logDir=/usr/local/service

log4j.rootLogger=DEBUG, log1

log4j.appender.log1=org.apache.log4j.DailyRollingFileAppender
log4j.appender.log1.layout=org.apache.log4j.PatternLayout
log4j.appender.log1.layout.ConversionPattern=%d{MM/dd/yyyy hh:mm:ss a}|%-5p|%-30c{1}| %m%n
log4j.appender.log1.DatePattern='.'yyyy-MM-dd
log4j.appender.log1.File=${logDir}/ads_api.log
log4j.appender.log1.append=true

log4j.appender.log1.filter.1=org.apache.log4j.varia.StringMatchFilter
log4j.appender.log1.filter.1.StringToMatch=REQUEST
log4j.appender.log1.filter.1.AcceptOnMatch=true
log4j.appender.log1.filter.2=org.apache.log4j.varia.DenyAllFilter

log4j.logger.com.google.ads.googleads.lib.request.summary=ALL
log4j.logger.com.google.ads.googleads.lib.request.detail=ALL
```

And of course using this property: 

`-Dlog4j.configuration=log4j.properties`

Disabling log truncation worked using `-Dapi.googleads.maxLogMessageLength=-1`:

```
    monthly_search_volumes {
      month: JANUARY
      year: 2024
      monthly_searches: 10
    }
    monthly_search_volumes {
      month: FEB
... TRUNCATED. See README.md to configure/disable log truncation.
```

Thank you again.
