### ISSUE TITLE
Unable to create ConversionAction : ArrayIndexOutOfBoundsException while evaluating ConversionAction.toString()

### ISSUE THREAD

**Issue by atienon** [googleads/google-ads-java#801]
Hi,

with com.google.ads.googleads.v17: (or v16)

![image](https://github.com/googleads/google-ads-java/assets/172509561/1ea46c76-5b98-4a49-8b46-5c4d4850f5b6)

while com.google.ads.googleads.v15:

![image](https://github.com/googleads/google-ads-java/assets/172509561/d4dd88fd-46ce-4f47-b0c4-b80f9686ecb5)

This blocks conversionAction creation. Does anyone have any idea?

thanks

**Comment by jradcliff** [comment]
Hi,

Could you check which version of `protobuf-java` you are using? Release 32.0.0 of the Google Ads library expects `protobuf-java` version `3.25.3`.

See [this section of our guide](https://developers.google.com/google-ads/api/docs/client-libs/java/advanced-usage#shadow_dependencies) for how to get a dependency report from Maven or Gradle.

Thanks,
Josh, Google Ads API Team

**Comment by atienon** [comment]
The solution works, thank you very much **Josh**!

Antoine.

**Comment by jradcliff** [comment]
You're welcome! Glad to hear it was easy to fix.
