### ISSUE TITLE
依赖报错

### ISSUE THREAD

**Issue by cgj0909** [googleads/google-ads-java#804]
![d54b4a236d48655dbba2705902d7e50b](https://github.com/user-attachments/assets/a2eac1f7-8a8e-40b2-baef-43106e8de3fb)
我该怎么做，并且我也获取不到刷新令牌

**Comment by jradcliff** [comment]
Hi,

Are you using IntelliJ IDEA, and if so, do you have the Gradle plugin installed?

https://plugins.jetbrains.com/plugin/13112-gradle

Thanks,
Josh, Google Ads API Team

**Comment by jradcliff** [comment]
I suggest running the `GenerateUserCredentials` sample from the command line. Some IDEs don't handle the prompts correctly. You can run the sample using Gradle as follows from the `google-ads-java` directory. Substitute the path and filename of the downloaded client JSON file for `YOUR_CLIENT_JSON_FILE`:

`./gradlew -q --console=plain runExample --example='authentication.GenerateUserCredentials --oAuthClientFile YOUR_CLIENT_JSON_FILE'`

If that still gives you trouble, consider following the instructions for using the OAuth Playground to generate credentials at https://developers.google.com/google-ads/api/docs/oauth/playground.
