### ISSUE TITLE
Create AdGroupCriteria Thinks An Attempt To Mutate Negative Is Occurring

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#808]
```
implementation "com.google.api-ads:google-ads:33.0.0"
```

```
request-id=2IEpMtvIKbJXOOkwat_O0w
```

Not sure how prevalent, if at all, this was before 17.1 but we're seeing some weird stuff when attempting to create an AdGroupCriterion Keyword that we're not marking as negative and the error response is saying that attempting to mutate the negative field is not allowed

Also not sure what the actual pattern here is, other than this is a single object create request

If we don't think this is Java library specific I'll kick it over to the support mailing list

Thanks
Pete

```
Request
-------
MethodName: google.ads.googleads.v17.services.AdGroupCriterionService/MutateAdGroupCriteria
Endpoint: googleads.googleapis.com:443
Headers: {REDACTED}
Body: customer_id: "REDACTED"
operations {
  create {
    status: ENABLED
    url_custom_parameters {
      key: "REDACTED"
      value: "REDACTED"
    }
    keyword {
      match_type: EXACT
      text: "boat storage"
    }
    ad_group: "REDACTED"
    cpc_bid_micros: 8000000
  }
}
partial_failure: true
```

```
Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,request-id=2IEpMtvIKbJXOOkwat_O0w,date=Tue, 27 Aug 2024 17:14:47 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000)
Body: results {
}
partial_failure_error {
  code: 3
  message: "The field attempted to be mutated is immutable., at operations[0].create.negative"
  details {
    type_url: "type.googleapis.com/google.ads.googleads.v17.errors.GoogleAdsFailure"
    value: "\n^\n\003\350\003\003\022/The field attempted to be mutated is immutable.\"&\022\016\n\noperations\030\000\022\b\n\006create\022\n\n\bnegative\022\0262IEpMtvIKbJXOOkwat_O0w"
  }
}

Failure message: null
Status: Status{code=OK, description=null, cause=null}.
```

**Comment by jradcliff** [comment]
Hi Peter,

Does the keyword text + match type combination already exist as a _negative_ keyword in the ad group? IIRC, ad group criterion `create` behaves like an upsert, so if the criterion already exists, it'll attempt to update the existing criterion instead of creating another one.

I'm not saying the error message is ideal...just offering this as a possible root cause.

Thanks,
Josh, Google Ads API Team

**Comment by PeterLavetsky** [comment]
This occurred to me a bit after I sent the message and I'm going to operate under the assumption that that's the case.

I'll investigate further on my end and close the task.

Thanks!
Pete
