### ISSUE TITLE
Unable to set Campaign KeywordMatchType to 0 which is "UNSPECIFIED"

### ISSUE THREAD

**Issue by balramknx** [googleads/google-ads-java#809]
**Describe the bug:**
I am unable to set Campaign KeywordMatchType to UNSPECIFIED.

**Steps to Reproduce:**
1. Create Campaign Builder Object
Campaign.Builder campaign = Campaign.newBuilder();
2. Try to assign value to KeywordMatchType
campaign.setKeywordMatchType(CampaignKeywordMatchTypeEnum.CampaignKeywordMatchType.UNSPECIFIED);
3. Pass campaign build while create Campaign Operation 
 CampaignOperation operation = CampaignOperation.newBuilder()
                        .setUpdate(campaign.build())
                        .setUpdateMask(FieldMasks.allSetFieldsOf(campaign).toBuilder()
                                .clearPaths().addAllPaths(maskField)
                        ).build();
Observed campaign does not contains field KeywordMatchType.

**Expected behavior:**

Campaign Builder must contains KeywordMatchType data while create/update

**Client library version and API version:**
Client library version: v17
Google Ads API version: v17
JDK version: JDK8

**Request/Response Logs:**

SUCCESS REQUEST SUMMARY. Method: google.ads.googleads.v17.services.CampaignService/MutateCampaigns, Endpoint: googleads.googleapis.com:443, CustomerID: 1416728966, RequestID: YxShcnWd3ygbkqe4bZVs6w, ResponseCode: OK, Fault: null.

Request
-------
MethodName: google.ads.googleads.v17.services.CampaignService/MutateCampaigns
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=6150134023, x-goog-api-client=gl-java/1.8.0_331__Oracle-Corporation gccl/32.0.0 gapic/32.0.0 gax/2.48.1 grpc/1.62.2}
Body: customer_id: "1416728966"
operations {
  update {
    resource_name: "customers/1416728966/campaigns/21743333277"
    geo_target_type_setting {
      positive_geo_target_type: PRESENCE_OR_INTEREST
      negative_geo_target_type: PRESENCE
    }
    name: "aw search cp 26092024"
    id: 21743333277
    end_date: "20240929"
  }
  update_mask {
    paths: "resource_name"
    paths: "id"
    paths: "name"
    paths: "geo_target_type_setting.positive_geo_target_type"
    paths: "geo_target_type_setting.negative_geo_target_type"
    paths: "end_date"
  }
}

Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,request-id=YxShcnWd3ygbkqe4bZVs6w,date=Mon, 30 Sep 2024 04:11:22 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000)
Body: results {
  resource_name: "customers/1416728966/campaigns/21743333277"
}

Failure message: null
Status: Status{code=OK, description=null, cause=null}.
 
**Anything else we should know about your project / environment:**

For reference i have attached 

Uploading Screen Recording 2024-09-27 at 11.56.33.mov…

recording as well.

**Comment by jradcliff** [comment]
Hi,

The `UNSPECIFIED` value can't be explicitly set since it represents the state where the match type is not set.

https://protobuf.dev/programming-guides/dos-donts/#unspecified-enum

If your goal is to clear the campaign's `keywordMatchType` (so it is no longer `BROAD`), then send an `update` operation where `keywordMatchType` is not set, and include `keyword_match_type` in the `update_mask`.

Thanks,
Josh, Google Ads API Team
