### ISSUE TITLE
How to set up partial http proxy

### ISSUE THREAD

**Issue by zhaoyuan7845** [googleads/google-ads-java#81]
Hello,the following line of code
```
// Send the keyword ideas request.
GenerateKeywordIdeaResponse response =
                    keywordPlanServiceClient.generateKeywordIdeas(requestBuilder.build());
```
It will time out if I don't set the proxy. 
```
System.setProperty("https.proxyHost", "proxyHost");
System.setProperty("https.proxyPort", "proxyPort");
```
But i don't want to use `System.setProperty()` in my project. What should I do? 
Thanks.

**Comment by nwbirnie** [comment]
Hey, you could supply these parameters on the command line, specifying `-Dhttps.proxyHost=proxyHost`. In future we would like to investigate configuring proxy settings from the ads.properties configuration file.

**Comment by dphan72** [comment]
@nwbirnie can command line parameters be used to supply `https.proxyUser` and `https.proxyPassword` for the JAX-WS client?

**Comment by nwbirnie** [comment]
@dphan72 yes, the JAX-WS client should also support the [standard Java proxy configuration params](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html).

**Comment by dphan72** [comment]
@nwbirnie I came across the [JaxWsProxySelector](https://github.com/googleads/adwords-alerting/blob/master/src/main/java/com/google/api/ads/adwords/awalerting/util/JaxWsProxySelector.java#L34), and was wondering if it's still the case where we need to use it as the `ProxySelector` in order for the user and password parameters to be used.

**Comment by nwbirnie** [comment]
Yes it would appear that this is required for the JAX-WS library.
