### ISSUE TITLE
Thread leak issue when using RecommendationServiceClient 

### ISSUE THREAD

**Issue by iwmib** [googleads/google-ads-java#814]
This bug was observed in version 33.0.0 of the java lib.  API version 17. JDK version 17

When calling the dismissRecommendation() method on the RecommendationServiceClient the number of active threads increases and never goes down afterward (threads are not released). See the screenshot attached.

![1](https://github.com/user-attachments/assets/00fd879f-29ba-450d-895c-fd56965d8f40)

It looks like there might be a thread leak issue.

**Comment by jradcliff** [comment]
Are you wrapping your `RecommendationServiceClient` in a [try-with-resources Statement](https://docs.oracle.com/javase/8/docs/technotes/guides/language/try-with-resources.html) so it's closed when the block completes?

```
try (RecommendationServiceClient recommendationClient = 
       googleAdsClient.getLatestVersion().getRecommendationServiceClient()) {
  // make some requests with the client...
} // client closes when this block exits
```

**Comment by iwmib** [comment]
Yes, we are already wrapping the call as you showed.

**Comment by jradcliff** [comment]
No worries, thanks for the prompt update!
