### ISSUE TITLE
Migrating to Ads API, All requests are stuck at Java call GoogleAdsServiceClient.search(SearchGoogleAdsRequest request)

### ISSUE THREAD

**Issue by saidatta** [googleads/google-ads-java#92]
Hey,

I have been migrating my code from Adwords to Google Ads API. I have been attempting to run GetCampaigns example or any other example provided from the repo. It is stuck calling GoogleAdsServiceClient.search(SearchGoogleAdsRequest request) with no errors or results and will be stuck until I abort it manually. console.developers.google.com statistics show no errors as well.

I tried various different configuration permutations.
I added oAuth tokens I used for Adwords and added loginCustomerId as the manager account. And then when I run getCampaigns using a clientCustomerAccount under that MCC, it is stuck

am I missing something obvious?

best regards

**Comment by jradcliff** [comment]
Hi,

In your project, do you happen to have dependencies on both this client library and the [googleads-java-lib](https://github.com/googleads/googleads-java-lib) library for the AdWords API? If so, could you try removing the dependency on the AdWords API library and let me know if you still see stuck requests?

Thanks,
Josh, Google Ads API Team

**Comment by saidatta** [comment]
I dont have any conflicting dependencies in it.

**Comment by jradcliff** [comment]
Hi,

It may not show up as conflicts, but there was at least one case where I saw requests getting stuck when both libraries were included as dependencies. Do you have both of them in your dependency list?

Also, if you're running on Linux or Unix, when the request is stuck could you issue a `kill -3 PID`, where `PID` is the process ID of your `java` process? That should give a stack trace of all of your threads, which will help debug which step in the request/response pipeline is getting stuck.

Thanks,
Josh, Google Ads API Team

**Comment by saidatta** [comment]
Hey Josh,
After your suggestions, I created a new project with my bare bones, java classes, to narrow down if its the dependencies issue. It started working after that! Even though I removed them from my original pom.xml, it might have had some obsolete cache that might have been causing it. Thanks for your help.

**Comment by jradcliff** [comment]
Great! Glad to hear the new project resolved it.

-Josh
